### ISSUE TITLE
Salesforce disabling TLS 1.0

### ISSUE THREAD

**Issue by cramoisan** [forcedotcom/dataloader#100]
As explained here : https://help.salesforce.com/apex/HTViewSolution?id=000221207
Salesforce is disabling TLS 1.0 and API-based software that Salesforce makes available for download, such as the Apex Data Loader, plans to achieve compatibility with TLS 1.1 and TLS 1.2 by the end of the Spring '16 release.
Is this already fixed in the source code or is it on the roadmap?

**Comment by rjmazzeo** [comment]
Master has been updated to require a JDK 1.8. The default protocol in JDK 1.8 is TLS 1.2. The Spring '16 release will have an updated release with these changes at launch.

**Comment by cramoisan** [comment]
Thanks Rocky; does it mean the current release (36.0.0) is not compatible with TLS1.1/1.2 ?
When are you planning to release the updated version? 
Will it be before February 6th when Spring '16 goes live in Production ?

**Comment by rjmazzeo** [comment]
Currently supported release is 35.0.0. 
The next release going into production with Spring '16 is 36.0.0.

Github source version is updated a little early on so we have to time get the download ready.

**Comment by rjmazzeo** [comment]
Oh and 36.0.0 will have mentioned fixes around TLS 1.2
