### ISSUE TITLE
config.process name and LastRun.properties.

### ISSUE THREAD

**Issue by thomasproductions** [forcedotcom/dataloader#1011]
**Describe the bug**
After recently upgrading Dataloader to 59 we have witnessed now that the lastrun.properties file is prepended with the process operation name such as "upsert". We have multiple processes which run in the same batch file. After each process is run it updates the "upsert.lastrun.properties" file with the new date time causing any follow on steps in the batch file to miss out on the records it was suppose to select.

Not sure if this is the place for that? I did find the code in Config.Java that is the root cause of this behavior. I have modified my processes to account for this but would really like for these files to be unique and if they are based on the operation they will not be.

just to be clear, we use the last run date as part of a sql query.

thanks
**To Reproduce**
1. run a process
2. check the lastrundate.properties filename

**Expected behavior**
Should be the process id

**Comment by ashitsalesforce** [comment]
Hi @thomasproductions , can you share the details of your batch file. I am assuming it is a wrapper that repeatedly invokes process.bat with different command line options. Also, share the details of your workaround so that we can better troubleshoot the issue.

**Comment by ashitsalesforce** [comment]
Hi @thomasproductions , can you clarify further the point "the workaround was to replace @process.lastrundate@ with and DATEADD(day,-1,GETDATE())" because rest of the script does not refer to process.lastrundate and does not have DATEADD() in it.

**Comment by thomasproductions** [comment]
the actual sql query is in the database-conf.xml which I cannot share - this is also where the @process.lastrundate@ used to reside.

**Comment by ashitsalesforce** [comment]
Got it. In which way does this relate to name of lastrun.properties file?

**Comment by thomasproductions** [comment]
there are two db calls that are made, both processes are upserts. When the first call is made with the query it dataloader updates the upsert.lastrundate.process file with the new date and time, the next process runs and uses the same file upsert.lastrundate.process which is now 24 hours later from the initial datetime. Here is a portion of the query "where lastrun > @process.lastrundate@".

**Comment by ashitsalesforce** [comment]
@thomasproductions , if you are using `process.lastRunDate` property from `upsert_lastrun.properties` file , the issue will also occur when the first batch executes because the timestamp of the second batch from the previous execution of your script. Checking to better understand why the timestamp of the first batch is an issue for the second batch but the timestamp of the second batch from the previous execution is not an issue for the first batch in the current execution.

**Comment by thomasproductions** [comment]
yes, but the first process.lastRunDate is 24 hours old, second process.lastRunDate is always the current time. The next day the same process.lastRunDate will be 24 hours old. This is a daily process.

**Comment by ashitsalesforce** [comment]
Would it work if `lastrun.properties` prefix is `<process name>_<entity name>_`?

**Comment by thomasproductions** [comment]
anything that would make it unique to the process would work. essentially though, the bean id is unique and I believe that is where the name should come from I suppose:
   <bean id="**thisprocess**" class="com.salesforce.dataloader.process.ProcessRunner" scope="prototype">
   <property name="name" value="**thisprocess**"/>

**Comment by ashitsalesforce** [comment]
Hi @thomasproductions , if the sole purpose is to get a timestamp that's 24 hours or more prior to current time for the query `... where lastrun > @process.lastrundate@`, why not use the current time of the system, subtract 24 hours from it, and specify it in the query? I am asking to better understand your script's dependency on _lastrun.properties value.

**Comment by ashitsalesforce** [comment]
Checked in the change to use process bean name as the prefix for `_lastrun.properties` file name in batch mode and "ui" as the prefix in the interactive mode.
