### ISSUE TITLE
Sandbox OAuth login uses the wrong URL

### ISSUE THREAD

**Issue by jscottfras** [forcedotcom/dataloader#1020]
**Describe the bug**
When attempting to login to a Sandbox with OAuth, the URL in use is login.salesforce.com instead of test.salesforce.com.  This prevents the login from proceeding successfully.

**To Reproduce**
1. Open Dataloader 60.0.2
2. Click on 'Export'
3. Select 'OAuth' from the radio buttons
4. Select Sandbox from the 'Environment' picklist
5. Complete the login on the browser window to a sandbox org (Notice that the login URL is incorrect for a sandbox org)
6. Dataloader continues waiting for the browser to complete the login

**Expected behavior**
After completing the login on the browser, dataloader verifies the login and allows you to continue

**Screenshots**
![image](https://github.com/forcedotcom/dataloader/assets/17574372/7cefe2b9-f62c-4590-a7a0-0dd2ab781635)

**Desktop (please complete the following information):**
 - OS: Mac OS Ventura
 - Version: 60.0.2

**Additional context**

**Comment by ashitsalesforce** [comment]
Go to Settings menu and change Server host to "https://test.salesforce.com". 
<img width="1044" alt="Screenshot 2024-03-13 at 5 03 33 PM" src="https://github.com/forcedotcom/dataloader/assets/71143047/efe31bde-586e-478c-af6f-074b2277aa08">



You will see the right URL when you try to login


<img width="698" alt="Screenshot 2024-03-13 at 5 03 05 PM" src="https://github.com/forcedotcom/dataloader/assets/71143047/ab91e7ae-d045-4738-952f-79b4b62719a5">

**Comment by jscottfras** [comment]
Prior versions of data loader properly selected the correct URL based on the Environment selected.  This is a regression.
