### ISSUE TITLE
"Progress Information" window too small and not resizable

### ISSUE THREAD

**Issue by lorenzoalali** [forcedotcom/dataloader#1028]
**Is your feature request related to a problem? Please describe.**
Unable to see the number of successes/fails during an update within the "Progress Information" window, if the number of records is too big. Text is truncated and that window cannot be resized, info is only available to be seen in the command interface in the background. This is a problem because we cannot easily see if the update is going well (errors happening or not) without having to look at the command window. So, not a deal breaker at all, but UI/UX could be improved here.

**Describe the solution you'd like**
Allow the "Progress Information" window to be resizable

**Describe alternatives you've considered**
Make it a bit larger by default (a few thousands of records to update should not lead to have a screen to be resized)

**Additional context**
Everything in the "..." within the red rectangle is truncated (see red square for original text to be displayed)
![Snag_4e88465](https://github.com/forcedotcom/dataloader/assets/11087992/ae2fda9f-1cc5-4e5f-a402-59565e9f4e40)

**Comment by ashitsalesforce** [comment]
Hi @lorenzoalali , thanks for reporting the issue. The fix to make progress monitor dialog resizable is checked in. It will be available with the next release.
