### ISSUE TITLE
Using a client certificate with Dataloader

### ISSUE THREAD

**Issue by tggagne** [forcedotcom/dataloader#104]
We've a client that is requesting 2-way SSL for all connections to Salesforce.  The documentation on Dataloader I've found so far doesn't mention the word "certificate" anywhere.

Does anyone know if such a feature exists, buried somewhere in a properties file that hasn't been documented yet?

**Comment by rjmazzeo** [comment]
I'm not sure what 2-way ssl is. All communication in v36 uses TLS 1.2 128bit AES (I could have the particular cipher wrong).

The only thing you can do is beef it up to 256bit AES. You would do that by installing JCE unlimited from Oracle.
http://www.oracle.com/technetwork/java/javase/downloads/jce8-download-2133166.html

**Comment by brytonpilling** [comment]
I am not sure what 2-way SSL is either. Would this be similar to an SSL intercepting proxy with a custom root certificate?

**Comment by ashitsalesforce** [comment]
Data Loader v51 supports client certs. Here is the outline of the steps to use it:

Outline of enabling mutual auth in Data Loader using client cert:

1. Upload the client-side certificate - single file containing the cert chain as specified [here](https://developer.salesforce.com/forums/?id=906F0000000BQoLIAW) and [here](https://help.salesforce.com/articleView?id=security_keys_uploading_mutual_auth_cert.htm&type=5).

2. Create a user profile to be "API only" and has “Enforce SSL/TLS Mutual Authentication” enabled.

3. Create a user using the user profile in the previous step.

4. Verify that previous steps are correctly taken and mutual auth is working through curl by following the curl example given [here](https://help.salesforce.com/articleView?id=security_keys_uploading_mutual_auth_cert_api.htm&type=5). 
**Note**: the fullcert.pem file in the example needs to contain the client private key, the client public key, intermediate keys, the CA key in the specified order. Alternately, use a PKCS12 keystore (see below for an example of curl command tha uses PKCS12 keystore).

5. Specify Java system properties `"javax.net.ssl.keyStoreType"`, `"javax.net.ssl.keyStore"`, and `"javax.net.ssl.keyStorePassword"` using `JAVA_TOOL_OPTIONS` environment variable. For example, specify `export JAVA_TOOL_OPTIONS="-Djavax.net.ssl.keyStoreType=PKCS12 -Djavax.net.ssl.keyStore=keystore.pkcs12 -Djavax.net.ssl.keyStorePassword=<keystore password>"` on Mac command shell before running dataloader.command from its installation directory.

6. Launch Data Loader. Uncheck the setting "Reset URL on Login" in "Settings" dialog.

7. Use Password Authentication with the Salesforce Login URL using mydomain URL and port 8443 in the form _"https://<mydomain name>.my.salesforce.com:8443"_.

**Comment by ashitsalesforce** [comment]
Closing the issue as it is fixed.

**Comment by skothakonda-sfdc** [comment]
@ashitsalesforce   Is it possible to use the client certificate in Dataloader CLI. Will the above steps applies for CLI too.

**Comment by ashitsalesforce** [comment]
Hi @skothakonda-sfdc , while we haven't tested it, you should be able to do so because the code paths for the CLI and GUI are identical for handling client certs.

Let us know if you run into any issues in doing so and we will troubleshoot.
