### ISSUE TITLE
Insert Step3 Mapping not resized properly

### ISSUE THREAD

**Issue by PawelWozniak** [forcedotcom/dataloader#1049]
**Describe the bug**
This is continuation of issue https://github.com/forcedotcom/dataloader/issues/1017 

**To Reproduce**
1. Open data loader and choose Insert
2. Navigate to Step 3 Mapping. 
3. If you have more than 7 rows in your CSV file then the table is cut as it doesn't resize properly to available space.

**Expected behavior**
Table is resized to take whole window space

**Screenshots**
<img width="491" alt="2024-03-27_12h48_00" src="https://github.com/forcedotcom/dataloader/assets/5740564/2574166c-4bc2-4206-925f-9779b597ea3b">

Additional improvement could be made to Mapping Dialog which is not set by default the same size as other screens. This cause a need for more scrolling or manual screen resize.
<img width="491" alt="2024-03-27_12h54_17" src="https://github.com/forcedotcom/dataloader/assets/5740564/d4d45f5c-ae4b-42bc-b90f-f366f588986c">

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version  60.0.2 beta from task 1017

**Comment by ashitsalesforce** [comment]
Hi @PawelWozniak , here is a patch containing fix for the issue seen on Mapping page. Is the issue on Mapping dialog that the dialog width or height is too short, thereby requiring resizing or scrolling?

[dataloader_v60.0.2.zip](https://github.com/forcedotcom/dataloader/files/14799321/dataloader_v60.0.2.zip)

MD5 (dataloader_v60.0.2.zip) = c0c31d0e6d3151484f2b62c575a58b6a

**Comment by PawelWozniak** [comment]
Hi @ashitsalesforce 
In step 3 mapping it is now resized correctly to the bottom of the window but columns width are set too big causing horizontal scroll activation.
<img width="491" alt="2024-04-02_13h54_07" src="https://github.com/forcedotcom/dataloader/assets/5740564/0a3a35f5-4dd1-4b03-879f-452e46d0cce8">
Yes I needed manually resize Mapping dialog or do scrolling. Now this windows is by default the same size as other windows causing less scrolling.
Now is much better but it contains the same issue as on previous screen that columns are too wide.
<img width="491" alt="2024-04-02_13h59_08" src="https://github.com/forcedotcom/dataloader/assets/5740564/9e163217-289f-48d4-bf75-cdfc85b1769f">

If you will change how "CSV Column Header" and "Field Name/Relationship" width is set to expand just to main window width and no more the it will be perfect.

**Comment by ashitsalesforce** [comment]
@PawelWozniak , thanks for testing and identifying remaining minor issues. Here is a patch with the fix:

[dataloader_v60.0.2.zip](https://github.com/forcedotcom/dataloader/files/14841831/dataloader_v60.0.2.zip)

MD5 (dataloader_v60.0.2.zip) = d3ff44f4e7ae28adbbda954ce424ece7

**Comment by PawelWozniak** [comment]
@ashitsalesforce now it looks perfect.
<img width="491" alt="2024-04-03_08h22_48" src="https://github.com/forcedotcom/dataloader/assets/5740564/9bb8e7f2-4402-43d6-8594-cf4db131febd">

<img width="491" alt="2024-04-03_08h24_33" src="https://github.com/forcedotcom/dataloader/assets/5740564/8b661cfd-50c3-4e21-a250-4860b125c03f">

All that fixes makes Dataloader more user friendly, thank you.
