### ISSUE TITLE
Data Loader Command Line Tool 20x slower than UI

### ISSUE THREAD

**Issue by MoysieK** [forcedotcom/dataloader#105]
I have posted this issue here  http://salesforce.stackexchange.com/questions/107422/data-loader-command-line-tool-slow.  Im pretty sure it is because it keeps writing logs to the command line but I cant work out how to turn that off.

I am trying to automate a data load using the Command Line tools and have everything working smoothly but it is taking 20x longer than if I do it through the Data Loader GUI.

Below is an exert from my process-conf.xml

> ```
> <bean id="csvUpsertOrderItem"
>       class="com.salesforce.dataloader.process.ProcessRunner"
>       singleton="false">
>     <description>Upsert Transaction Headers into Orders standard object.</description>
>     <property name="name" value="csvUpsertOrderItem"/>
>     <property name="configOverrideMap">
>         <map>
>             <entry key="sfdc.debugMessages" value="false"/>
>             <entry key="sfdc.endpoint" value="CUSTOM ENDPOINT"/>
>             <entry key="sfdc.username" value="USERNAME"/>
>             <entry key="sfdc.password" value="ENCRYPTED PASSWORD"/>
>             <entry key="process.encryptionKeyFile" value="C:\Program Files (x86)\salesforce.com\Data Loader\bin\key.txt"/>
>             <entry key="sfdc.timeoutSecs" value="540"/>
>             <entry key="sfdc.loadBatchSize" value="2000"/>
>             <entry key="sfdc.entity" value="OrderItem"/>
>             <entry key="process.operation" value="upsert"/>
>             <entry key="sfdc.useBulkApi" value="true"/>
>             <entry key="sfdc.bulkApiSerialMode" value="true"/>
>             <entry key="sfdc.externalIdField" value="SlId__c"/>
>             <entry key="process.mappingFile" value="C:\Users\User\Google Drive\Automation\OrdersLine21Jan.sdl"/>
>             <entry key="process.outputError" value="C:\Users\User\downloads\Logs\errorUpsertOrderItem.csv"/>
>             <entry key="process.outputSuccess" value="C:\Users\User\downloads\Logs\successUpsertOrderItem.csv"/>
>             <entry key="dataAccess.name" value="C:\Users\User\Google Drive\Automation\JAEG_TransactionDetails.csv" />
>             <entry key="dataAccess.type" value="csvRead" />
>         </map>
>     </property>     </bean>
> ```

From my research, it seems to be something to do with either the debug log (I think most likely) or batch size.

I have set the sfdc.debugMessages to 'false' so it is not writing the files but it does seem to write it to the command screen.  I feel this could be causing the problem, is there a default log setting?  Maybe a process command setting?

In the data loader document http://resources.docs.salesforce.com/200/6/en-us/sfdc/pdf/salesforce_data_loader.pdf it says the max sfdc.loadBatchSize is 200 but through the UI it sets it to 2000 when batch is true.  If that does restrict it, that could explain it.

**Comment by rjmazzeo** [comment]
the batch size sounds like a typo.
As for logging, you could also change the log4j configuration.
https://developer.salesforce.com/docs/atlas.en-us.dataLoader.meta/dataLoader/using_the_command_line_interface.htm?search_text=log-conf.xml

set the logging level to off to completely disable it. I have not tried this to see if all our logging is going through log4j though. I'll take a look and try to get back to you.

**Comment by rjmazzeo** [comment]
So I dropped the sample log-conf.xml in the bin the folder and set priority="error" and "off". Very little made it to the console after doing that.

**Comment by MoysieK** [comment]
Ok, so that turned the logs off and everything much faster.  

Why does this setting not turn it off <entry key="sfdc.debugMessages" value="false"/>?

**Comment by rjmazzeo** [comment]
It's a little misleading but that setting is for adding additional debugging to the connector's configuration.
https://help.salesforce.com/apex/HTViewHelpDoc?id=loader_params.htm&language=en

It's turned off by default but you can set it to true and it should add debug messaging provided by the Salesforce Web Services Connector.

**Comment by rjmazzeo** [comment]
also it looks like that logger might bypass log4j.

**Comment by ashitsalesforce** [comment]
closing the old issue as it may no longer be relevant.
