### ISSUE TITLE
Data Loader Not Visible/Blank

### ISSUE THREAD

**Issue by dericharris** [forcedotcom/dataloader#1097]
**Describe the bug**
When opening and trying to use Data Loader 60.0.2 on MacOS Sonoma 14.4.1, the UI is not visible, though it seems to respond to clicking, since additional windows will open, but it is all blank. I have JRE 17 installed as well.

**To Reproduce**
1. Open Data Loader
2. The window is blank, nothing can be seen except "Please choose an action from the menu."

**Expected behavior**
A visible UI.

**Screenshots**
![Screenshot 2024-04-18 at 2 07 41 PM](https://github.com/forcedotcom/dataloader/assets/3473207/90fb2743-ef67-4ad1-828b-2f8ef680fd4c)

**Desktop (please complete the following information):**
 - OS: MacOS Sonoma 14.4.1 w/ 
 - Version Data Loader 60.0.2
OpenJDK Runtime Environment Temurin-17.0.10+7 (build 17.0.10+7)

**Comment by ashitsalesforce** [comment]
Hi @dericharris , this is a dup of #1073 . The issue is with specific versions of JRE/JDK (OpenJDK or Eclipse Tamurin). #1073 provides workarounds for the issue.
