### ISSUE TITLE
How do I export the rich text area data type field in Salesforce without an HTML tag by the data loader? How can I get the API of the field in the header in small letters? 

### ISSUE THREAD

**Issue by chimpanzee818** [forcedotcom/dataloader#1155]
Hi @ashitsalesforce 

hope you are doing well!

Can you please help me? I have two queries with DataLoder. 

1. How do I export the rich text area data type field in Salesforce without an HTML tag by the data loader?
2. How can I get the API of the field in the header in small letters too? When we export the data, the header of the CSV is "PRODUCT_COST__C,"  but I want Product_Cost__c" (the actual API of Product_Cost__c).

**Comment by ashitsalesforce** [comment]
Hi @chimpanzee818 ,

Regarding 2, data loader 61.0.0 uses the names specified in select clause of SOQL as-is. Here is an example:
```
SELECT CuStOmDateTiMe__c, Id, RTA__c FROM Account 
```

outputs query results in a csv file with the following headers:
```
"CuStOmDateTiMe__c","Id","RTA__c"
```
Regarding 1, Data Loader currently does not pos-process Rich Text Area fields to remove HTML tags. Does your text contain HTML tags or [HTML character entities](https://www.w3schools.com/html/html_entities.asp) or both?

**Comment by chimpanzee818** [comment]
@ashitsalesforce 

thanks,
It's kind of both.

**Comment by ashitsalesforce** [comment]
Here are a few possible solutions an online search of the term "utility to remove html tags from a string in a csv file" results in:
- [using Excel](https://www.wikihow.com/Remove-HTML-Tags-in-Excel)
- [programmatically in C#, Java, C++, python, and JavaScript](https://www.geeksforgeeks.org/program-to-remove-html-tags-from-a-given-string/)
- [an open source implementation in python](https://github.com/manghat/python-remove-html-from-csv)
- [an online service](https://codebeautify.org/html-stripper)

There may be others. You will have to experiment and settle for the one that works the best for your requirements.

**Comment by ashitsalesforce** [comment]
Hi @chimpanzee818 , submit your feature request for exporting rich text area field without HTML tags and character entities on [IdeaExchange](https://github.com/forcedotcom/dataloader?tab=readme-ov-file#feature-requests). Doing so will help prioritize it among the backlog of feature requests. Closing this issue as point 2 is resolved.

**Comment by chimpanzee818** [comment]
Hi @ashitsalesforce 
ok I will do it!
thanks for your help once gain.
