### ISSUE TITLE
Can not extract rows with NULL relation into database

### ISSUE THREAD

**Issue by r-nasiri** [forcedotcom/dataloader#117]
We have been using the following SOQL to extract from Contact object and insert them into a local database :

`select Id, HomePhone, Account.AccountNumber`

with the new API, we are getting the following exception :

`FATAL dataloader.dao.database.DatabaseContext:175 - Error getting value for SQL parameter: AccountNumber. Please make sure that the value exists in the configuration file or is passed in. Database configuration: insertContactUpdate.`

it works fine if the contacts have an account attached to them, but throws that exception if one of the contacts doesn't have an account attached to it. I've looked at the code and it looks like that Salesforce WS doesn't return "Account.AccountNumber" as a field in sObject if it is null. it doesn't do it for other fields so if for example HomePhone is null, it will be returned with a null value. I am not sure if it is a bug in Salesforce API or it was done on purpose.

**Comment by ashitsalesforce** [comment]
Hi @r-nasiri , does your SQL Insert Bean ("insertContactUpdate"), specified in your database-conf.xml, contain an entry in its sqlParams property for the field that maps to AccountNumber in Salesforce? Here is an example from the [documentation](https://help.salesforce.com/articleView?id=sf.loader_sql.htm&type=5):

```
<bean id="partiesInsertSql"
    class="com.salesforce.dataloader.dao.database.SqlConfig"
    singleton="true">
    <property name="sqlString"/>
        <value>
            INSERT INTO REP.INT_PARTIES (
            BILLING_ADDRESS, SIC_CODE)
            VALUES (@billing_address@, @sic_code@)
        </value>
    </property>
    <property name="sqlParams"/>
        <map>
            <entry key="billing_address" value="java.lang.String"/>
            <entry key="sic_code" value="java.lang.String"/>
        </map>
    </property>
</bean>
```
