### ISSUE TITLE
Unfamiliar with MacOS, Dataloader Installation Issues

### ISSUE THREAD

**Issue by littlegreenguy24** [forcedotcom/dataloader#1193]
**Describe the bug**
Installing Dataloader on a Mac running Ventura 13.1 on an M2 chip. I have downloaded Java as instructed, and successfully installed Dataloader on my computer. When I click on the program to open it, it flashes, and then does nothing. I have done a fair amount of googling, and it seems that Dataloader doesn't always "point" to Azul Zulu, which might be my issue? However, I do not know how to check to be sure, nor fix that if it is the issue. If anyone can help, and give me very clear instructions I would appreciate it! I'm not totally familiar with using the terminal to check or fix issues on a Mac.

**To Reproduce**
1. Go to the Dataloader folder where it is installed.
2. Click on the program.
3. Nothing happens

**Expected behavior**
Dataloader launches and I can log in!

**Desktop (please complete the following information):**
 - OS: Ventura 13.1, M2 chip
 - Version 61.0.0

**Comment by littlegreenguy24** [comment]
Thank you so much @ashitsalesforce I was able to install it correctly, and I am clicking on the installed desktop shortcut and the program file in the installed folder. Would that change your advice?

**Comment by ashitsalesforce** [comment]
@littlegreenguy24 , you must be clicking on `dataloader.app` in the installed folder. Try clicking on `dataloader_console` in the installed folder and share the messages that show up in the command line console so that we can troubleshoot the issue further.

**Comment by littlegreenguy24** [comment]
Thank you @ashitsalesforce, I appreciate the direct instruction! This is what I got:

[REDACTED] ~ % /Users/me/Desktop/DataLoader\ Files/v61.1.0/dataloader_console ; exit;
/Users/me/Desktop/DataLoader Files/v61.1.0/dataloader_console: line 3: /Users/me/Desktop/DataLoader: No such file or directory
/Users/me/Desktop/DataLoader Files/v61.1.0/dataloader_console: line 5: runDataLoader: command not found

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

That is the correct file path.

**Comment by ashitsalesforce** [comment]
Thanks @littlegreenguy24 . There is a bug in the launch script that's triggered if the installation folder path has a space character, which is the case for you `...\DataLoader Files\...`. There are 2 workarounds:
1. Reinstall in `/Users/me/Desktop/DataLoaderFiles/` or a similar folder where the full path has no space character.
2. Modify `/Users/me/Desktop/DataLoader Files/v61.1.0/dataloader_console` script to the following:

```
#!/bin/bash
DL_INSTALL_ROOT="$(dirname "$(readlink -f "$0")")"
source "${DL_INSTALL_ROOT}/util/util.sh"

runDataLoader $@
```
