### ISSUE TITLE
Receiving error message: Error opening CSV file for writing: header row (with column names) has to be provided

### ISSUE THREAD

**Issue by dthompsonusa** [forcedotcom/dataloader#1200]
When trying to export data from an object to a .csv file locally I am getting the error message: Error opening CSV file for writing: header row (with column names) has to be provided

Steps: 
1. log into the Dataloader
2. browse to the folder to download to and then enter the file name to export to "myfile.csv"
3. click next
4. select the object to download data from
5. select the fields to download
6. click next

This should download the records to my file.  Instead I get the error message.

Windows 11
![image](https://github.com/user-attachments/assets/411d3a1a-5b8f-4fac-b599-c7dedbd01d56)

![image](https://github.com/user-attachments/assets/c8c26f0a-24fb-40a4-987a-0440667b57f8)

**Comment by ashitsalesforce** [comment]
Hi @dthompsonusa , the screenshot indicates you are using v59.0.0. Can you use the latest version of Data Loader - [v61.1.0](https://github.com/forcedotcom/dataloader/releases/tag/v61.1.0)?

Also, provide the SOQL you are executing for the extraction and config.properties file after removing all sensitive information such as password, email address, and other personal/company-sensitive information for further troubleshooting.

**Comment by dthompsonusa** [comment]
Thanks for your response.  I am able to run it in v61.1.0.  I think what happened is that I saved a field map as an .sdl and v59.0.0 kept looking at that for the export, even when I changed objects.  

I could not figure out how to uninstall v59.0.0 so its' still on my machine, doesn't seem to be causing any issues so I've left it.  If I should remove it if you could provide instructions on how to do that I would be grateful.

**Comment by ashitsalesforce** [comment]
Hi @dthompsonusa , good to hear that your issue got resolved. While I suspected use of wrong .sdl, I wouldn't have been sure till I first looked at config.properties to discover the use of .sdl and details of sobject you are trying to upload.

As to uninstalling an old version, given that data loader installation does not modify Registry, you can delete the root folder of v59.0.0 to uninstall it.

**Comment by dthompsonusa** [comment]
Awesome, thank you so much!

**Comment by ashitsalesforce** [comment]
Closing out.
