### ISSUE TITLE
Numeric Fields are converted to scientific notation when greater than 10 or 11 digits

### ISSUE THREAD

**Issue by ImranMoTown** [forcedotcom/dataloader#1204]
Numeric Fields are converted to scientific notation when greater than 10 or 11 digits,

As an example:
"AnnualRevenue","Id","type"
"9.9213206E7","0010g00001XiGdjAAF","Account"
"1.15056052E8","0010g00001XiGlnAAF","Account"
"9.0E7","0010g00001XiUntAAF","Account"

This must be converted back to a general format number and loses precision in external systems that are leveraging the data

When run through the developer console, the SOQL returns general format numbers that are not rounded.

**Comment by ashitsalesforce** [comment]
See comment [here](https://github.com/forcedotcom/dataloader/issues/1203#issuecomment-2263896743)

**Comment by ashitsalesforce** [comment]
fixed by the same fix as that for #1203 .
