### ISSUE TITLE
New Version 38.0 of dataloader has oauth option missing

### ISSUE THREAD

**Issue by msrivastav13** [forcedotcom/dataloader#123]
The version 37.0 had a nice interface to do an oauth login for session management and avoided use of the username and password and finding security token .

The version 38.0 seems to be missing the oauth option for login .Check below query on stackexchange 

http://salesforce.stackexchange.com/questions/144684/data-loader-v38-winter-17

**Comment by xbiansf** [comment]
Thanks for posting the issue, Mohith. We are investigating the issue.

**Comment by camisotro** [comment]
Thanks. V37 still working for me. We just have to ensure we keep a copy around until this is handled!

**Comment by xbiansf** [comment]
There is an issue for our release script which cause the configuration not correctly set.  We are review the fix and will release a patch for this.

**Comment by xbiansf** [comment]
New V38.0.1 is now released.  Please let us know if there is any problem.

**Comment by camisotro** [comment]
Thank you. I downloaded from my org and I still ended up with 38.0.0. Any idea when I can expect it to be available?

**Comment by xbiansf** [comment]
Try to download from this place:  https://github.com/forcedotcom/dataloader/releases.   The binary inside the org will take some time to release.
