### ISSUE TITLE
Release v62.0.1.zip MD5 Hash incorrect

### ISSUE THREAD

**Issue by tonnesen-ncqa** [forcedotcom/dataloader#1234]
**Describe the bug**
The assets available at https://github.com/forcedotcom/dataloader/releases/tag/v62.0.1, specifically "dataloader_v62.0.1.zip" is downloading to my system with a MD5 Hash of "5218581D53CE1A958B8239CF94E49072"

The MD5 Hash indicated in the release is "MD5 (dataloader_v62.0.1.zip) = d7df3a121069ae3990d55e0b24894209"

**To Reproduce**
1. Download dataloader_v62.0.1.zip
2. Generate MD5 hash: Get-FileHash -Path .\dataloader_v62.0.1.zip -Algorithm MD5

**Expected behavior**
Generated hash and expected hash match.

**Screenshots**
![image](https://github.com/user-attachments/assets/13ef3c5f-66ac-47b6-a272-e3f84f3c28f1)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version [e.g. 62.0.1]

**Comment by ashitsalesforce** [comment]
Hi @tonnesen-ncqa , thanks for catching this issue. The release notes have a bug - they did not get updated for MD5 sum of v62.0.1 (5218581d53ce1a958b8239cf94e49072). We have fixed the release notes.
