### ISSUE TITLE
Failure on attempt to update records

### ISSUE THREAD

**Issue by IZcld** [forcedotcom/dataloader#1244]
When trying to run an update with a file referencing a related lookup with an external ID. I get the following error:

Progress.NihilistProgressAdapter doneError (NihilistProgressAdapter.java:68) - Failed to find class `com.fasterxml.jackson.databind.ext.CoreXMLSerializers` for handling values of type `javax.xml.namespace.QName`, problem: (java.lang.ClassNotFoundException) com.fasterxml.jackson.databind.ext.CoreXMLSerializers (through reference chain: java.util.HashMap["records"]->java.util.ArrayList[0]->java.util.HashMap[<RELATED_OBJECT__r>]->com.sforce.soap.partner.sobject.SObject["children"]->com.sforce.ws.bind.XmlObject["name"])

I am on v62.0.1, I have reinstalled the application and installed an updated version of java. Neither has fixed the issue. This happened while using the New Update with external Id functionality. When I switched back to using Upsert, it worked.

**Comment by ashitsalesforce** [comment]
Hi @IZcld , can you share a sample csv file, `config.properties` file, the salesforce object you are updating, the referenced object, and the external id field on the referenced object?

**Comment by ashitsalesforce** [comment]
Hi @IZcld , we have been able to reproduce the issue and have checked in the fix. Here is a patched version of Data Loader containing the fix.

[dataloader_v62.0.1.zip](https://github.com/user-attachments/files/16925615/dataloader_v62.0.1.zip)

MD5 (dataloader_v62.0.1.zip) = 1892a754bffc227d7c31a32cd5c05cd6

**Comment by IZcld** [comment]
Thank you!

**Comment by ashitsalesforce** [comment]
closing this issue.
