### ISSUE TITLE
dataloader only supports export/exportAll for CustomMetadata type

### ISSUE THREAD

**Issue by b1nch3f** [forcedotcom/dataloader#128]
dataloader only supports export/exportAll for CustomMetadata type, any plans to support Insert/Update/Upsert/Delete operations?

**Comment by ashitsalesforce** [comment]
data loader is currently in maintenance mode. Only changes made are version updates and critical bug fixes. Please provide more details of your use-case and code changes to support the request in the form of a pull request if possible.
