### ISSUE TITLE
Ok button on Settings disapear on Windows 10

### ISSUE THREAD

**Issue by lioram** [forcedotcom/dataloader#130]
Hi,

I try to modify some option on the dataloader and I can't see the ok button to apply my modification.
I try on v39.0 and v38.0.

Could you please correct this bug?
Thanks in advance

**Comment by lioram** [comment]
The problem is not on windows 10 in fact it is a problem of the screen resolution.
In the Settings panel it has a lot of settings and I could not see the ok button.
Could you reorganise the settings please?

**Comment by ashitsalesforce** [comment]
Closing the issue as Data Loader is in maintenance mode for now with no feature enhancements planned.
