### ISSUE TITLE
terminal warning delays load "No value provided for field"

### ISSUE THREAD

**Issue by bigassforce** [forcedotcom/dataloader#134]
# See [fixed JAR](http://bigass.force.com/data-loader-no-value-provided-for-field) solution

When performing database-to-salesforce loads, there's a terminal nag holding up the batching process.

```
[java] 2017-05-18 17:50:56,959 WARN
[execute] visitor.BulkLoadVisitor writeSingleColumn (BulkLoadVisitor.java:222)
- No value provided for field: RecordTypeId
- No value provided for field: RecordTypeId
- No value provided for field: RecordTypeId
- No value provided for field: RecordTypeId
- No value provided for field: RecordTypeId
- No value provided for field: RecordTypeId
(hundreds of thousands of times)
```

Naturally some of the source data may contain NULL column values - the nag gets streamed to the terminal for each NULL field of each record, delaying the creation of the next Bulk API Batch. The output comes from [Line 222 of BulkVisitorLoader.java](https://github.com/forcedotcom/dataloader/blob/324f42dfb87205d8925e700cdfcc70e684c39101/src/main/java/com/salesforce/dataloader/action/visitor/BulkLoadVisitor.java#L221-L222) and has no configuration to disable it.

See reports elsewhere:
- [Never ending warning message when executing dataloader](https://success.salesforce.com/answers?id=90630000000h4lFAAQ)
- [Error using Cliq dataloader when using Bulk API](https://developer.salesforce.com/forums/?id=906F0000000BNuUIAW)

**Comment by jblotus** [comment]
this would be very handy

**Comment by the1mattkaufman** [comment]
So can we just comment out line 222, does anyone actually want these warnings?

**Comment by bigassforce** [comment]
@the1mattkaufman No - the DBA should decide what NULL means, not salesforce data loader. If we overlooked a real case for these warnings a quick code comment would be great.

**Comment by ashitsalesforce** [comment]
The log level is reduced from "warn" to "debug" in v52. Change the log level for root logger to a higher value than "debug" to suppress the message.
