### ISSUE TITLE
I need some help starting with starting with git.cloning

### ISSUE THREAD

**Issue by PyAuthority** [forcedotcom/dataloader#136]
I am trying to type this on my Linux machine
git clone git@github.com:forcedotcom/dataloader.git

And getting this error:
Permission denied (publickey).
fatal: Could not read from remote repository

What should I do?

**Comment by apoorvashenoy** [comment]
Please try this : git clone https://github.com/forcedotcom/dataloader.git

**Comment by PyAuthority** [comment]
Thanks! Apoorva.
That works.
So, based on the bottom text from https://github.com/forcedotcom/dataloader/,
I tried the second line.

git clone git@github.com:forcedotcom/dataloader.gitgit submodule init
git submodule update
mvn clean package -DskipTests

And I am getting this message:

fatal: Not a git repository (or nay parent up to mount point /home)

Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

What am I supposed to do?

Thanks. Justin

**Comment by apoorvashenoy** [comment]
You are asking me questions that are general Git usage questions and can be answered with a Google Search. Please do the same.
For this issue, first do a cd dataloader before running the commands.
Closing this issue as it is not relevant to Data Loader.
