### ISSUE TITLE
During Mapping columns from source file gets duplicated.

### ISSUE THREAD

**Issue by PawelWozniak** [forcedotcom/dataloader#1376]
**Describe the bug**
When I map fields using "Create or Edit a Map" and drag and drop SF fields to map then field is duplicated and added at the end of the list. Please see pictures below. 

**To Reproduce**
1. Load file start mapping 
2. You will see that fields are duplicated

**Expected behavior**
No fields are duplicated.

**Screenshots**
Before mapping:
<img width="519" alt="2024-11-12_12h56_23" src="https://github.com/user-attachments/assets/69f748ce-e462-44cb-ba72-1377e318659e">
After mapping Vertical and Partner Manager Rating they were duplicated on the list:
<img width="609" alt="2024-11-12_12h56_59" src="https://github.com/user-attachments/assets/fd42ec62-e761-4314-8eee-29ff12746929">

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version [e.g. 62.0.2]

**Comment by ashitsalesforce** [comment]
Hi @PawelWozniak , I tried to reproduce the issue without success with the following fields in a test CSV (perform an upsert on Account sobject):
```
name,oracle_id,richtext,RTA,description,annualRevenue,SLASerialNumber
```
I am unable to see duplicates in mapped fields. I have attached screenshots below. It will help troubleshoot further if you can share the CSV column names and sobject name.


**Mappings dialog before mapping a field**
<img width="595" alt="Screenshot 2024-11-12 at 10 23 36 AM" src="https://github.com/user-attachments/assets/37f36a17-44a5-4c11-9360-34de358de15f">
  
**
**AFTER**
**
  
**User drags and drops "Name" field to map it to "Name" column in the CSV**
<img width="599" alt="Screenshot 2024-11-12 at 10 24 11 AM" src="https://github.com/user-attachments/assets/6e46113a-d37e-4c43-ab6e-762c557cc98c">

**Comment by PawelWozniak** [comment]
I will try to prepare some example file that is not strictly connected with customer data.

**Comment by ashitsalesforce** [comment]
Thank you. I am also wondering if you are able to reproduce issue using a smaller set of CSV columns such as the list I shared with you.

**Comment by ashitsalesforce** [comment]
Hi @PawelWozniak , I am closing this issue assuming that it is not reproducible. Reopen in case you have a reproducible test case whose data is shareable so that we can troubleshoot further.

**Comment by PawelWozniak** [comment]
@ashitsalesforce Please reopen this issue I have an example.
In salesforce I have a field "Is a Billing Contact"

<img width="796" alt="Image" src="https://github.com/user-attachments/assets/c1ef4e49-1092-47bf-8e8f-45beb66a3dc4" />

Using this csv 
[Double field name example.csv](https://github.com/user-attachments/files/20707730/Double.field.name.example.csv)

Reproduction steps.
1. Open Data loader 63.0.0 and click "Insert", authorize it
2. Choose Contact as object and attached csv file, click Next to skip to Step 3 Mapping

<img width="488" alt="Image" src="https://github.com/user-attachments/assets/fc8f3fcc-3ab0-4bbd-ae4c-6d05cc0db724" />

It is missing mapping for Is a Billing Contact.
3. Click Create or Edit a Map
4. Drag Is a billing contact field to map it. Duplicate on the list will be created.

![Image](https://github.com/user-attachments/assets/5862199e-607a-4788-a513-cdb977f0ed7d)
Click OK
You will se now duplication in step details

<img width="614" alt="Image" src="https://github.com/user-attachments/assets/14b80e55-5d7b-4c89-8de3-053e84f25d52" />
Exported mapping seems to look right.

[Duplicated mapping.sdl.txt](https://github.com/user-attachments/files/20707818/Duplicated.mapping.sdl.txt)

As a bonus you can map it twice:

<img width="612" alt="Image" src="https://github.com/user-attachments/assets/f1e4732d-a1e2-4ccd-81a4-bc2c36bda74e" />
Exported mapping will also contain double mapping

[Duplicaded 2.sdl.txt](https://github.com/user-attachments/files/20707847/Duplicaded.2.sdl.txt)

But I haven't tried to import that into the SF.

**Comment by PawelWozniak** [comment]
@ashitsalesforce Checked with 64 and there is no duplicate. Then nothing to do.
