### ISSUE TITLE
Cannot Use Data Loader CLI for Sandbox

### ISSUE THREAD

**Issue by generalzevo** [forcedotcom/dataloader#1384]
**Describe the bug**
I can use the Data Loader GUI to connect to production and sandbox environments. I can also use the CLI version to connect to production. However, **the CLI will not connect to sandbox environments**. CMD shows that Data Loader attempts to connect to login.salesforce.com even though a sandbox URL is specified in the process-conf.xml file. This error does not happen using the same settings and process-conf.xml file for Data Loader CLI v61.1.0.

**To Reproduce**
1. Go to CMD
2. Go to Data Loader bin folder (e.g.: C:\sf\v62.0.2\bin)
3. Enter the command process.bat "path to folder that contains process-conf.xml" task/bean being called from process-conf file.
4. An error message will appears indicating the attempted login to production (i.e.: login.salesforce.com) was unsuccessful.

**Expected behavior**
This should allow users to export, upload, etc. data using the CLI to a sandbox.

**Desktop (please complete the following information):**
 - OS:  Windows 11
 - Version 62.0.2

**Comment by ashitsalesforce** [comment]
Hi @generalzevo , this issue will be addressed in the next release of data loader. Here is a [workaround](https://issues.salesforce.com/issue/a028c00000zj83H/) you can use for v62.0.2.

**Comment by ashitsalesforce** [comment]
Hi @generalzevo , I am closing this issue assuming that the workaround has resolved the issue. Reopen if you are still encountering the same issue.
