### ISSUE TITLE
fatal: Not a git repository

### ISSUE THREAD

**Issue by PyAuthority** [forcedotcom/dataloader#139]
I tried downloading with this command line on my Linux machine.
git clone https://github.com/forcedotcom/dataloader.git
And it donwloaded the folder "dataloader" and its content.

So, I tried next line **git submodule init**
But now, I am getting this error message.

fatal: Not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

What should I do?

**Comment by xbiansf** [comment]
Working fine for me.   Are you able to download other github projects? You can try "git clone git@github.com:forcedotcom/dataloader.git"
Or download as zip?

**Comment by PyAuthority** [comment]
Downloading was fine (the first line), but from second line, it is causing error.

fatal: Not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

**Comment by PyAuthority** [comment]
xbiansf, how can I download a zip?

**Comment by xbiansf** [comment]
Download a zip is an option in the github webpage when you choose to clone/download the repo. 
Google the git error and you can find this to troubleshoot your problem related to git.  https://stackoverflow.com/questions/4630704/receiving-fatal-not-a-git-repository-when-attempting-to-remote-add-a-git-repo
I will close this issue as this is not related to dataloader repo itself.
