### ISSUE TITLE
I am stuck at "mvn clean package -DskipTests"

### ISSUE THREAD

**Issue by PyAuthority** [forcedotcom/dataloader#140]
Previously, I was stuck at the second line "git submodule init", but now I passed second line and third line.
Now, I am stuck at "mvn clean package -DskipTests".

I got these messages:

The program 'mvn' can be found in the following packages:
 '*'  maven    
 **  maven2
Try: sudo apt-get install < selected package >

Sorry. I could not print single "*" on the top lines.. 

I am not sure what to do now..

**Comment by apoorvashenoy** [comment]
Hi again @PyAuthority . Like mentioned earlier, we leave this forum for issues with Data Loader. Please google your build related issues.

**Comment by PyAuthority** [comment]
Sorry.
