### ISSUE TITLE
Login failure

### ISSUE THREAD

**Issue by kudohs** [forcedotcom/dataloader#141]
Finally, I was able to open up GUI with following command:
java -jar target/dataloader-**40.0.0**-uber.jar
Not
java -jar target/dataloader-**40.0**-uber.jar
It appears that there is an error with **40.0** rather than **40.0.0**.

I am not able to login thru my username and password to https://login.salesforce.com.
It says: "Error: Check your username and password, If you still can't log in, contact"

When I looked at Login history from Org ->Set up -> My Setting -> Login History, error message says, "**Failed: API security token required**"

What do I need to do?

**Comment by brytonpilling** [comment]
Have you generated a security token in your org and appended this to your password in dataloader?

**Comment by ashitsalesforce** [comment]
Closing as the issue is likely solved.
