### ISSUE TITLE
Server error returned unknown format for Bulk API export

### ISSUE THREAD

**Issue by sudharsannr** [forcedotcom/dataloader#144]
I'm using Export using Bulk API with authenticated proxy for the data loader where the error "Server error returned unknown format". A quick debug seems that _com.sforce.async.BulkConnection_ is not equipped with authenticated proxy.
```
private InputStream doHttpGet(URL url) throws IOException, AsyncApiException {
        HttpURLConnection connection = config.createConnection(url, null);
        connection.setRequestProperty(SESSION_ID, config.getSessionId());

        boolean success = true;
        InputStream in;
        try {
            in = connection.getInputStream();
        } catch (IOException e) {
            success = false;
            **in = connection.getErrorStream();**
        }
....
}
```

The error caught is a typical _**"HTTP/1.1 407 Proxy Auth Required"**_. This has to be equipped with some additional header changes. This needs a change in the line:
        **`**HttpURLConnection connection = config.createConnection(url, null);**`**
where headers must be passed instead of null.

**Comment by zefreak** [comment]
I also have this issue. Any progress with this?

**Comment by ashitsalesforce** [comment]
Data Loader uses Salesforce WSC for making Bulk API calls. WSC currently does not support proxy per issue reported [here](https://github.com/kvrsfdc/sfdc-wsc/issues/34).
