### ISSUE TITLE
Dataload error - Expected batch state to be Completed or Failed, but was InProgress

### ISSUE THREAD

**Issue by zefreak** [forcedotcom/dataloader#146]
I am using v41 of the dataloader from the command line. I am getting several exceptions inconsistently. It is usually this error:
'LoadException: Server error returned in unknown format' caused by AsyncApiException exceptionCode='ClientInputError'

followed by another error:
Expected batch state to be Completed or Failed, but was InProgress (I have also seen Queued).

I am not sure if these errors are related but they also occur inconsistently, rerunning the dataload will sometimes work.

**Comment by zefreak** [comment]
If it helps, running the dataloader v37 gives me different errors:

com.sforce.ws.ConnectionException: Failed to send request to https://login.salesforce.com/services/Soap/u/37.0
peer not authenticated

I also get the following in 37
LoadException - Expected 10000 to be processed for batch but got results for 8000.

All of these issues only started occurring in the last few days, after running successfully for months.

**Comment by ashitsalesforce** [comment]
Closing as we are now at v51 and likely the issue no longer exists.
