### ISSUE TITLE
Could not execute on macOS 10.12

### ISSUE THREAD

**Issue by hymmm** [forcedotcom/dataloader#157]
I've downloaded ApexDataLoader.dmg v42. Try to run it on Finder, but it just shows 

> Java 1.8 is required but could not be found. Please visit http://java.com/download 

even if Java8 was installed. 

```
$ java -version
java version "1.8.0_162"
Java(TM) SE Runtime Environment (build 1.8.0_162-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.162-b12, mixed mode)
```

Then tried to run it via terminal as README.md says,

> Use the command below to run the Data Loader GUI on Mac
> java -XstartOnFirstThread -jar target/dataloader-xx.0-uber.jar

But failed as below.

```
$ java -jar /Applications/Data\ Loader.app/Contents/Java/com/force/dataloader/42.0.0/dataloader-42.0.0.jar 
/Applications/Data Loader.app/Contents/Java/com/force/dataloader/42.0.0/dataloader-42.0.0.jarにメイン・マニフェスト属性がありません
```
It is in Japanese  “no main manifest attribute” error.

Is there any workaround?

**Comment by ashitsalesforce** [comment]
Closing as this issue is not relevant due to major DL and MacOS upgrades since reported.
