### ISSUE TITLE
Stop using exponential notation for numeric field with more than 8 digits

### ISSUE THREAD

**Issue by RedaBenh** [forcedotcom/dataloader#161]
Hi,
I am trying to export data with numeric field (Currency or number) where it has more than 8 digits. 
The generated CSV file has an invalid format and break integration with other systems (a lot of systems or programming language cannot parse exponential notation).

Exemple:
```
In Salesforce UI   |  In Dataloader export
80,000,000.00     |   8.0E7
```

This occur value greater than 10,000,000. 
Please notice that CSV file is not an Excel file, so there is no confusion here !

There is one workaround : Use text formulat with `TEXT(FIELD_NUMBER_NAME)`

Thanks,

**Comment by bigassforce** [comment]
Same issue applies when using JDBC to insert records into SQL Server with prepared statements.

Workaround is to `CAST` the number columns accordingly, for example:

```
<bean class="com.salesforce.dataloader.dao.database.SqlConfig" id="extractSql" singleton="true">
    <property name="sqlString">
        <value>
            INSERT INTO [Accounts]
            (SELECT Id, AnnualRevenue)
            VALUES
            (@Id@, CAST(@AnnualRevenue@ AS REAL))
        </value>
    </property>
    <property name="sqlParams">
        <map>
            <entry key="Id" value="java.lang.String" />
            <entry key="AnnualRevenue" value="java.lang.Double" />
        </map>
    </property>
</bean>
```

**Comment by ashitsalesforce** [comment]
Closing out old issue as we are right now in a maintenance mode for Data Loader and a workaround exists.
