### ISSUE TITLE
Cannot set multiple fields to the same constant value in mapping file

### ISSUE THREAD

**Issue by gsbasso** [forcedotcom/dataloader#162]
Data Loader has long supported the ability to specify a constant value for a field in the mapping file as per the below example.

`"value"=MyField__c`

However, if you try to set multiple fields to the same constant value only one field is updated – the others remain unchanged. It's not clear how Data Loader determines what field is updated.

`"value"=MyField1__c`
`"value"=MyField2__c`

Granted, setting multiple fields to the same value is not a typical requirement, except in the case where you want to clear (i.e. blank out) multiple fields. We do this after refreshing a sandbox to remove any sensitive production data (we also obfuscate some content but for certain fields it's just simpler to blank out the value).

`"\ "=MyField1__c`
`"\ "=MyField2__c`

**Comment by bigassforce** [comment]
Does delimiting the fields with commas work for your use case?

> If you have multiple fields that should contain the same value, you must specify the constant and the field names separated by commas. For example, if you’re importing data, the syntax would be "constantvalue"=field1, field2.
> 
> https://developer.salesforce.com/docs/atlas.en-us.dataLoader.meta/dataLoader/loader_columns.htm

Example SDL file:

![screen shot 2018-11-30 at 13 47 50](https://user-images.githubusercontent.com/6777144/49292955-923cb280-f4a6-11e8-93c6-cc7e397cc37f.png)

**Comment by gsbasso** [comment]
Hi,

Yes that does work! I'd no idea Data Loader supported such a feature.

Thanks,
Gino

**Comment by ashitsalesforce** [comment]
Closing the issue as it is addressed by comments above.
