### ISSUE TITLE
CSVReader throws the CSVParseException and nowhere it is caught in CSVFileReader to take advantage of line no in exception object

### ISSUE THREAD

**Issue by balwinderkumar** [forcedotcom/dataloader#164]
CSVFileReader should make use of line no in case if there is CSVParseException is thrown by CSVReader to print the line no in logs.

**Comment by ashitsalesforce** [comment]
Closing this enhancement request as we are right now in a maintenance mode for Data Loader. Moreover, DataAccessRowException thrown by CSVFileReader specifies the line number.
