### ISSUE TITLE
Dataloader should be able to set the User Email Header

### ISSUE THREAD

**Issue by IamDrowsy** [forcedotcom/dataloader#167]
As importing Users using Dataloader is a common and [documented](https://help.salesforce.com/articleView?id=000007571&language=en_US&type=1) use case, DataLoader should also be able to generate the user welcome emails. 

This should be easily achieved by setting the [email header](https://developer.salesforce.com/docs/atlas.en-us.api.meta/api/sforce_api_header_emailheader.htm#topic-title) and making it configurable.

**Comment by ashitsalesforce** [comment]
data loader is currently in maintenance mode with only critical bug fixes going in. We will review the proposed code change to address the ask if you create a pull request containing the code change.
