### ISSUE TITLE
Build Error: Execution default of goal sh.tak.appbundler:appbundle-maven-plugin:1.0.4:bundle failed

### ISSUE THREAD

**Issue by rmccu** [forcedotcom/dataloader#168]
When I try to build on a Mac I get this error:

> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time:  14.321 s
> [INFO] Finished at: 2018-11-15T20:48:39-07:00
> [INFO] ------------------------------------------------------------------------
> [ERROR] Failed to execute goal sh.tak.appbundler:appbundle-maven-plugin:1.0.4:bundle (default) on project dataloader: Execution default of goal sh.tak.appbundler:appbundle-maven-plugin:1.0.4:bundle failed: An API incompatibility was encountered while executing sh.tak.appbundler:appbundle-maven-plugin:1.0.4:bundle: java.lang.ExceptionInInitializerError: null
> [ERROR] -----------------------------------------------------
> [ERROR] realm =    plugin>sh.tak.appbundler:appbundle-maven-plugin:1.0.4
> [ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
> [ERROR] urls[0] = file:/Users/ryan/.m2/repository/sh/tak/appbundler/appbundle-maven-plugin/1.0.4/appbundle-maven-plugin-1.0.4.jar
> [ERROR] urls[1] = file:/Users/ryan/.m2/repository/org/codehaus/plexus/plexus-velocity/1.1.8/plexus-velocity-1.1.8.jar
> [ERROR] urls[2] = file:/Users/ryan/.m2/repository/junit/junit/3.8.1/junit-3.8.1.jar
> [ERROR] urls[3] = file:/Users/ryan/.m2/repository/commons-collections/commons-collections/3.1/commons-collections-3.1.jar
> [ERROR] urls[4] = file:/Users/ryan/.m2/repository/velocity/velocity/1.5/velocity-1.5.jar
> [ERROR] urls[5] = file:/Users/ryan/.m2/repository/commons-lang/commons-lang/2.1/commons-lang-2.1.jar
> [ERROR] urls[6] = file:/Users/ryan/.m2/repository/oro/oro/2.0.8/oro-2.0.8.jar
> [ERROR] urls[7] = file:/Users/ryan/.m2/repository/org/codehaus/plexus/plexus-archiver/1.0-alpha-7/plexus-archiver-1.0-alpha-7.jar
> [ERROR] urls[8] = file:/Users/ryan/.m2/repository/org/codehaus/plexus/plexus-utils/1.2/plexus-utils-1.2.jar
> [ERROR] urls[9] = file:/Users/ryan/.m2/repository/javax/enterprise/cdi-api/1.0/cdi-api-1.0.jar
> [ERROR] urls[10] = file:/Users/ryan/.m2/repository/com/google/guava/guava/10.0.1/guava-10.0.1.jar
> [ERROR] urls[11] = file:/Users/ryan/.m2/repository/com/google/code/findbugs/jsr305/1.3.9/jsr305-1.3.9.jar
> [ERROR] urls[12] = file:/Users/ryan/.m2/repository/org/sonatype/sisu/sisu-guice/3.1.0/sisu-guice-3.1.0-no_aop.jar
> [ERROR] urls[13] = file:/Users/ryan/.m2/repository/aopalliance/aopalliance/1.0/aopalliance-1.0.jar
> [ERROR] urls[14] = file:/Users/ryan/.m2/repository/org/eclipse/sisu/org.eclipse.sisu.inject/0.0.0.M5/org.eclipse.sisu.inject-0.0.0.M5.jar
> [ERROR] urls[15] = file:/Users/ryan/.m2/repository/org/eclipse/aether/aether-util/0.9.0.M2/aether-util-0.9.0.M2.jar
> [ERROR] urls[16] = file:/Users/ryan/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.19/plexus-interpolation-1.19.jar
> [ERROR] urls[17] = file:/Users/ryan/.m2/repository/org/codehaus/plexus/plexus-component-annotations/1.5.5/plexus-component-annotations-1.5.5.jar
> [ERROR] urls[18] = file:/Users/ryan/.m2/repository/org/sonatype/plexus/plexus-sec-dispatcher/1.3/plexus-sec-dispatcher-1.3.jar
> [ERROR] urls[19] = file:/Users/ryan/.m2/repository/org/sonatype/plexus/plexus-cipher/1.4/plexus-cipher-1.4.jar
> [ERROR] Number of foreign imports: 1
> [ERROR] import: Entry[import  from realm ClassRealm[maven.api, parent: null]]
> [ERROR] 
> [ERROR] -----------------------------------------------------
> [ERROR] : multiple points
> [ERROR] -> [Help 1]
> [ERROR] 
> [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
> [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> [ERROR] 
> [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginContainerException

**Comment by xbiansf** [comment]
I do not see this issue in mac. Maybe try to start from a new clone.

**Comment by xyc** [comment]
I had the similar issue. My java version is 11.0.1. I saw a similar issue from https://github.com/spotify/dockerfile-maven/issues/77

Adding this to appbundle-maven-plugin section in pom.xml resolves it.
```xml
                    <artifactId>appbundle-maven-plugin</artifactId>
                    ...
                    <dependencies>
                      <dependency>
                        <groupId>org.codehaus.plexus</groupId>
                        <artifactId>plexus-velocity</artifactId>
                        <version>1.2</version>
                      </dependency>
                    </dependencies>
```

**Comment by ashitsalesforce** [comment]
Closing this issue as plexus-velocity is removed from dependencies list in v51, which should address the issue.
