### ISSUE TITLE
Desktop folder path different with OneDrive

### ISSUE THREAD

**Issue by Feldhacker** [forcedotcom/dataloader#180]
With DLv45 on Windows, the new install.bat file creates the desktop shortcut in the standard location "%USERPROFILE%\Desktop".
However, if Microsoft OneDrive is installed and AutoSave configured to protect the Desktop folder, then the Desktop folder path is different, like "%USERPROFILE%\OneDrive - My Company\Desktop".
The result is that the Data Loader icon does not actually appear on the user's desktop.

Given the prevalence of OneDrive use in some corporate environments, it would be helpful if the installer would detect the actual location of the Desktop folder rather than assuming.

**Comment by xbiansf** [comment]
Thanks for the feedback.  I will create a work item internally to track this issue.

**Comment by ashitsalesforce** [comment]
Closing as we are not adding new feature enhancements at this point. Will go through this and other issues when we do more active development in the future.
