### ISSUE TITLE
Make runtime JDK independent

### ISSUE THREAD

**Issue by Feldhacker** [forcedotcom/dataloader#181]
It is understandable if a specific openJDK distribution might be required for compilation purposes, or documented for "official support" purposes.
However, at normal runtime, the Data Loader launch scripts should be JDK independent -- either relying on java that is available on the Path, or relying on the JAVA_HOME environment variable.

Data Loader works just fine with Amazon Corretto, Amazon's supported distribution of OpenJDK.

**Comment by xbiansf** [comment]
Good suggestion.  We will consider it for the next release.

**Comment by cachan** [comment]
Data Loader also works without any issues with the AdoptOpenJDK 11 on macOS, installed using `macports`:
```
$ java -version
openjdk version "11.0.3" 2019-04-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.3+7)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.3+7, mixed mode)
```

Also, the macOS launcher doesn't force you to use a particular Java distribution - the Windows launcher examines `C:\Program Files\` paths to ensure the Zulu JDK (not JRE) is installed.

**Comment by ucgit2rg** [comment]
Has Data loader been made JDK independent in 47.0.0? I am trying to install it with Amazon Corretto OpenJDK11 but its not recognizing that JDK and is still asking for Zulu OpenJDK 11.

**Comment by ashitsalesforce** [comment]
This issue will be addressed in v52. The fix is checked in on github.
