### ISSUE TITLE
HTTPS only broke my workflow

### ISSUE THREAD

**Issue by Goobles** [forcedotcom/dataloader#183]
This change broke our workflow: #154 
We use a locally running proxy to do authentication for us.
A server would be running at `localhost:5678` that would expose an authentication endpoint that dataloader could use to get credentials without having to use OAuth. 

Since we can only use HTTPS now, this has become an issue.

**Comment by ashitsalesforce** [comment]
Data Loader is in maintenance mode and we are not making any enhancements or fixes. Moreover, the requested change seems to open up a security risk for users. Perhaps there is a way to support https traffic between data loader and your local proxy? See https://stackoverflow.com/questions/516323/https-connections-over-proxy-servers as an example.
