### ISSUE TITLE
Unable to log out

### ISSUE THREAD

**Issue by Ted-Staub-MBA** [forcedotcom/dataloader#184]
Unable to log out.  Clicking on the logout button does nothing.  I exit and restart Data Loader and I'm still logged in.

No errors are displayed in the Data Loader Command Prompt

How do I even verify which environment I'm logged into?  I manage over 100 Sandboxes and need a visual to confirm which environment I'm using.
I figured I'd log out and log back in again to be 100% certain which Sandbox I'm connected to.

Details:
Windows 10 Pro 64 bit
Data Loader v45
OpenJDK 11.0.x

**Comment by samuel012** [comment]
This also happens to me today.

Details:
- Windows 10 x64
- Data Loader v47
- Zulu OpenJDK 11.0.x

**Comment by ashitsalesforce** [comment]
Unable to reproduce the issue on Windows 10 with Data Loader v51.
