### ISSUE TITLE
Need to display connected environment in the Window Title or UI Interface

### ISSUE THREAD

**Issue by Ted-Staub-MBA** [forcedotcom/dataloader#185]
How do I verify which environment I'm logged into?  I manage over 100 Sandboxes and need a visual to confirm which environment I'm using.

Can you add the environment to the Windows Title or add to the UI?

Details:
Windows 10 Pro 64 bit
Data Loader v45
OpenJDK 11.0.x

**Comment by ashitsalesforce** [comment]
Data Loader is in maintenance-only mode. We are not currently adding new features and will only release a new version of the tool as part of the Salesforce major release cadence or to resolve high severity issues.
