### ISSUE TITLE
Launching on Windows should check ZULU_JAVA_HOME and JDK version

### ISSUE THREAD

**Issue by identigral** [forcedotcom/dataloader#188]
dataloader.bat, version 46:

```
:CheckOpenJdk11
    REM: Todo, we need to improve this to better detect JAVA 11+, rather than depending on default zulu installed folder.
    echo Data Loader requires Zulu OpenJDK 11. Checking if it is installed...
    for /F "delims=" %%a in ('powershell -Command "foreach($path in (Get-ChildItem Env:Path).value -split ';') { if($path -like '*zulu*') { $jdkDir = $path -split 'bin\\' }}; echo $jdkDir"') do Set "ZULU_JAVA_HOME=%%a"
    if "%ZULU_JAVA_HOME%"=="" (
        echo Zulu OpenJDK is not installed. Download Zulu OpenJDK 11 for Windows here:
        echo    https://www.azul.com/downloads/zulu/zulu-windows/
        PAUSE
        goto Exit
    )
```

That first comment in the script is, well, yeah. Several ways to do so: https://stackoverflow.com/questions/18890926/how-to-get-the-java-version-in-powershell

Even if the script did perform a better version check, it should first see if ZULU_JAVA_HOME is set in the environment and use the value of that. If ZULU_JAVA_HOME is not set, then try to discern it via the Path.

**Comment by ashitsalesforce** [comment]
Closing the issue as the check will be done for JRE v11 or later in v52.
