### ISSUE TITLE
Display size

### ISSUE THREAD

**Issue by veranscoto** [forcedotcom/dataloader#192]
There's simply no reason that fields should be unsized at 4k (or even 1920x1080!) at this point in time.

![image](https://user-images.githubusercontent.com/45440797/64057529-00f08e80-cb53-11e9-8fb6-8172c0579133.png)

**Comment by adepew** [comment]
You can fix this in Windows 10 by following these steps:

1. Navigate to the Zulu installation directory bin folder. (C:\Program Files\Zulu\zulu-11\bin)
2. Right-Click on javaw and select "Properties".
3. Click the "Compatibility" tab.
4. Click the "Change high DPI settings" button.
5. Check the "Override high DPI scaling behavior." checkbox.
6. Select "System (Enhanced)" in the drop down menu and then hit OK
7. Run Dataloader again

**Comment by tonyfederer** [comment]
@adepew's workaround worked for me, but I had to do it for java.exe, not javaw.exe.

**Comment by ashitsalesforce** [comment]
Closing as the workaround works.
