### ISSUE TITLE
Unable to export when Bulk API enabled - version 46.1.0

### ISSUE THREAD

**Issue by milosmac94** [forcedotcom/dataloader#193]
46.1 update which has a fix for compound fields issue is now having a problem where, when Bulk API is enabled, export is failing. Exporting works when Bulk API is disabled.

Steps to recreate:
1. Enable Batch API in Settings (check Use Bulk API option);
2. Select object to export (e.g. Account);
3. Choose the export file name and location
4. Select all fields;
5. Hit Finish;
6. Error appears:
![image](https://user-images.githubusercontent.com/17649996/64134392-d7976300-cddd-11e9-9c6f-37b317396744.png)

**Comment by ashitsalesforce** [comment]
Closing as there are no other reports of the issue as of v51.
