### ISSUE TITLE
Bulk api V2

### ISSUE THREAD

**Issue by Doglesby** [forcedotcom/dataloader#195]
Will the Data loader ever be able to use bulk api V2? The use case is that we currently use a VB Script that uses a BCP command to export data to a .csv file. The same VB script then uses the Data loaders dos command prompt commands to load the data into Salesforce. We then have a scheduled task on the server to run the script. When I use enable bulk API, Salesforce still shows them on V1 of bulk load and not V2.

**Comment by ashitsalesforce** [comment]
Hi @Doglesby , will moving to bulk v2 support your use-case better? If so, how?

**Comment by ashitsalesforce** [comment]
Closing the issue as Data Loader is currently in a strict maintenance mode.

**Comment by ashitsalesforce** [comment]
@Doglesby , the latest version of Data Loader (v61.1.0) supports Bulk v2.
