### ISSUE TITLE
Buttons do not render on screen when run from Linux

### ISSUE THREAD

**Issue by the1mattkaufman** [forcedotcom/dataloader#197]
Buttons in the bottom left and bottom right corners of screens are rendered off the screen/window when running the Dataloader on Linux.
![ink](https://user-images.githubusercontent.com/15354688/66875483-52b67200-ef63-11e9-89a3-86fa5f51e4c1.png)

**Comment by ashitsalesforce** [comment]
This may be a bug in Eclipse SWT on linux.
