### ISSUE TITLE
Add configruation options for reporting success and error.

### ISSUE THREAD

**Issue by manojtrek** [forcedotcom/dataloader#198]
Log errors in logs instead of CSV.
Must have ability to write back salesforce Id in destination(s) instead of CSV.

**Comment by ashitsalesforce** [comment]
data loader is in maintenance mode right now with only critical bug fixes and version upgrade allowed. We will review this and other feature requests when we do more active development. Feel free to submit a PR meanwhile if you have a code contribution to make. We will review and decide the next steps.
