### ISSUE TITLE
Error converting value to correct data type: Boolean

### ISSUE THREAD

**Issue by AyyappanNadar** [forcedotcom/dataloader#205]
Hi,

The below error appeared in data loader execution while converting from CSV cell value : space/y/n to salesforce object boolean field. 

--------------------------------Error --------------------------------
visitor.DAOLoadVisitor visit (DAOLoadVisitor.java:93) - Error converting value to correct data type:  
org.apache.commons.beanutils.ConversionException:  
	at com.salesforce.dataloader.dyna.BooleanConverter.convert(BooleanConverter.java:117)
--------------------------------Error --------------------------------

the conversion works fine when cell value is empty, null, y or n but it failed for space.

And looks like this can be corrected in below line with trim on value string before checking the length.

https://github.com/forcedotcom/dataloader/blob/44cabefe93b7a768bc36b0d35de903ef8896e3f4/src/main/java/com/salesforce/dataloader/dyna/BooleanConverter.java#L92

Any thoughts ??

**Comment by ashitsalesforce** [comment]
Thanks for reporting the issue. This issue will be addressed in v52. The new code in BooleanConverter.java is

```
    public Object convert(Class type, Object value) {

        if (value == null || value instanceof Boolean) {
            return value;
        }
      
        String stringValue = value.toString().trim();
        if (stringValue.length()==0) {
            return null;
        }
```
