### ISSUE TITLE
Windows installer fails - xcopy error

### ISSUE THREAD

**Issue by fdinkler-mbx** [forcedotcom/dataloader#206]
The v48 install.bat has the xcopy command:      xcopy . "%INSTALLATION_DIR%" /e /i
This command didn't copy the files in dataloader-win folder.
When I replaced the dot with an asterix, it worked...       xcopy * "%INSTALLATION_DIR%" /e /i

**Comment by ashitsalesforce** [comment]
Data Loader installs in %USERPROFILE%\%DIR_NAME%\v%DATALOADER_VERSION% folder, where DIR_NAME is the directory specified by the user. If you specify "dataloader-win" when install.bat prompts to specify the installation directory, install.bat for v51 will install data loader in "%USERPROFILE%\dataloader-win\v51.0.1" folder.
