### ISSUE TITLE
Unable to import file with field value greater than 80,000

### ISSUE THREAD

**Issue by ameyadreamwares** [forcedotcom/dataloader#207]
Since a Text Area (Long) permits 131,072 characters max, it makes sense for records having such long strings to be imported successfully. This is currently not possible and an error is thrown instead.

**Comment by ashitsalesforce** [comment]
Hi @ameyadreamwares , can you provide the details of the error thrown such as messages logged, error dialog shown?

Thanks.

**Comment by ashitsalesforce** [comment]
Hi @ameyadreamwares , looks like this is a [limit of Bulk API v1](https://developer.salesforce.com/docs/atlas.en-us.salesforce_app_limits_cheatsheet.meta/salesforce_app_limits_cheatsheet/salesforce_app_limits_platform_bulkapi.htm) that Data Loader uses. A workaround is to disable "Use Bulk API" in Settings.
