### ISSUE TITLE
Unable to use a proxy with more than 4 digits in the port number

### ISSUE THREAD

**Issue by brytonpilling** [forcedotcom/dataloader#211]
Dataloader currently does not allow a user to specify a proxy port with greater than 4 digits. The UI only has space for four digits, and if 5 digits is used in the configuration file it is truncated.

Pull request #202 fixes this bug.

**Comment by ashitsalesforce** [comment]
@brytonpilling , thanks for your contribution. I have merged your PR. It will be available in v52.
