### ISSUE TITLE
GUI is difficult to use when using Dark Mode on macOS

### ISSUE THREAD

**Issue by tcyrus** [forcedotcom/dataloader#213]
The Data Loader app seems to be incompatible with Dark Mode on macOS. The buttons are not visible and white screen covers up text and buttons.

![Screen Shot 2020-08-10 at 2 23 03 PM](https://user-images.githubusercontent.com/4201229/89944791-6451c000-dbee-11ea-8e1a-fb3288f0faf5.png)

Currently running macOS Catalina 10.15.6 (19G73)

**Comment by dannywalshzego** [comment]
I had the same problem as tcyrus. I tried changing to Light mode and there was no difference.

Also currently running macOS Catalina 10.15.6 (19G73)

**Comment by shinonome128** [comment]
I solved it. Hope this help you.

#### set up .bash_profile

```
export PATH="$HOME/.jenv/bin:$PATH"
eval "$(jenv init -)"
```

#### install jenv

```
mkdir ~/.jenv
mkdir ~/.jenv/versions
brew install jenv
jenv add /Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home
jenv global zulu64-11.0.9
```

**Comment by ashitsalesforce** [comment]
Closing the issue as it is resolved.
