### ISSUE TITLE
Are pull requests still being accepted?

### ISSUE THREAD

**Issue by brytonpilling** [forcedotcom/dataloader#216]
It seems like there is very little in the way of Pull Requests from the community being accepted/merged. Is dataloader no longer being actively maintained by Salesforce?

**Comment by krissirk** [comment]
Hello @brytonpilling - Data Loader is in maintenance-only mode. We are not currently evaluating PRs and will only release a new version of the tool as part of the Salesforce major release cadence or to resolve high severity issues.

**Comment by brytonpilling** [comment]
Thanks @krissirk - appreciate the reply. Little bit sad as the pull request I submitted in January was my first ever :( Oh well.  Appreciate the update!

Will you guys be adding a comment to indicate this on the Readme, so others are aware of the current status?

**Comment by ashitsalesforce** [comment]
Closing the issue.
