### ISSUE TITLE
dataloader.bat needs improvement 

### ISSUE THREAD

**Issue by roeschter** [forcedotcom/dataloader#225]
I proposed numerous changes
- Allow for override
	- set ZULU_JAVA_HOME
	- Check for ZULU_JAVA_HOME in script
- Print java -version in start script
- Check version 11 in 
- Better failure messages

**Comment by ashitsalesforce** [comment]
Hi @roeschter , these issues are addressed in v52. It checks for JRE 11 or higher in the PATH, which enables you too use your favorite JRE.
