### ISSUE TITLE
Start with console hidden/minimised

### ISSUE THREAD

**Issue by 29039** [forcedotcom/dataloader#227]
Ideally it would be nice if the console was fully hidden as it doesn't serve any purpose to the user.

If that is too much work, there is an easy way to make to start minimised until then.

In the install.bat, when it comes to shortcut creation, just add in `$Shortcut.WindowStyle = 7` and this will make it so that the shortcuts it creates will make the console start minimised but the main application window still comes up without being minimised.

**Comment by ashitsalesforce** [comment]
The console provides feedback on whether right JRE version is installed at the start time and gives the user a quick glance at console messages. You can have the console showing up in minimized state when launching through the desktop link by 
- right click on the desktop icon
- select "Properties"
- select "Shortcut" tab
- select "Minimized" from the dropdown for "Run"
