### ISSUE TITLE
Data loader functionality issue.

### ISSUE THREAD

**Issue by georgebettley** [forcedotcom/dataloader#234]
Hi,

Since I got a new laptop (MacOS Big Sur) and re-installed data loader I have been experiencing multiple issues. Originally it was the blank screen issue that has now been fixed.

However, now when I try to browse files for my CSV upload it greys out and doesn't change over time. I have tried redownloading Zulu and Data Loader, but the problem persists.
<img width="567" alt="Screenshot 2020-12-08 at 17 40 50" src="https://user-images.githubusercontent.com/43244833/101624884-89c2cf00-3a12-11eb-97c2-181e34f19994.png">

![](https://user-images.githubusercontent.com/43244833/101924158-3c885e00-3bc8-11eb-9d38-40e0c01986c7.png)

I'm using Mac OS 11 however the above issue was happening when i was running Zulu 11 (10.13 or later).

When I tried loading with MacOS 11 or later version of Zulu, i get this error:

![](https://user-images.githubusercontent.com/43244833/102077175-cb7fbb00-3e00-11eb-892a-5a03ff4b1a70.png)

**Comment by georgebettley** [comment]
Issue still persisting

**Comment by georgebettley** [comment]
```
<img width="570" alt="Screenshot 2020-12-11 at 15 47 18" src="https://user-images.githubusercontent.com/43244833/101924118-2d091500-3bc8-11eb-8793-bf877a397524.png">

```

**Comment by georgebettley** [comment]
<img width="570" alt="Screenshot 2020-12-11 at 15 47 18" src="https://user-images.githubusercontent.com/43244833/101924158-3c885e00-3bc8-11eb-9d38-40e0c01986c7.png">

**Comment by georgebettley** [comment]
I'm using Mac OS 11 however the above issue was happening when i was running Zulu 11 (10.13 or later).

When I tried loading with MacOS 11 or later version of Zulu, i get this error:

<img width="859" alt="Screenshot 2020-12-14 at 11 33 53" src="https://user-images.githubusercontent.com/43244833/102077175-cb7fbb00-3e00-11eb-892a-5a03ff4b1a70.png">

**Comment by leftpropeller** [comment]
That's progress!  How did you get past the blank loader screen problem?

**Comment by gabrielmocelin** [comment]
> That's progress! How did you get past the blank loader screen problem?

https://github.com/forcedotcom/dataloader/issues/217#issuecomment-733944644

**Comment by silvy96** [comment]
I'm having the same issue. Has there been any found solution to this?

**Comment by leftpropeller** [comment]
Not that I’m aware of. Been using workbench.



Steve Berley

Left Propeller Salesforce Consulting

steve@leftpropeller.com<mailto:steve@leftpropeller.com>

510 459 0558<tel:510%20459%200558>

________________________________

**Comment by jaffacakesny** [comment]
I am having the same issue. I cant get the program to even launch.

**Comment by ashitsalesforce** [comment]
If you have M1 running Big Sur, see #237 for a workaround.
