### ISSUE TITLE
Data Loader for Mac M1 

### ISSUE THREAD

**Issue by kristfr009** [forcedotcom/dataloader#237]
Is there a version for Mac M1 machines for Data Loader?

I have tried multiple times to install Data Loader on my Mac M1.  I keep getting the below error message.  I have JDK 11 installed.  I used the dmg file. 

I have posted on Salesforce community:  Data Loader Error

https://trailblazers.salesforce.com/answers?id=9064S000000DRDU

**Comment by ashitsalesforce** [comment]
Hi Kris,

Mac M1 is a new hardware from Apple. While Salesforce updates Data Loader time-to-time to support the latest OS releases, the time frame for doing so depends on support by underlying 3rd party libraries. In this case, the error you are seeing on your console indicates that Eclipse SWT library, needed by Data Loader, is not supported on Mac M1. While I did not find anything on Eclipse SWT support (or lack thereof) of Mac M1, you may want to try running Data Loader in Intel emulation mode using Rosetta 2 to see if emulation mode enables Eclipse SWT to work correctly. Here is Apple's support article on enabling Rosetta 2: https://support.apple.com/en-us/HT211861

Here is the relevant log line from your post indicating that incompatible SWT library is the issue:
```
dlopen(/Users/krisevans/.swt/lib/macosx/aarch64/libswt-cocoa-4936r26.jnilib, 1): no suitable image found.  Did find:
/Users/krisevans/.swt/lib/macosx/aarch64/libswt-cocoa-4936r26.jnilib: mach-o, but wrong architecture
```

The Eclipse SWT [download page](https://download.eclipse.org/eclipse/downloads/drops4/R-4.18-202012021800/#SWT) also shows that the latest SWT for Mac (swt-4.18-cocoa-macosx-x86_64.zip) is available only for x86 architecture, not for M1.

**Comment by kristfr009** [comment]
Thanks that worked!

**Comment by ashitsalesforce** [comment]
That's great to hear! Thanks for confirming that it works.

**Comment by zoker715** [comment]
Can someone give us a step by step on how to make the Data Loader work in M1?

**Comment by ashitsalesforce** [comment]
Hi zoker715,

I don't have a Mac M1 but looking at Apple's [article](https://developer.apple.com/documentation/apple_silicon/about_the_rosetta_translation_environment), I would imagine you need to right-click (2 finger click) on dataloader app icon, select "Get Info", and check the checkbox "Open using Rosetta" before trying to launch Data Loader.

**Comment by kristfr009** [comment]
I will write what i did to make it work tomorrow morning.  Basically I installed Rosetta 2 from a command line and then installed data loader and it worked.

**Comment by zoker715** [comment]
> Hi zoker715,
> 
> I don't have a Mac M1 but looking at Apple's [article](https://developer.apple.com/documentation/apple_silicon/about_the_rosetta_translation_environment), I would imagine you need to right-click (2 finger click) on dataloader app icon, select "Get Info", and check the checkbox "Open using Rosetta" before trying to launch Data Loader.

Thank you for the suggestion. I did try it. The OPEN using ROSETTA check box does not exist on the info page.

**Comment by zoker715** [comment]
> I will write what i did to make it work tomorrow morning. Basically I installed Rosetta 2 from a command line and then installed data loader and it worked.
> […](#)
> On Jan 4, 2021, at 10:14 PM, ashitsalesforce ***@***.***> wrote: ﻿ Hi zoker715, I don't have a Mac M1 but looking at Apple's article, I would imagine you need to right-click (2 finger click) on dataloader app icon, select "Get Info", and check the checkbox "Open using Rosetta" before trying to launch Data Loader. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Thank you very much! 🙏🏻

**Comment by kristfr009** [comment]
Good morning

This is how it worked for me.

1. Opened Terminal and ran this command:  softwareupdate --install-rosetta (found this from https://osxdaily.com/2020/12/04/how-install-rosetta-2-apple-silicon-mac/)
2. Then I installed zulu11.43.55-ca-jdk11.0.9.1-macosx_x64.dmg
3. Then I ran the install.command from the dataloader folder that you download.  

Now when I click on the Dataloader icon on my desktop, it runs a terminal session in the background.  As long as you keep that open Data Loader will work.  

It's a work around for now, but I did test and so far so good.  

Good luck to you.

**Comment by zoker715** [comment]
> Good morning
> 
> This is how it worked for me.
> 
> 1. Opened Terminal and ran this command:  softwareupdate --install-rosetta (found this from https://osxdaily.com/2020/12/04/how-install-rosetta-2-apple-silicon-mac/)
> 2. Then I installed zulu11.43.55-ca-jdk11.0.9.1-macosx_x64.dmg
> 3. Then I ran the install.command from the dataloader folder that you download.
> 
> Now when I click on the Dataloader icon on my desktop, it runs a terminal session in the background. As long as you keep that open Data Loader will work.
> 
> It's a work around for now, but I did test and so far so good.
> 
> Good luck to you.

I followed your direction step by step and it WORKS!

THANK YOU SO MUCH!!!! 🙏🏻🙏🏻🙏🏻🙏🏻🙏🏻🙏🏻

**Comment by ashitsalesforce** [comment]
Hi @zoker715  and @kristfr009 , Eclipse Foundation has [released](https://download.eclipse.org/eclipse/downloads/drops4/R-4.19-202103031800/) an early access of SWT built for Mac ARM (swt-4.19-cocoa-macosx-arm64.zip) using which I have built a data loader zip file. I would appreciate your help in trying it out with your Mac M1 and let me know if it works.

[dataloader_mac_arm64.zip](https://github.com/forcedotcom/dataloader/files/6172623/dataloader_mac_arm64.zip)

**Comment by kristfr009** [comment]
Thanks! I will try this now.

Kris

From: ashitsalesforce ***@***.***>
Date: Friday, March 19, 2021 at 11:18 AM
To: forcedotcom/dataloader ***@***.***>
Cc: kristfr009 ***@***.***>, Mention ***@***.***>
Subject: Re: [forcedotcom/dataloader] Data Loader for Mac M1 (#237)

Hi @zoker715<https://github.com/zoker715> and @kristfr009<https://github.com/kristfr009> , Eclipse Foundation has released<https://download.eclipse.org/eclipse/downloads/drops4/R-4.19-202103031800/> an early access of SWT built for Mac ARM (swt-4.19-cocoa-macosx-arm64.zip) using which I have built a data loader zip file. I would appreciate your help in trying it out with your Mac M1 and let me know if it works.

dataloader_mac_arm64.zip<https://github.com/forcedotcom/dataloader/files/6172623/dataloader_mac_arm64.zip>

**Comment by ashitsalesforce** [comment]
Hi @kristfr009 , did you get a chance to try the M1-specific data loader?

**Comment by kristfr009** [comment]
Hi,

This hasn’t worked for me. Any instructions on this?

Thanks,

kris

From: ashitsalesforce ***@***.***>
Date: Thursday, March 25, 2021 at 11:22 AM
To: forcedotcom/dataloader ***@***.***>
Cc: kristfr009 ***@***.***>, Mention ***@***.***>
Subject: Re: [forcedotcom/dataloader] Data Loader for Mac M1 (#237)

Hi @kristfr009<https://github.com/kristfr009> , did you get a chance to try the M1-specific data loader?

**Comment by ashitsalesforce** [comment]
Thanks @kristfr009. The instructions to install are the same as the instructions to [install dataloader_mac.zip](https://developer.salesforce.com/docs/atlas.en-us.dataLoader.meta/dataLoader/loader_install_mac.htm). Make sure not to use Rosetta 2 ("Open using Rosetta" checkbox should be unchecked). If this is not working then likely M1-native libswt has bugs that we will have to await fix for.

The way to check that data loader uses the correct libswt is to take the following steps:
1.  [Download libswt 4.19 for Mac OSX (64 bit version for ARM64) Early Access](https://download.eclipse.org/eclipse/downloads/drops4/R-4.19-202103031800/download.php?dropFile=swt-4.19-cocoa-macosx-arm64.zip).
2.  Unzip its contents and extract the 2 jnilibs by running the command : `jar xf swt.jar libswt-awt-cocoa-4942r22.jnilib libswt-cocoa-4942r22.jnilib libswt-pi-cocoa-4942r22.jnilib`
3.  Go to data loader installation directory and extract the 2 jnilibs: `jar xf dataloader-51.0.1-uber.jar libswt-awt-cocoa-4942r22.jnilib libswt-cocoa-4942r22.jnilib libswt-pi-cocoa-4942r22.jnilib`
4.  Compare the md5 checksum of the jnilibs extracted in steps 2 and 3 to make sure that the same named jnilibs have the same md5 checksum.

**Comment by kristfr009** [comment]
This worked for me. It is now working.

Thanks!

Kris

From: ashitsalesforce ***@***.***>
Date: Friday, March 26, 2021 at 10:21 AM
To: forcedotcom/dataloader ***@***.***>
Cc: kristfr009 ***@***.***>, Mention ***@***.***>
Subject: Re: [forcedotcom/dataloader] Data Loader for Mac M1 (#237)

Thanks @kristfr009<https://github.com/kristfr009>. The instructions to install are the same as the instructions to install dataloader_mac.zip<https://developer.salesforce.com/docs/atlas.en-us.dataLoader.meta/dataLoader/loader_install_mac.htm>. Make sure not to use Rosetta 2 ("Open using Rosetta" checkbox should be unchecked). If this is not working then likely M1-native libswt has bugs that we will have to await fix for.

The way to check that data loader uses the correct libswt is to take the following steps:

  1.  Download libswt 4.19 for Mac OSX (64 bit version for ARM64) Early Access<https://download.eclipse.org/eclipse/downloads/drops4/R-4.19-202103031800/download.php?dropFile=swt-4.19-cocoa-macosx-arm64.zip>.
  2.  Unzip its contents and extract the 2 jnilibs by running the command : jar xf swt.jar libswt-awt-cocoa-4942r22.jnilib libswt-cocoa-4942r22.jnilib libswt-pi-cocoa-4942r22.jnilib
  3.  Go to data loader installation directory and extract the 2 jnilibs: jar xf dataloader-51.0.1-uber.jar libswt-awt-cocoa-4942r22.jnilib libswt-cocoa-4942r22.jnilib libswt-pi-cocoa-4942r22.jnilib
  4.  Compare the md5 checksum of the jnilibs extracted in steps 2 and 3 to make sure that the same named jnilibs have the same md5 checksum.

**Comment by ashitsalesforce** [comment]
Hi @kristfr009 , that's excellent news! What did you have to do to make it work? Uncheck "Open using Rosetta" checkbox or something else? I ask as I do not have a Mac M1 and it will be super-helpful to know these steps so that we can make the Mac M1 version available more widely.

Thanks.

**Comment by kristfr009** [comment]
Hi,

Basically installed the JDK and then opened the data loader file you sent me and ran the command and it worked for me.

Hope this helps,

Thanks again,

Kris

From: ashitsalesforce ***@***.***>
Date: Tuesday, March 30, 2021 at 11:27 AM
To: forcedotcom/dataloader ***@***.***>
Cc: kristfr009 ***@***.***>, Mention ***@***.***>
Subject: Re: [forcedotcom/dataloader] Data Loader for Mac M1 (#237)

Hi @kristfr009<https://github.com/kristfr009> , that's excellent news! What did you have to do to make it work? Uncheck "Open using Rosetta" checkbox or something else? I ask as I do not have a Mac M1 and it will be super-helpful to know these steps so that we can make the Mac M1 version available more widely.

Thanks.

**Comment by ashitsalesforce** [comment]
It does. Thanks!

**Comment by ashitsalesforce** [comment]
Hi @kristfr009 , it will be good to get the confirmation regarding the details of why you had to reinstall the JDK. Is it because the previously installed JDK (or JRE) on your Mac M1 a Mac x86 version and the newly installed JDK (or JRE) a Mac ARM version?

Thanks.

**Comment by jwmoss** [comment]
This is how I got this working on my M1. The only manual part is downloading SWT from their website, I can't get cURL to download the zip, and I'm too lazy to figure it out (maybe user-agent?).

[download.sh](https://gist.github.com/jwmoss/f5dd584313c32a5da7bd2787f634c62a)

**Comment by Bizness13** [comment]
I struggled with this. Your M1 machine will default use the latest Java version unless you disable it through terminal. I was having the issue where I had installed Rosetta and updated my Java version to run the correct version (in my case Java SE 11.0.12). 

I ran this command in terminal open /Library/Java/JavaVirtualMachines and then deleted the other versions and it was able to open without any problem and I don't even have to keep the terminal window open to keep it running.

**Comment by ashitsalesforce** [comment]
Hi @Bizness13 , you can try the attached data loader. It runs on both ARM and x86 Mac natively. In other words, it runs in all of the following 3 cases:
- Mac ARM: ARM-native JRE
- Mac ARM: x86 JRE in emulation mode using Rosetta 2 emulator
- Mac x86: x86-native JRE

Thanks.
[dataloader_mac.zip](https://github.com/forcedotcom/dataloader/files/7543734/dataloader_mac.zip)

**Comment by Bizness13** [comment]
@ashitsalesforce Thanks, my data loader was already working from the steps I mentioned. But if anyone else has issues in the future I'll direct them to that link.
