### ISSUE TITLE
Can't login through oauth because internet explorer 11 isn't supported

### ISSUE THREAD

**Issue by pnpzac** [forcedotcom/dataloader#242]
Can't login through oauth because internet explorer 11 isn't supported by salesforce but the data loader opens the oath window in internet explorer.

**Comment by ashitsalesforce** [comment]
See [Considerations for Microsoft Internet Explorer](https://help.salesforce.com/articleView?id=sf.getstart_browser_considerations_ie.htm&type=5) regarding what is supported. You can try the workaround suggested in #196 to specify a newer IE version.
