### ISSUE TITLE
Lack of scaling support on Windows 10

### ISSUE THREAD

**Issue by pgumiela** [forcedotcom/dataloader#254]
Data Loader is completely lacking scaling support, so it is very inconvenient to use this application on 4k monitors. For instance, the default recommended scaling on Windows 10 for 32-inch 4k displays is 150%, and it looks as shown in the attachments.

<img src="https://user-images.githubusercontent.com/7087639/111045031-35355280-844c-11eb-835e-0d0497670f08.jpg" width="419" height="333">

<img src="https://user-images.githubusercontent.com/7087639/111045033-3797ac80-844c-11eb-8213-ae22b70624a0.jpg" width="463" height="570">

**Comment by ashitsalesforce** [comment]
Data Loader v51.0.1 uses Eclipse SWT v4.18. Per [Eclipse SWT documentation](https://www.eclipse.org/eclipse/news/4.6/platform.php#swt-autoscale), SWT supports auto-scaling. However, you can specify the scale explicitly by setting an environment variable, GDK_DPI_SCALE and tweaking other auto-scale related properties of SWT as specified in [SWT documentation](https://www.eclipse.org/eclipse/news/4.6/platform.php#swt-autoscale-tweaks).

**Comment by ashitsalesforce** [comment]
Reading more about this (I don't have a high DPI Windows desktop), here are the steps to improve your Data Loader UI display based on an article [here](https://superuser.com/questions/988379/how-do-i-run-java-apps-upscaled-on-a-high-dpi-display) and an article [here](https://www.windowscentral.com/how-improve-app-dpi-scaling-enabling-system-enhanced-feature-windows-10):

    Find java.exe you installed.
    Right click -> Properties
    Go to Compatibility tab
    Check Override high DPI scaling behavior.
    Choose "System (Enhanced)" for Scaling performed by:

**Comment by ashitsalesforce** [comment]
Hi @pgumiela , does that thumbs up mean the suggested approach worked?

**Comment by pgumiela** [comment]
@ashitsalesforce, not yet, but thank you very much for sharing this information. I will check whether it works and get back to you.

**Comment by ashitsalesforce** [comment]
Closing the issue assuming that it is resolved with the suggestions provided. Re-open this one or open a new one if it hasn't.
