### ISSUE TITLE
Upgrade data loader to Bulk API 2.0

### ISSUE THREAD

**Issue by gvpatel** [forcedotcom/dataloader#255]
Hello - Current data loader is using Bulk API 1.0.

Is there any plan to migrate data loader and spring framework to  Bulk API 2.0.

Thank you.

**Comment by krissirk** [comment]
@gvpatel - there is no immediate plan to migrate the client to consume Bulk API 2.0. Our current focus is on addressing high priority security or usability issues with Data Loader and issuing a new release in conjunction with new API versions. We continue to partner with internal teams to look across all data import/export tools and devise a long-term strategy.

**Comment by ashitsalesforce** [comment]
@gvpatel , what is your reason for the request? Is there a limitation of Data Loader with its use of bulk v1 that you would like addressed by switching to bulk v2? Knowing this will help us devise a better long-term strategy.

**Comment by gvpatel** [comment]
Hi @ashitsalesforce and @krissirk,

not really. Data loader is working very well. No issues. The one issue we reported you've fixed it so we're very happy.

i just want to know long term salesforce strategy for bulk load. 

Will data loader be supported going forward? someone told me SFDX is future strategy so just want to check

**Comment by gvpatel** [comment]
Is this the future of SF bulk load?

https://github.com/forcedotcom/SFDX-Data-Move-Utility

**Comment by ashitsalesforce** [comment]
Hi @gvpatel , as @krissirk states, we continue to partner with internal teams to look across all data import/export tools and devise a long-term strategy.

**Comment by ashitsalesforce** [comment]
Hi @gvpatel , the latest version of data loader (v61.1.0) supports Bulk v2.
