### ISSUE TITLE
install.bat can cause `rd /s /q %userprofile%`

### ISSUE THREAD

**Issue by iRomanyshyn** [forcedotcom/dataloader#257]
Hi guys!

It looks like the install.bat script for Windows can cause the removal of the user profile or even any accessible file on C: on some systems. Can someone check? One of my colleagues had his user profile removed after running the install.bat.

**Comment by ashitsalesforce** [comment]
Hi @iRomanyshyn , which version of Data Loader is your colleague using? What value does your colleague specify when install.bat prompts for name of the installation directory? Also, does install.bat ask them whether they want to overwrite a previously installed version of data loader?

install.bat sets a variable INSTALLATION_DIR as  "%USERPROFILE%\%DIR_NAME%\v%DATALOADER_VERSION%"  where %DIR_NAME% is the variable containing name of the directory that user specified at the prompt. If the user did not specify a name, install.bat uses "dataloader" as the default. For example, INSTALLATION_DIR is set to "\Users\foo\dataloader\v51.0.1" for a user foo who is running install.bat for v51.0.1 of data loader.

install.bat then proceeds to check for the existence of %INSTALLATION_DIR%. If found, it prompts the user whether it should delete the directory. If the user types in "Y" or "Yes", install.bat proceeds to run "rd /s /q %INSTALLATION_DIR%". In the example above, it would delete "\Users\foo\dataloader\v51.0.1" and its subdirectories. However, it will not delete "\Users\foo\dataloader" or "\Users\foo", the home directory of the user.

**Comment by ashitsalesforce** [comment]
Closing the issue. Note that the title is incorrect because install.bat does not and can not cause `rd /s /q %userprofile%` because the command executed by install.bat is `rd /s /q %USERPROFILE%%DIR_NAME%\v%DATALOADER_VERSION%` where `DIR_NAME` and `DATALOADER_VERSION` are both non-empty strings. Even if these two were empty strings, the command would be `rd /s /q %USERPROFILE%\v`.
