### ISSUE TITLE
Feature Request: Introduce search bar for Select Data Objects screen

### ISSUE THREAD

**Issue by pgumiela** [forcedotcom/dataloader#261]
As we all know, the Data Loader is currently sorting all the objects via Label Name, which is not always convenient as API Name can start with a different letter, depending on the scenario. So, ideally, it would be best to just have a search bar that allows searching both by Label and API Name. It would save a lot of time, especially when connecting to large organizations with hundreds of objects.

**Comment by ashitsalesforce** [comment]
Hi @pgumiela , just to make sure we understand the request correctly, are you referring to the objects list in "Step 2: Select data objects" dialog when performing Insert, Update, Upsert, Delete, or Export?

**Comment by pgumiela** [comment]
@ashitsalesforce, yes, exactly:
![Data-Loader-Step-2](https://user-images.githubusercontent.com/7087639/115008675-b351a280-9eab-11eb-9dbd-c5567b08db63.jpg)

**Comment by ashitsalesforce** [comment]
Thanks. I have checked in the fix to provide search. It will be available in v52 of Data Loader. Here is a screenshot of the search box:
<img width="668" alt="Screen Shot 2021-04-16 at 8 58 52 AM" src="https://user-images.githubusercontent.com/71143047/115051737-ff8fe900-9e91-11eb-8600-d71bee9ea3c8.png">

**Comment by pgumiela** [comment]
@ashitsalesforce, I've tested this behaviour, and it works fine, but it would be great if the filtering could be triggered without pressing any keys. So whenever you type something, it narrows down the search results immediately.

**Comment by ashitsalesforce** [comment]
Hi Paul, thanks for trying out the search bar and giving us the feedback for improving its usage.
