### ISSUE TITLE
Datloader Timing Out

### ISSUE THREAD

**Issue by nssidhu** [forcedotcom/dataloader#268]
I have a large file  3,241,256 rows and it takes around 2+ hrs , and somewhere down the line i get the DataLoader Login related Error

the error is

Failed to send request to
https://XXXXX/services/Soap/u/51.0

Is there timeout for Login in DataLoader ? do we have to relogin again ?

**Comment by ashitsalesforce** [comment]
Hi nssidhu,

Have you enabled Bulk API for the operation? Also, can you provide log content around the time when this error occurs?

**Comment by nssidhu** [comment]
Yes Bulk API is enabled.

**Comment by ashitsalesforce** [comment]
Hi nssidhu, please file a support case so that support can troubleshoot and help resolve the issue.
