### ISSUE TITLE
[Feature Request] Set UTF-8 Read/Write Encoding TRUE by default in Settings

### ISSUE THREAD

**Issue by pgumiela** [forcedotcom/dataloader#274]
The point of this Feature Request is to set UTF-8 both for Read and Write as TRUE by default. UTF-8 is a global standard anyway, and it's very unlikely that somebody doesn't want to use it.
![2021-06-20_19-36-24](https://user-images.githubusercontent.com/7087639/122683422-4d60fe80-d1ff-11eb-9be6-fc39dcdb4c7d.png)

**Comment by ashitsalesforce** [comment]
Hi pgumiela,

Enabling these settings means reading from or writing to CSV file uses UTF-8 encoding regardless of the default encoding for the desktop OS when writing and the encoding specified in the CSV file when reading (BOM in the CSV file). As such, forcing these to be checked will result in undesirable behavior for clients with an encoding other than UTF-8.

Is there a reason why you had to choose these settings? Did data loader not read your CSV file even though the encoding was specified explicitly in its BOM?

Thanks.

**Comment by pgumiela** [comment]
Hi @ashitsalesforce,

I typically have contact with EU customers and when they are starting to learn the Data Loader, it happens very often that people forget to mark this flag.  Similarly, when they are reinstalling, it's not set by default. So what happens both for export and import is that non-Latin characters are being corrupted.

So, honestly, I don't see a reason why it couldn't be enabled by default, especially for Windows machines because UTF-8 is a gold standard anyway. If somebody is not happy with such a setup, it could be disabled anyway. But I'm pretty sure that the vast majority of non-US users rely on Windows machines, so maybe let's enable this by default only for Windows build?

**Comment by ashitsalesforce** [comment]
Hi @pgumiela , thanks for providing additional details of the issue. It seems that DL is either not correctly picking up the default charset on customers' system or is missing a reasonable default setting. Can you share a sample csv file that reproduces the issue? It will help troubleshoot it.

Thanks.

**Comment by ashitsalesforce** [comment]
Closing the issue assuming it is resolved. Reopen with additional details if needed.

Thanks.
