### ISSUE TITLE
[Feature Request] enable lookup-by-Name

### ISSUE THREAD

**Issue by bgaspic** [forcedotcom/dataloader#279]
Can you please enable lookup-by-Name importing in dataloader, in addition to the already-existing lookup-by-ExternalId?
I mean, if importing `My_SObject__c` which has a `My_SObject__c.My_Parent__c` lookup, that you allow the `.sdl` to specify `MyParentName=My_Parent__r\:Name`. (Enabling this also in the GUI, in addition to .sdl editing, would be a plus)

Yes, it is not possible to enforce uniqueness on Name in SF (as ExternalIds do). Yes, the "standard solution" is to create a "shadow" ExternalId field, not placed in the Layout, whom before-insert&before-update triggers keep aligned to a copy of Name (and which thus also begin prohibiting the duplicating of a Name).

Having said that,
1. people do need lookup-by-name (google the question in its various phrasings, to see how often it pops up)
2. in _practical_ terms, the sObject Names are effectively kept unique whenever it matters for them to be unique (obviously not for "names of people", but yes in myriads of other use cases)
3. not everyone who needs to import a batch of data, has the authority to add datamodel fields and add triggers to the org
4. not everyone who has the authority to add (redundant) fields and associated triggers, _wishes_ to always do so for every sObject that may become the parent-lookup side of an import sometime down the line when they're already on another project
5. Data Import Wizard does allow it
6. Dataloader.io does allow it

Since the #5 and #6 are not universally applicable nor universally available, could you please enable lookup-by-Name in the "regular" dataloader?

**Comment by ashitsalesforce** [comment]
Hi bgaspic,

Thanks for the feature request. Data Loader is currently in maintenance mode - a major feature such as the requested one will be considered and prioritized with other requests when we decide to enhance it.

**Comment by bgaspic** [comment]
Thank you Ashit. Please consider when you go out of maintenance mode.

**Comment by bgaspic** [comment]
Hi @ashitsalesforce, the request is made about the standard `Name` field on custom sObjects.
It's understood that the Contacts and Leads "Name" is a composite, and this one would not be expected.
Also it's understood that the uniqueness of standard `Name` is not guaranteed by the system,
and that where `Name` is non-unique, loads may fail for such rows.
With all of the above caveats, this remains an important feature sought by many.
Thank you

**Comment by ashitsalesforce** [comment]
Hi @bgaspic,

I have configured the following in my test org to recreate the issue:
- ParentCustom - a custom object with the following fields:
    - Name
    - Field1: Text
    
- ChildCustom objects with the following fields:
    - Name
    - Field1: Text
    - parent: Lookup field to ParentCustom object

Next, I inserted following ParentCustom objects using a CSV file:
```
Name,Field1__c
P1, Parent field stuff
P2,
P3, More parent
```

I modified a specific code and upserted the following CSV:
```
Name,ParentCustom:Name,Field1
C1,P1,child one
C2,P1,child two
C3,P3,single child
```
My mapping file (generated through the UI) is:
```
#Mapping values
#Wed Sep 15 16:16:13 PDT 2021
Field1=field1__c
ParentCustom\:Name=parent__r\:Name
Name=Name
```
Does this match the fix you are looking for? You can also try out my code changes using the data loader zip files (based on API version 52) to see if it works for you.
[dataloader_win.zip](https://github.com/forcedotcom/dataloader/files/7173847/dataloader_win.zip)
[dataloader_mac.zip](https://github.com/forcedotcom/dataloader/files/7173848/dataloader_mac.zip)

**Comment by bgaspic** [comment]
Thank you @ashitsalesforce . I will test it as soon as I get the chance (tomorrow, probably), but the possibility to have `ParentCustom\:Name=parent__r\:Name` is exactly what we were looking for, and the ParentCustom/ChildCustom objects above correctly summarize the desired upsert scenario.

**Comment by ashitsalesforce** [comment]
Hi @bgaspic , that's good to hear. I will hold off checking the fix into the code base till you confirm that the fix is indeed working for your use-case.

**Comment by bgaspic** [comment]
Hi @ashitsalesforce, I've just created some sample files to test on my org. I confirm that it has all worked out as expected, end-to-end: being able to select My_Custom_Parent__r:Name as the lookup field for that relationship, and assigning the name field from the CSV to it in the mapping stage, and that everything worked as expected both on inserted and on updated records in the ensuing upsert operation. Thank you for implementing this!

**Comment by ashitsalesforce** [comment]
Hi @bgaspic , thanks for confirming that the fix works for you. I will check in the code change and close this issue.

**Comment by ashitsalesforce** [comment]
Checked in the fix, closing issue.
