### ISSUE TITLE
Dates automatically go back one day after the update

### ISSUE THREAD

**Issue by HUMENTH** [forcedotcom/dataloader#280]
When I update the data, the dates automatically go back one day after the update, it only happens with the field with the date, not the date/time field.

> **Device: Desktop
> OS: Windows 10
> Date format: dd/MM/yyyy
> Dataloader ver.: 52.0.0
> Dataloader Time Zone: Asia/Calcutta**
![Dataloader Settings](https://user-images.githubusercontent.com/4609678/124881549-19524f80-dfed-11eb-8977-1ed78fc3a8c6.jpg)

**Comment by ashitsalesforce** [comment]
Hi @HUMENTH , provide a sample CSV containing the dates that you are updating to help troubleshoot and attach a screenshot of the updated record with incorrect date to aid in troubleshooting the issue.

Also, what is the timezone of the user in the Salesforce whose credentials you are using? You can see this information by clicking on "View profile" from the dropdown when you hover on the user icon in the top-right corner of the screen after logging into your Salesforce org using that user's credentials.

Thanks.

**Comment by HUMENTH** [comment]
Hello @ashitsalesforce, 
Please review attached CSV and Screenshots.

I'm using the Salesforce administrator User.

![Salesforce screenshot with wrong dates](https://user-images.githubusercontent.com/4609678/125036280-72cf8280-e0b0-11eb-8b09-5c9e3fd57c76.jpg)
![TimeZone and Locale of the SFDC User](https://user-images.githubusercontent.com/4609678/125036287-74994600-e0b0-11eb-88ed-0d9aea6bb959.jpg)

[CSV](https://drive.google.com/open?id=1HDjjlwit5P2Yf-V77lpSpJ-RNvR7IJDO&authuser=CRM%40respoproducts.com&usp=drive_fs)

**Comment by ashitsalesforce** [comment]
Fix checked in. It will be available in v53.
