### ISSUE TITLE
Change to ProcessRunner in v52.0.0 locks out non-X11 servers

### ISSUE THREAD

**Issue by devildog820** [forcedotcom/dataloader#281]
Hi,

The change to rename main() in ProcessRunner.java and only be able to run main() in DataLoaderRunner.java for v52.0.0 means that X11 is now required to run the Data Loader CLI in Linux.

I understand Linux isn't officially supported, but I'm asking just in case. We have a need to have RHEL servers pump data into Salesforce, but we are unable to put X11 of any kind on there. Can a switch or argument be added to just run without initializing the graphics layer?

**Comment by ashitsalesforce** [comment]
Hi,

I am not sure how removal of main() method from ProcessRunner.java is forcing X11 client libraries loading. That said, I am assuming that you are cloning the git repo and adding a profile in pom.xml to be able to build on Linux. If so, add the following lines in ProcessRunner.java:

    public static void main(String[] args) {
        Controller.setConfigDir(args);
        runBatchMode(args);
    }

to be able to avoid invoking main() in DataLoaderRunner.java. If that works, I will consider reintroducing it in ProcessRunner.java.

**Comment by ashitsalesforce** [comment]
If you don't want to modify ProcessRunner.java, you may want to create your own java class with main method containing the code:
public static void main(String[] args) {
    Controller.setConfigDir(args);
    ProcessRunner.runBatchMode(args);
}

**Comment by devildog820** [comment]
User error, of course. I had a typo in my process.sh and the run.mode=batch had an extra character, causing it to fire the GUI.

Thanks for your help and patience!

**Comment by ashitsalesforce** [comment]
Thanks for the update. Good to know that you don't need to change the code. If it makes sense, you may want to issue a PR for your process.sh script that I will reject but the code will be available for other linux-based users to discover and use.

Thanks.
