### ISSUE TITLE
Password Encryption strips off characters and invalidates login

### ISSUE THREAD

**Issue by amorek** [forcedotcom/dataloader#290]
I've spent half of the day figuring out why CLI returns `Error while calling web service operation: login, error was: com.sforce.soap.partner.fault.LoginFault: null` and it turned out that encryption process invalidates password if it contains special characters.

Reproduction steps:
```
`> .\encrypt.bat -e password*^$123 ..\pk.key

The output string of encryption is:
2f238958d6751594968a7370af62b60824eeee88ce39e38df53ba5eacce4f262

> .\encrypt.bat -d 2f238958d6751594968a7370af62b60824eeee88ce39e38df53ba5eacce4f262 ..\pk.key            
The output string of decryption is:
password*



> .\encrypt.bat -e password*^123 ..\pk.key
The output string of encryption is:
f22e9cacec6195c56c9d58e27b0f25379c048f09653d5c71c61ae5233619e3ee

> .\encrypt.bat -d f22e9cacec6195c56c9d58e27b0f25379c048f09653d5c71c61ae5233619e3ee ..\pk.key
The output string of decryption is:
password*123
```

As you can see, it's not the same password. Login History for my user says:
Other Apex API | Invalid Password | N/A | test.salesforce.com

-----------
Dataloader v52.0
```
> java --version
openjdk 16.0.1 2021-04-20
OpenJDK Runtime Environment Zulu16.30+15-CA (build 16.0.1+9)
OpenJDK 64-Bit Server VM Zulu16.30+15-CA (build 16.0.1+9, mixed mode, sharing)

OS Name:                   Microsoft Windows 10 Home
OS Version:                10.0.19042 N/A Build 19042
```

**Comment by ashitsalesforce** [comment]
Hi @amorek , try encapsulating the password argument in double-quotes such as
`> .\encrypt.bat -e "password*^$123" ..\pk.key`

if you are trying to indeed escape the $ character in the password and your password does not contain ^ character, try the following:
`> .\encrypt.bat -e "password*$123" ..\pk.key`

**Comment by amorek** [comment]
Hi @ashitsalesforce 
I experimented a bit more with this and the correct answer is to use single quotes instead:
`> .\encrypt.bat -e 'password*^$123' ..\pk.key`

Then it works as expected
