### ISSUE TITLE
dataloade v52 mac - no uninstall steps anywhere!! please HELP

### ISSUE THREAD

**Issue by elizdlt202** [forcedotcom/dataloader#298]
Hi, unfortunately shortly after downloading data loader successfully on my mac....the organization associated ended up not using this route. 
Can you please provide steps to uninstall and completely remove dataloader v52 from my mac?

**Comment by ashitsalesforce** [comment]
Hi @elizdlt202 , here is the outline of the steps to uninstall on mac:
- Navigate to the parent folder where v52 of data loader is installed. Default is /Users/<username>/dataloader/
- Move the folder v52.0.0 to trash.
- Check for and delete the link in the Desktop folder and link in the App folder if it exists.
