### ISSUE TITLE
Loading of log-conf.xml

### ISSUE THREAD

**Issue by DeveloperWonk** [forcedotcom/dataloader#30]
Using the CLI I set the CONF directory to c:\load\conf.
I run from c:\load
The \conf directory has log-conf.xml.  The logging configuration is not recognized and I receive the console output '[main] controller.Controller initLog (Controller.java:389) - Using built-in logging configuration, no log-conf.xml'

Controller.java is using the user.dir property to construct the File at line 380.  This returns "c:\load"

Shouldn't the log-conf.xml be loaded from the directory returned from the getConfigDir() on line 400.

**Comment by ashitsalesforce** [comment]
closing out old threads that are likely not relevant anymore.
