### ISSUE TITLE
[Feature Request] Hide Terminal Window by default

### ISSUE THREAD

**Issue by pgumiela** [forcedotcom/dataloader#304]
The point of this feature is to introduce a new option in Settings called `Hide Terminal Window` and set it `TRUE` by default. The rationale behind this is that many business users are not familiar with the command line, and it's just confusing. Power users can simply turn it on (in case they need it), but most people just don't. And that was the case in the past - there was no terminal window at all.

![DL-52-Hide-Terminal-Window](https://user-images.githubusercontent.com/7087639/131252860-55e47c2c-ff52-4d7f-919f-d1331a50d60a.png)

**Comment by ashitsalesforce** [comment]
Hi @pgumiela , I have checked in the fix for both Windows and Mac platforms. The fix will be available in 53.0.0.

As you can see in the changelist, the fix on the Windows platform is to launch the terminal in minimized mode.

**Comment by ashitsalesforce** [comment]
The fix is available with [v53.0.0](https://github.com/forcedotcom/dataloader/releases/tag/v53.0.0)
