### ISSUE TITLE
Invalid Api version specified on URL

### ISSUE THREAD

**Issue by matinlotfali** [forcedotcom/dataloader#324]
I am getting the error "Invalid Api version specified on URL" during login. Looking online I noticed that I should match my Api version with the dataloader version and I want to build the latest version (not the already compiled one).

I looked up Apex Classes but there was no "Dataloader" item.
Can someone help me find where I should change my Api version? Shouldn't it be part of the README.md?

**Comment by ashitsalesforce** [comment]
Hi @matinlotfali , you need to change the following line in pom.xml to specify the WSC version:
```
...
    <force.wsc.version>53.0.0</force.wsc.version>
...
```

**Comment by matinlotfali** [comment]
Don't you want to include this information in README.md ? Do you want me to create a pull request?

**Comment by ashitsalesforce** [comment]
Hi @matinlotfali , sure, create a PR. We will review and pick it up as-is or revise and check-in the change.
