### ISSUE TITLE
Hardware 2FA Breaks OAuth Login

### ISSUE THREAD

**Issue by rmoodySIS** [forcedotcom/dataloader#328]
![dataloader_key_issue](https://user-images.githubusercontent.com/36513627/133692098-dfd59888-49f0-46b7-a591-5e425d246dbb.png)

If the user is using hardware 2FA (e.g. Yubikey), they will no longer be able to log in via OAuth. The window prompting the user to insert the key and touch the button displays; however, it immediately fails. When logging into Salesforce directly, the the OS normally displays another window prompting the user to touch the button. It also appears to affect both Windows and MacOS. 

This does not appear to be an issue with authenticator apps.

**Comment by ashitsalesforce** [comment]
Hi @rmoodySIS , Data Loader uses Eclipse SWT Browser widget, which supports some but not all capabilities of a native browser such as Chrome, Firefox, or Edge, resulting in this issue. Here is a potential fix that lets the users login through the browser on their desktop that supports 2FA. Try it and let us know if it works. If it does, we will consider it in a future release.

Enabling this potential fix requires the following steps:

- Create a [Connected App in Salesforce](https://help.salesforce.com/s/articleView?id=sf.connected_app_create.htm&type=5) for your Salesforce org's OAuth authentication Data Loader.
- Get the client id of your Connected App by going to `Setup >> App Manager >>` clicking on the Connected App you created in the previous step.
- Install Data Loader containing the potential fix. [dataloader_mac.zip](https://github.com/forcedotcom/dataloader/files/7272045/dataloader_mac.zip), [dataloader_win.zip](https://github.com/forcedotcom/dataloader/files/7272046/dataloader_win.zip)
- Go to `"Settings"` dialog, check the checkbox labeled `"Enable OAuth login from browser"`, and specify the client id of your connected app in the textbox labeled `"Client ID in Production"`. <img width="951" alt="advanced settings screenshot" src="https://user-images.githubusercontent.com/71143047/135729208-c2060a2d-a5d8-4fda-a172-36d53e357eb4.png">
- Go through the OAuth login flow. A clickable link will be shown. <img width="645" alt="login from browser screenshot" src="https://user-images.githubusercontent.com/71143047/135729212-cf30f17b-302f-4720-8e1d-af45dc89e38d.png">.
Clicking on it will take you through 2FA login sequence on your browser, which enables you to use a hardware key for 2FA.
