### ISSUE TITLE
Cannot install Data Loader

### ISSUE THREAD

**Issue by jch00oo** [forcedotcom/dataloader#330]
I have installed Zulu and downloaded the Data Loader file. When I run the Install.bat file, after answering if I want to create shortcut etc, it just says "Data Loader installing is quitting" and nothing is installed. How should I resolve this? I've checked that Zulu has been installed correctly and is in the path, but I am not quite sure.

**Comment by ashitsalesforce** [comment]
Hi @jch00oo , please provide following:
- What version of Data Loader did you try with? If v53.0.0, try with v52.0.0 and see if you see the same issue.
- What folder did you specify for installation?
- Are you using Windows command shell to run install.bat or launching it from the extraction folder?
