### ISSUE TITLE
Mac OS 11.6 / zulu-11 - Still can't see buttons

### ISSUE THREAD

**Issue by jove4015** [forcedotcom/dataloader#333]
Running versions 50.0, 52.0, and 53.0 on Mac OS Big Sur 11.6 with zulu-11.jdk (only JDK installed on machine), still can't get Dataloader to display properly.

![image](https://user-images.githubusercontent.com/228216/137185972-a6cfad8f-22f0-4a0c-b618-13e5d5eea424.png)

Personally I know what all the buttons are but it's definitely difficult to train other people to use this when it looks like this. 

I've tried every fix I can find out there and no matter what, all the buttons in the app show up blank except for the icon.

**Comment by ashitsalesforce** [comment]
Perhaps you are encountering the same issue as issue #213 . If so, try the solution posted there.
