### ISSUE TITLE
GMT should be set as the default Time Zone in Data Loader Settings

### ISSUE THREAD

**Issue by pgumiela** [forcedotcom/dataloader#334]
GMT Time Zone should be set as the Default value in Settings:
![2021-10-14_15-48-22](https://user-images.githubusercontent.com/7087639/137330566-9396b84a-4875-4cad-84ce-bbba81e6ba02.png)
The rationale behind this is that the timestamps are always in GMT in Salesforce. And when somebody is not aware of this setting, it can produce unwanted results like inserting/updating date fields with different values that were intended because Los Angeles is the default Time Zone.

**Comment by pgumiela** [comment]
Hi @ashitsalesforce,

I think it doesn't default to the desktop timezone because I'm based in the EU, and my local timezone is GMT+2. Exactly the same timezone is set on the User level in Salesforce. So whenever I'm installing Data Loader from scratch, it defaults to Los Angeles. And LA has GMT-7, so it's nowhere close :).

I haven't checked how the Data Loader detects the timezone, but I think it should be a picklist field anyway. Because now it's just a text, and there's no validation for the user input. So it would be just better to reflect the timezone picklist from Salesforce.

This is why I think that setting up GMT by default is reasonable. And if somebody prefers to detect the timezone automatically, it could be a separate checkbox/button, so people can intentionally verify whether detection is correct. I was getting feedback from my coworkers that it was defaulting for them to Los Angeles as well. And because they were preparing .CSV files with GMT timezone, it could lead to unwanted results.

So maybe let's start with the change from text to picklist field, and then let's analyze what else we could do?

**Comment by ashitsalesforce** [comment]
Hi @pgumiela , 

The root-cause for seeing Los Angeles pre-filled is because config.properties file contains the following entry when data loader is installed:

`sfdc.timezone=America/Los_Angeles
`

The workaround is to exit data loader, delete that entry, and restart data loader. Data Loader will now show your desktop's timezone.

We will fix this for sure in the next version of data loader and will look closer into a picklist too.
