### ISSUE TITLE
Data loader v53.0.0 throws INVALID_FIELD when trying to update Date field when Bulk API is enabled

### ISSUE THREAD

**Issue by ashitsalesforce** [forcedotcom/dataloader#338]
Data Loader v53.0.0 works fine to insert, upsert, or update fields of type "Date" unless the 'Use Bulk API' setting is checked. If checked, data loader v53.0.0 shows an error in the results file similar to

`INVALID_FIELD:Failed to deserialize field at col 1. Due to, 'Sat Oct 02 17:00:00 PDT 2021' is not a valid value for the type xsd:date`

**Comment by ashitsalesforce** [comment]
The issue was introduced during the fix for issue #280 . The fix for the issue is included in the zip files below.
[dataloader_mac.zip](https://github.com/forcedotcom/dataloader/files/7447040/dataloader_mac.zip)
[dataloader_win.zip](https://github.com/forcedotcom/dataloader/files/7447041/dataloader_win.zip)

**Comment by tgilde** [comment]
Hi @ashitsalesforce 
Thanks for providing the fixed version of Data Loader.
I downloaded the Mac version, but cannot get it to open, unfortunately. The app icon shortly shows up in the dock, then disappears again right away.
Is there anything that needs to be done in addition to downloading and unpacking the ZIP file?

**Comment by ashitsalesforce** [comment]
Hi @tgilde , which Mac do you run it on? An Intel x86 processor-based Mac or an ARM processor-based Mac (M1 or M2)? If it is ARM processor based, it is likely that the JRE used to run data loader is a M1-native JRE. In which case you will need to switch to x86 JRE and run it in emulation mode using Rosetta 2. I can provide the instructions on how to do so once you confirm your processor type.

Thanks.

**Comment by ashitsalesforce** [comment]
To further troubleshoot, run data loader from the command line as follows:
- launch the Terminal app
- `cd <installation root folder for data loader v53.0.1>`
- execute the following command in the command line:
`./dataloader.app/Contents/MacOS/dataloader`

capture the output. It will help identify the reason why data loader fails to launch.

**Comment by tgilde** [comment]
Hey @ashitsalesforce 
Thanks for your fast reply. I am indeed using a Macbook with an M1 processor.
So far I haven't experienced any issues when running Data Loader on this machine. I've been using versions 50.0, 52.0 and 53.0 without problems.
As my computer is a business computer, I am not sure whether I would be able (or allowed) to install and use Rosetta.

As for launching 53.0.1 via the terminal: this actually seems to work :) There is a warning on Terminal ("WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance"), but the app shows up properly.

I'll check it out and let you know if it works the way it's intended to.

**Comment by ashitsalesforce** [comment]
Hi @tgilde, good to hear that it is working from the command line. The fact that it is not working when you try to launch it from Finder is likely because the System default JRE is M1-native whereas your shell env is picking up x86 JRE that runs in emulation mode.
