### ISSUE TITLE
Can't export on v29.0

### ISSUE THREAD

**Issue by marioquirino** [forcedotcom/dataloader#37]
Hello Force team.

I've started using Apex Data Loader, the latest available version but it doesn't allow me to finish the export process when I click the "Finish" button.

When I click it simply doesn't do anything.

This happens when I have logs disabled.
If I enable it, it will take me to the dialog where I choose the logs folder and then it allows me to finish the export.

This workaround is fine for me, just thought it would be good to point out this issue for those who don't use the logs feature.

**Comment by ashitsalesforce** [comment]
closing out old threads that are likely not relevant anymore.
