### ISSUE TITLE
Can't Install on Windows 10 Pro

### ISSUE THREAD

**Issue by sirideva** [forcedotcom/dataloader#374]
I am getting install errors on Windows 10 Pro when downloading dataloader_win.zip and running install.bat.

Please see snips. 

![image](https://user-images.githubusercontent.com/35934937/146444807-27250bdb-cecc-4020-91d6-de0ad0959fcf.png)
![image](https://user-images.githubusercontent.com/35934937/146444844-68d3e804-0126-4196-9100-811ec7671c63.png)

**Comment by ashitsalesforce** [comment]
Hi @sirideva , I am unable to reproduce this issue and therefore suggest installing v53.0.1 in another folder. Let us know if that works.

**Comment by HUMENTH** [comment]
@sirideva I think, you are using Microsoft OneDrive and "Important PC folder Backup" enabled on your PC.
If yes, then change some default paths and replace `\Desktop` to `\Onedrive\Desktop` in `install.bat`.
