### ISSUE TITLE
SWT blocking issue in batch mode, when current directory is not installation directory

### ISSUE THREAD

**Issue by Thibibi** [forcedotcom/dataloader#376]
Basic situation:

- DL 53.0.1 is installed in folder `C:\Users\<user>\dataloader\v53.0.1`
- My config folder is `D:\DPM\Shared\YDL\Scripts`

I try to execute batch mode from another location, let's say `D:\`

**D:\\>** `java -cp "C:\Users\<user>\dataloader\v53.0.1\dataloader-53.0.1-uber.jar" com.salesforce.dataloader.process.DataLoaderRunner  salesforce.config.dir=D:\DPM\Shared\YDL\Scripts run.mode=batch process.name=<my process name> dataAccess.name="<path to my csv file>" process.outputSuccess="<path to my success file>" process.outputError="<path to my error file>"`
Results in error message:
`Unable to find SWT jar for Windows 10 : amd64`

Launching from `C:\Users\<user>\dataloader\v53.0.1`, **the SAME command works fine**.

I have tried adding `classpath`, `java.library.path` to make sure `C:\Users\<user>\dataloader\v53.0.1\swtwin32_x86_64\swtwin32_x86_64-4.21.jar` is visible, but nothing can make it work from somewhere else than the DL install directory.

What is strange to me is why do we need SWT for a console mode?

**Comment by ashitsalesforce** [comment]
Hi @Thibibi , this is an issue. Here is a workaround while we figure out how to address it:

Create a symlink from the folder you are executing the command from (D: in your case) to <Data Loader v53.0.1 installation folder>\swtwin32_x86_64. 

For example, I did the following from my home folder:
`mklink /d swtwin32_x86_64 dataloader\v53.0.1\swtwin32_x86_64` and successfully ran process.bat from my home folder.

**Comment by jeischens** [comment]
@ashitsalesforce I'm also encountering this issue. I've attempted to execute the command from within the install directory and have added the relevant SWT jar for my architecture (win x86) to the classpath, but am still encountering the same error that @Thibibi is reporting. I'm unable to use the symlink workaround (for a number of reasons).

Are you actively working on a fix so that the SWT jar isn't required in console mode so that I can upgrade to 53.0.1? Do you have a timeline for when a fix will be available?

**Comment by ashitsalesforce** [comment]
Hi @jeischens , did you try the workaround I posted above?

We are actively working on a fix but do not have a timeline on it.

**Comment by jeischens** [comment]
@ashitsalesforce I'm unable to use the symlink workaround - so the only way I'll be able to update to version 53.0.1 (and thus Log4j 2.16.0) is for this issue to be fixed. I also attempted to execute the script from the install directory but am still encountering the same error. So I haven't been able to force SWT to be pulled in batch mode.

**Comment by ashishraj09** [comment]
With the workaround mentioned, I ran in this error while running it in batch mode.
Any idea what is the issue ?

vm_info: OpenJDK 64-Bit Server VM (11.0.7+10-LTS) for linux-amd64 JRE (11.0.7+10-LTS), built on Apr 14 2020 21:38:20 by "mockbuild" with gcc 4.8.5 20150623 (Red Hat 4.8.5-39)

```
sh-4.2$ java -version
openjdk version "11.0.7" 2020-04-14 LTS
OpenJDK Runtime Environment 18.9 (build 11.0.7+10-LTS)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.7+10-LTS, mixed mode, sharing)
```

```
sh-4.2$ cd /salesforce
sh-4.2$ mkdir /salesforce/swtlinux_amd64
sh-4.2$ cp lib/swtlinux_x86_64-4.21.jar /salesforce/swtlinux_amd64/
sh-4.2$ mv /salesforce/swtlinux_amd64/swtlinux_x86_64-4.21.jar /salesforce/swtlinux_amd64/swtlinux_amd64-4.21.jar
sh-4.2$ java -jar lib/dataloader-53.0.1-uber.jar  run.mode="batch" salesforce.config.dir="conf/config.properties"

[java] #
[java] # A fatal error has been detected by the Java Runtime Environment:
[java] #
[java] #  SIGSEGV (0xb) at pc=0x00007f589bbf4f91, pid=407, tid=431
[java] #
[java] # JRE version: OpenJDK Runtime Environment (11.0.7+10) (build 11.0.7+10-LTS)
[java] # Java VM: OpenJDK 64-Bit Server VM (11.0.7+10-LTS, mixed mode, sharing, tiered, compressed oops, g1 gc, linux-amd64)
[java] # Problematic frame:
[java] # V  [libjvm.so+0x623f91]  ClassLoaderData::holder_phantom() const+0x1
[java] #
[java] # Core dump will be written. Default location: Core dumps may be processed with "/usr/libexec/abrt-hook-ccpp %s %c %p %u %g %t e %P %I %h" (or dumping to /salesforce/core.407)
[java] #
[java] # An error report file with more information is saved as:
[java] # /salesforce/hs_err_pid407.log
[java] #
[java] # Compiler replay data is saved as:
[java] # /salesforce/replay_pid407.log
[java] #
[java] # If you would like to submit a bug report, please visit:
[java] #   http://bugreport.java.com/bugreport/crash.jsp
[java] #
```

**Comment by ashitsalesforce** [comment]
A fix that avoids the need to load SWT in batch mode is checked in.

**Comment by Thibibi** [comment]
> mklink /d swtwin32_x86_64 dataloader\v53.0.1\swtwin32_x86_64

The symbolic link worked for me. I might use this trick until there is an official release with the fix, do you know when is it planned @ashitsalesforce ?
