### ISSUE TITLE
Possibility to escape @ character in sqlString property (daodatabaseSqlConfig)

### ISSUE THREAD

**Issue by dedeisep** [forcedotcom/dataloader#38]
in mySql the @ character can be used to set dynamic variables, but the @ characters present in the sqlString are always parsed to some config variable.
for exemple, this query cannot be executed
 SELECT (@a:=20) as variable FROM table_name;

I think the problem resides in the replaceSqlParams of com.salesforce.dataloader.dao.database.databaseContext replaceSqlParams function:

**Comment by jimilinuxguy** [comment]
@dedeisep Did you ever find  a solution?

**Comment by ashitsalesforce** [comment]
closing out old threads that are likely not relevant anymore.
