### ISSUE TITLE
Data loader v53.0.0 on Windows : Works interactively, but not using CLI

### ISSUE THREAD

**Issue by mauricecote** [forcedotcom/dataloader#382]
Using the sandbox, with a custom domain works only in interactive fashion.  While using the CLI I do not even reach the backend (I've confirmed nothing is added in my login history)

Here's the error I get

2021-12-20 09:04:58,442 ERROR [csvAccountExtract] client.PartnerClient runOperation (PartnerClient.java:359) - Error while calling web service operation: login, error was: Failed to send request to https://XXXXXX.lightning.force.com/services/Soap/u/53.0

**Comment by ashitsalesforce** [comment]
Hi @mauricecote , to make sure, have you followed the steps described [here](https://developer.salesforce.com/docs/atlas.en-us.dataLoader.meta/dataLoader/loader_batchmode_intro.htm)?

Specifically, make sure that your process-conf.xml has valid entries for sfdc.endpoint, sfdc.username, sfdc.password, and process.encryptionKeyFile.

**Comment by mauricecote** [comment]
I did follow the steps to create a key, encrypt, and so on.  Since the URL is correct in the logs, I would imagine that the settings are read successfully from the process-conf.xml file.

A wrong password would appear in my login history, I simply to not reach the backend

**Comment by ashitsalesforce** [comment]
Hi @mauricecote , in that case, just to be sure, you have set the value for sfdc.endpoint to be "https://XXXXXX.lightning.force.com", right? Also, is there a proxy service in your network? If so, you need to also configure sfdc.proxyHost, sfdc.proxyPassword, sfdc.proxyPort, and sfdc.proxyUsername.

**Comment by mauricecote** [comment]
yes for 
  key="sfdc.endpoint"
  key="sfdc.username"
  key="sfdc.password"
  key="process.encryptionKeyFile"

no proxy is involved, no vpn, I can ping the host.   Calling the endpoint with cUrl even tells me that it expects a POST, so I see no explanation why I cannot reach it when launched by the CLI.

The error in the log does contain my valid endpoint

**Comment by ashitsalesforce** [comment]
Hi @mauricecote , I suggest filing a case with Salesforce Support team so that we can troubleshoot this issue further.

**Comment by PrafulGuptaDarta** [comment]
@ashitsalesforce same, I'm also encountering the same issue after upgrading to a recent version, not able to use it via CLI commands but able to log in and do DML via data loader **UI**. Any plan fix or known issue?

**Comment by ashitsalesforce** [comment]
Hi @PrafulGuptaDarta , please provide the log content to further troubleshoot.

**Comment by ashitsalesforce** [comment]
A few troubleshooting steps are provided [here](https://help.salesforce.com/s/articleView?id=000324395&type=1).
