### ISSUE TITLE
Error: "Encountered html content when looking for http //schemas.xmlsoap.org/soap/envelope/ envelope"

### ISSUE THREAD

**Issue by nganesha** [forcedotcom/dataloader#384]
Hi,

Getting the above error when trying to authenticate using dataloader ver. 53.0.2. This is happening across prod and sandbox env. 

Thanks,
Navin

**Comment by ashitsalesforce** [comment]
Hi @nganesha , here is a [discussion](https://trailhead.salesforce.com/trailblazer-community/feed/0D54S00000A7tXESAZ) on this issue that you can look into. File a support case if that does not resolve your issue.
