### ISSUE TITLE
template xml files read old spring dtds.

### ISSUE THREAD

**Issue by megascus** [forcedotcom/dataloader#39]
Template xml header is using old spring 2.0 dtds.
You shoud use spring 3.1 xsds.

<!DOCTYPE beans PUBLIC "-//SPRING//DTD BEAN//EN" "http://www.springframework.org/dtd/spring-beans.dtd">
↓
<?xml version="1.0" encoding="UTF-8"?> 
<beans xmlns="http://www.springframework.org/schema/beans" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:p="http://www.springframework.org/schema/p" 
xmlns:util="http://www.springframework.org/schema/util" 
xsi:schemaLocation=" 
http://www.springframework.org/schema/beans
http://www.springframework.org/schema/beans/spring-beans-3.1.xsd
http://www.springframework.org/schema/util
http://www.springframework.org/schema/util/spring-util-3.1.xsd">

**Comment by jon-freed** [comment]
Agreed, especially because the XSDs permit parent relationships.

**Comment by ashitsalesforce** [comment]
closing out old threads that are likely not relevant anymore.
