### ISSUE TITLE
OAuth should be opened in the Browser

### ISSUE THREAD

**Issue by MaxG-Enpal** [forcedotcom/dataloader#396]
After pressing login with OAuth the login window should be opened in the default web browser for Security reasons and for making use of the password manager.

**Comment by ashitsalesforce** [comment]
Hi @MaxG-Enpal , we can launch a browser to do OAuth login but transferring the session info securely from browser to data loader after successful login is a challenge.

Fortunately, a solution exists if you want to login through the default browser. See issue #328 for the details.

**Comment by MaxG-Enpal** [comment]
> Hi @MaxG-Enpal , we can launch a browser to do OAuth login but transferring the session info securely from browser to data loader after successful login is a challenge.
> 
> Fortunately, a solution exists if you want to login through the default browser. See issue #328 for the details.

Great thank you for your quick reply!
Last question:
Is it possible to set a launch argument with the setting enabled by default?
This would be really great!

**Comment by ashitsalesforce** [comment]
Hi @MaxG-Enpal , you can set this property (_sfdc.oauth.loginfrombrowser=true_) in config.properties file. You will also need to set _sfdc.oauth.Production.bulk.clientid_ and _sfdc.oauth.Production.partner.clientid_ properties using your Connected App's client id in the config.properties file.

**Comment by MaxG-Enpal** [comment]
> Hi @MaxG-Enpal , you can set this property (_sfdc.oauth.loginfrombrowser=true_) in config.properties file. You will also need to set _sfdc.oauth.Production.bulk.clientid_ and _sfdc.oauth.Production.partner.clientid_ properties using your Connected App's client id in the config.properties file.

Hey,

where can I get the bulk.clientid and partner.clientid?

**Comment by ashitsalesforce** [comment]
Hi @MaxG-Enpal , 

Ignore my comment about setting _sfdc.oauth.Production.bulk.clientid_ and _sfdc.oauth.Production.partner.clientid_ properties in config.properties.

Here are the steps to follow:
-Get the client id of your Connected App by going to `Setup >> App Manager >>`, selecting `View` from the dropdown menu (down arrow) in the rightmost column of the Connected App. Next, launch data loader, go to `"Settings"` dialog before logging in, check the checkbox labeled `"Enable OAuth login from browser"`, and specify the client id of your connected app in the textbox labeled `"Client ID in Production"`. <img width="951" alt="advanced settings screenshot" src="https://user-images.githubusercontent.com/71143047/135729208-c2060a2d-a5d8-4fda-a172-36d53e357eb4.png">
- Go through the OAuth login flow. A clickable link will be shown. <img width="645" alt="login from browser screenshot" src="https://user-images.githubusercontent.com/71143047/135729212-cf30f17b-302f-4720-8e1d-af45dc89e38d.png">.
Clicking on it will take you through login sequence on your browser.

**Comment by MaxG-Enpal** [comment]
> closing assuming that provided steps have resolved the issue.

Hey @ashitsalesforce,

in the provided settings, there is no button view.
I could send you later a screenshot if my colleague gets in the office.

**Comment by ashitsalesforce** [comment]
Hi @MaxG-Enpal , there is no button. Do you see a checkbox "Enable OAuth login from browser" in Settings dialog? Have you checked it and specified the connect app client id in "Client ID in Production" text field below the checkbox?
