### ISSUE TITLE
Only Works with Java 11; Using Zulu didn't work.

### ISSUE THREAD

**Issue by joanjackson** [forcedotcom/dataloader#403]
I was using Java JDK 8 to do development in VS Code.  Dataloader 53.0.3 wouldn't work with that even though I also have Zulu 15 installed.  I had to update to JDK 11 to get this new version of dataloader to work, but now that I have done that, my VS Code is broken and cannot work with this newest version of Java.  Now I have to go through a big rigamarole to repoint my VS Code to some open source JDK.  Just a warning to developers who may be using both VS Code and also need this newest version of the dataloader.  Be prepared.

**Comment by ashitsalesforce** [comment]
Hi @joanjackson , data loader requires a JRE version 11 or later. It could be an open source JRE such as Zulu or proprietary such as Oracle. Also, you can use the latest JRE version 17.

**Comment by joanjackson** [comment]
Thank you, I understand.  I updated to 11 to get the dataloader to work, and it now works, but doing that broke my VS Code development tool.  That is the only point I'm trying to make.  I am now trying to reset my VS Code to point to Zulu 11 but the VS Code instructions on how to do that are not working.

________________________________

**Comment by ashitsalesforce** [comment]
Hi @joanjackson , if you want to use a different JRE for VS than that for Data Loader, set DATALOADER_JAVA_HOME environment variable to JRE 11 or later and JAVA_HOME environment variable to the JDK that you want for VS.

**Comment by joanjackson** [comment]
Okay good to know.  Thanks.
