### ISSUE TITLE
Timezone INFO Messages

### ISSUE THREAD

**Issue by devildog820** [forcedotcom/dataloader#408]
This isn't really an issue, I don't think, but I have a question about the Timezone log output in v54.0.

I'm sending an update via CLI, it's working fine, but for every single record I get something like:

`<timestamp> INFO [updateContact] util.DateOnlyCalendar setTimeInMillis (DateOnlyCalendar.java:62) - Timezone is Pacific Standard Time`

I know I can suppress a specific message, but is there something else I should be aware of with my process?

**Comment by ashitsalesforce** [comment]
Hi @devildog820 , this is a diagnostic message introduced to improve troubleshooting for date-only field in the processed records. Previous versions of data loader had a bug where when a date-only field value was uploaded in timezones that are ahead of GMT, the date was stored one day less than the value provided. For example, if the timezone in Setup is set to JST and value "2010-10-14T00:00:00.000" uploaded, the stored value would be "2010-10-13". The INFO message you see was introduced in the process of fixing this bug and adding the tests to verify the fix.
