### ISSUE TITLE
Can't load default log-conf.xml from configs in v54.0.0

### ISSUE THREAD

**Issue by juanlu-github** [forcedotcom/dataloader#409]
In v54.0.0 you have to include the file log-conf.xml in the conf folder, otherwise DL will not log to the console... even if the log-conf.xml exists in C:\Users\{userName}\dataloader\version\configs !

In other words, '[main] controller.Controller initLog (Controller.java:389) - Using built-in logging configuration, no log-conf.xml' does not appear to be working.

We have been using Data Loader for years in batch mode/cli and we never had to include the log-conf.xml in every single conf folder, but rather did it centralized using the default file in _configs_.

The last version we were using before v54.0.0 was v49.0.0 (and many others before), again, without having to copy the log-conf.xml file all over the place.

**Comment by ashitsalesforce** [comment]
Hi @juanlu-github , you can specify a different location for log-conf.xml by setting LOG4J_CONFIGURATION_FILE environment variable. Make sure to include the full path including the file name in the value.

**Comment by juanlu-github** [comment]
It works! Thanks a lot, @ashitsalesforce . This information should definitely be part of the official Salesforce Data Loader Guide.
