### ISSUE TITLE
Project abandoned?

### ISSUE THREAD

**Issue by ViViDboarder** [forcedotcom/dataloader#41]
It seems like nothing meaningful has been done for some time now in the project. API version numbers have been bumped but no new features have been added nor have any pull requests been merged.

Should the community agree on a common fork to follow instead of the primary project?

**Comment by ViViDboarder** [comment]
A while back I submitted #35 and #36 and haven't heard anything. They are relatively trivial changes, but it's discouraging to put more effort in if even trivial changes aren't being considered for merging.

**Comment by jthurst01** [comment]
Understood.  

We develop/merge based on our release cycles.  We look at these requests along with our other work, and it gets prioritized, and these have not yet been picked up.

I made a comment on #36 and it looks like #35 should be ok for us to merge.  I will make sure it is on our task list for the next few weeks.

Thanks again

**Comment by ViViDboarder** [comment]
Thanks @jthurst01. That lends some more clarity.

**Comment by xbiansf** [comment]
Thanks for closing this old request.   The project is mainly in maintence/bug mode. Most of the changes are bug fixes from customer report.  I will mention this inside the team about how to maintain the pull request in general.
