### ISSUE TITLE
Unable to install/open dataloader in my MacOS

### ISSUE THREAD

**Issue by mrhugoraposo** [forcedotcom/dataloader#419]
I recently downloaded dataloader v54.0.0 and V53.0.3 in my macOS Big Sur. The job install.command was executed without any major issue and I can confirm that the app was correctly installed in my Application folder. However I can't find a way to run the application. The application does not load and no error is displayed in my screen.

**Comment by ashitsalesforce** [comment]
Hi @mrhugoraposo, try to run data loader from the Terminal app (it is in the Utilities sub-directory of Applications directory). You will see the console output. Capture that so that we can troubleshoot the issue further.

**Comment by mrhugoraposo** [comment]
I had to install Zulu OpenJDK in my laptop because the app was not loading with JRE. You can close this issue but maybe it would be worth to investigate why it is not working with Oracle JRE. Thanks

**Comment by ashitsalesforce** [comment]
Hi @mrhugoraposo , good to hear you were able to figure out the root-cause and fix it. Which version of Oracle JRE is installed on your Mac?

**Comment by mrhugoraposo** [comment]
openjdk version "17.0.2" 2022-01-18 LTS
OpenJDK Runtime Environment Zulu17.32+13-CA (build 17.0.2+8-LTS)
OpenJDK 64-Bit Server VM Zulu17.32+13-CA (build 17.0.2+8-LTS, mixed mode, sharing)

**Comment by ashitsalesforce** [comment]
Hi @mrhugoraposo , I meant the version of Oracle JRE on your Mac using which you are unable to run Data Loader.

I downloaded Oracle JDK 17 from [here](https://www.oracle.com/java/technologies/downloads/#jdk17-mac) and verified that Data Loader 53.0.2 is successfully launched with it.
