### ISSUE TITLE
Error Running DataLoader batch

### ISSUE THREAD

**Issue by IVerkhosh** [forcedotcom/dataloader#427]
Hi there,

We recently updated to the DataLoader v53, and I am no longer able execute the process, which was working for the last few years with DL v40. I start getting the error:

Processing Billing file: eo_pge_billing_20211015232606.gz
    1 file(s) moved.
Transforming file D:\Data\PGE\Data_Interfaces\Interface_6d_v2\Prod\eo_pge_billing_20211015232606.gz.txt
Converting to CSV...
Validating file...
ERROR: No input
Moving files to appropriate folders...
1 file(s) moved.
1 file(s) moved.
1 file(s) moved.
Done
1 file(s) moved.
The system cannot find the file specified.
1 file(s) copied.
1 file(s) copied.
Processing Usage records...
Upserting 'Usage'...
Error: Main method not found in class com.salesforce.dataloader.process.ProcessRunner, please define the main method as:
public static void main(String[] args)
or a JavaFX application class must extend javafx.application.Application
Reading Usage upsert results...
setting EFILE=error_UsageUpserts.csv
EFILE is set to D:\Data\PGE\Data_Interfaces\Interface_6d_v2\Prod\error_UsageUpserts.csv
ERROR: Cannot open EFILE for input
ERROR: Cannot open success_UsageUpserts.csv for input
ERROR: No input
ERROR: Cannot open D:\Data\PGE\Data_Interfaces\Interface_6d_v2\Prod\error_UsageUpserts.csv for input
ERROR: No input
Missing operand.
Creating Usage Upsert Results file...
1 file(s) copied.
Inserting Usage upsert Results to Salesforce...
Error: Main method not found in class com.salesforce.dataloader.process.ProcessRunner, please define the main method as:
public static void main(String[] args)
or a JavaFX application class must extend javafx.application.Application
Creating Usage Upsert error attachments file...
Reading SFDC ID of inserted upload result...
ERROR: Cannot open success_eiUploadResults_Upsert.csv for input
Insert exception rows with SFDC ID ...
ERROR: Cannot open D:\Data\PGE\Data_Interfaces\Interface_6d_v2\Prod\error_UsageUpserts.csv for input
The system cannot find the file specified.
D:\Data\PGE\Data_Interfaces\Interface_6d_v2\Prod\UsageException02.csv
D:\Data\PGE\Data_Interfaces\Interface_6d_v2\Prod\UsageException03.csv
1 file(s) copied.
Error: Main method not found in class com.salesforce.dataloader.process.ProcessRunner, please define the main method as:
public static void main(String[] args)
or a JavaFX application class must extend javafx.application.Application
Done
moving D:\Data\PGE\Data_Interfaces\Interface_6d_v2\Prod\success_UsageUpserts.csv to D:\Data\PGE\Data_Interfaces\Interface_6d_v2\Prod\2022_01_24
The system cannot find the file specified.
The system cannot find the file specified.
The system cannot find the file specified.
The system cannot find the file specified.
deleting D:\Data\PGE\Data_Interfaces\Interface_6d_v2\Prod\BillingUpsertSoapTrace.log
Could Not Find D:\Data\PGE\Data_Interfaces\Interface_6d_v2\Prod\BillingUpsertSoapTrace.log
1 file(s) copied.
1 file(s) copied.
Could Not Find D:\Data\PGE\Data_Interfaces\v2\CDWtoEICustomerData\Prod\UsageUpsert_lastRun.properties
1 file(s) copied.
1 file(s) copied.

The system cannot find the file specified.
The system cannot find the file specified.
The system cannot find the file specified.
The system cannot find the file specified.
        1 file(s) moved.
The system cannot find the file specified.
The system cannot find the file specified.
The system cannot find the file specified.
The system cannot find the file specified.
        1 file(s) moved.
        1 file(s) moved.
The system cannot find the file specified.
Could Not Find D:\Data\PGE\Data_Interfaces\v2\CDWtoEICustomerData\Prod\success_attachmentinsert_Upsert.csv
Could Not Find D:\Data\PGE\Data_Interfaces\v2\CDWtoEICustomerData\Prod\error_attachmentinsert_Upsert.csv
Could Not Find D:\Data\PGE\Data_Interfaces\v2\CDWtoEICustomerData\Prod\AttachmentInsert_Upsert_lastRun.properties
Could Not Find D:\Data\PGE\Data_Interfaces\v2\CDWtoEICustomerData\Prod\InvalidAttachmentInsert_Upsert_lastRun.properties
Could Not Find D:\Data\PGE\Data_Interfaces\v2\CDWtoEICustomerData\Prod\ResultsInsert_Upsert_lastRun.properties
Could Not Find D:\Data\PGE\Data_Interfaces\v2\CDWtoEICustomerData\Prod\error_eiUploadResults_Upsert.csv
Could Not Find D:\Data\PGE\Data_Interfaces\v2\CDWtoEICustomerData\Prod\ErrorsInsert_lastRun.properties
Could Not Find D:\Data\PGE\Data_Interfaces\Interface_6d_v2\Prod\ei_sourceFile.csv
Could Not Find D:\Data\PGE\Data_Interfaces\v2\CDWtoEICustomerData\Prod\success_eiUploadResults_Upsert.csv
Could Not Find D:\Data\PGE\Data_Interfaces\v2\CDWtoEICustomerData\Prod\UsageException_lastRun.properties
Could Not Find D:\Data\PGE\Data_Interfaces\v2\CDWtoEICustomerData\Prod\ResultsInsert_UpsertCust_lastRun.properties
Could Not Find D:\Data\PGE\Data_Interfaces\v2\CDWtoEICustomerData\Prod\UsageUpsertCust_lastRun.properties
Could Not Find D:\Data\PGE\Data_Interfaces\v2\CDWtoEICustomerData\Prod\success_eiUploadResults_Upsert.csv
Could Not Find D:\Data\PGE\Data_Interfaces\v2\CDWtoEICustomerData\Prod\SPAUpsertCust_lastRun.properties
Could Not Find D:\Data\PGE\Data_Interfaces\v2\CDWtoEICustomerData\Prod\SAExceptionI_lastRun.properties
Could Not Find D:\Data\PGE\Data_Interfaces\v2\CDWtoEICustomerData\Prod\SiteUpsertCust_lastRun.properties
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ moving temp file
The system cannot find the file specified.
The system cannot find the file specified.
The system cannot find the file specified.
The system cannot find the file specified.
The system cannot find the file specified.
The system cannot find the file specified.
The system cannot find the file specified.
The system cannot find the file specified.
        1 file(s) moved.
The system cannot find the file specified.
The system cannot find the file specified.
The system cannot find the file specified.
Done
Done
D:\Data\PGE\Data_Interfaces\v2\CDWtoEICustomerData\Prod>

**Comment by ashitsalesforce** [comment]
Closing this because the same issue is discussed in the comments section of issue #288
