### ISSUE TITLE
Batch Mode - Status Files Wrong

### ISSUE THREAD

**Issue by rajvis** [forcedotcom/dataloader#428]
When running the jobs in Batch Mode, I have received the status files from Salesforce where the record id for the succeeded records were written randomly, meaning the id mentioned in a given row was indeed the id for another row. Have the same issue with Error file as well.

@ashitsalesforce - any thoughts?

**Comment by ashitsalesforce** [comment]
Hi @rajvis , Provide the following details:
- data loader version
- Bulk API enabled ("Use Bulk API" checkbox checked in Settings dialog)
- Operation you are performing (insert, update, upsert, delete, hard delete)
- A sample input CSV  and its success and error results file that do not contain your personal or business sensitive information. If you can't provide this, file a support case with Salesforce support and work with them.

**Comment by rajvis** [comment]
Hi @ashitsalesforce , please find the requested details below:

- Data Loader Version: 53.0.1
- Attached [dataloader_issue_428.zip](https://github.com/forcedotcom/dataloader/files/7941808/dataloader_issue_428.zip) that contains all relevant configurations. Please note that we are using custom PropertyPlaceholderConfigurer to parameterize various properties, and uses separate resource files to enable readability and for better maintenance.
- Operation: upsert
- Attached the [AccountImportProcess_Input.csv](https://github.com/forcedotcom/dataloader/files/7941809/AccountImportProcess_Input.csv)
[Account_ImportProcess_Error.csv](https://github.com/forcedotcom/dataloader/files/7941817/Account_ImportProcess_Error.csv)
[Account_ImportProcess_Success.csv](https://github.com/forcedotcom/dataloader/files/7941818/Account_ImportProcess_Success.csv) files

**Comment by ashitsalesforce** [comment]
Thanks @rajvis . Can you provide a sample csv (make sure it does not have any personal or business sensitive info) where your record id order in Input.csv is different from that in Success.csv and Error.csv?

Also, what is the typical size of your upsert batches? Large size batches get split into multiple batches by data loader and chunks on the server side (by Bulk API), which may impact the order of results. Finally, try by setting `sfdc.useBulkApi=false` in config.properties. Doing so will result in Data Loader upserting one record at a time using Partner SOAP API. If you have a large number of records to process, your org may run out of API limit in doing so. Work with Salesforce Support to figure out your API limit to do this experiment.

**Comment by ashitsalesforce** [comment]
Hi @rajvis , recommend upgrade to v53.0.3 as it uses log4j 2.17.1, which has fixes for the recent spate of log4j vulnerabilities.

**Comment by rajvis** [comment]
@ashitsalesforce - I will upgrade to 53.0.3. The Batch jobs that we have created is for a data migration activity that is expected to load over 30M records, so it is not realistic for me to move to standard API Permanently. I can try the same to understand if this issue happens in Standard API as well or not.

Finally, I do not follow your ask about the sample csv where Input.csv order is incorrect from that in Success.csv and Error.csv. Perhaps I did not explain my problem correctly. The issue is not that the order of the records are incorrect in the success and the error files. The issue is that the record ids received in the success file is wrong and so is the error received in the error file. Please find [Account_ImportProcess_SalesforceExtract.xlsx](https://github.com/forcedotcom/dataloader/files/7943920/Account_ImportProcess_SalesforceExtract.xlsx) which has the record id and the external id extracted from Salesforce after I upsert them. In the Input.csv file I shared, the first column (SF_ID) and the last column (External_Id__c) are both the same value and are the external id values I use for my upsert operation. 

If you look at the ID I received in Success.csv for SF_ID/ External_Id__c = '0012E00002AhnswQAB', it is '0010R00001OGugTQAT'. However, upsert failed for this row and the record was not created in salesforce. See CreatedDate and LastModifiedDate for that row in Input.csv, and you will see that the CreatedDate is blank and LastModifiedDate is backdated to 2019. Thus, when the record is actually created in Salesforce, LastModifiedDate will be before CreatedDate and that's the error you will find in Error.csv for all records. If I query Salesforce for the id = '0010R00001OGugTQAT', I see that the external id for that record is '0013t00001pPSDEAA4' (see the new attachment Account_ImportProcess_SalesforceExtract.xlsx).

Likewise, if you look at the records in Error.csv, all those records were actually succeeded and you will find the external id in Account_ImportProcess_SalesforceExtract.xlsx with the actual id's that were generated in Salesforce. The issue is not that the Success and Error files are interchanged either as you will see the record with SF_ID/ External_Id__c = '0012E000028VFQ3QAO' in the Input.csv has the ID = '0010R00001OGwIRQA1' in Success.csv, but the actual ID in Salesforce for that external id is '0010R00001OH2f4QAD'. '0010R00001OGwIRQA1' is the ID for the record with SF_ID/ External_Id__c = '0013t00002Fr0PaAAJ' instead.

Hope I did not confuse you and this time I explained it correctly.

**Comment by ashitsalesforce** [comment]
Hi @rajvis , requesting you to work with Salesforce Support because troubleshooting your issue likely will require looking more closely at your org's setup and more involved troubleshooting than what we can provide in this forum.

**Comment by rajvis** [comment]
Will do! Thanks @ashitsalesforce

**Comment by ashitsalesforce** [comment]
Hi @rajvis , CreatedDate and LastModifiedDate are read-only fields ([system fields)](https://developer.salesforce.com/docs/atlas.en-us.api.meta/api/system_fields.htm). Specifying them in the mappings file (mappings\toSalesforce in the provided zip) will result in upsert failure.

**Comment by rajvis** [comment]
@ashitsalesforce - Yes, I am aware of the behavior. As I have mentioned earlier, mine is a data migration scenario and hence it is important that we set the Audit Field values during migration. You may do so by following the steps outlined here: https://help.salesforce.com/s/articleView?id=000334139&type=1

**Comment by ashitsalesforce** [comment]
Hi @rajvis , I tried upsert in CLI with a small batch of 3 records in my org with 'Create Audit Fields' enabled. Here are the details of my test:
config.properties:
```
...
sfdc.useBulkApi=true
...
```

process-conf.xml content:
```
...
    <entry key="sfdc.externalIdField" value="Oracle_Id__c"/>
...
```

Org setup:
- 2 Account objects exist before running data loader: account with Oracle_Id__C = 1 (Name = "upsert1CHANGE_#1") and account with Oracle_Id__C = 2 (Name = "upsert2CHANGE_#1").  

CSV file content:
```
"CREATEDDATE","LASTMODIFIEDDATE","NAME","ORACLE_ID__C"
"","","upsert1CHANGE_#2","1"
"2022-01-07T03:25:07.000Z","2022-01-07T03:25:07.000Z","upsert2CHANGE_#2","2"
"2022-01-07T03:25:07.000Z","2022-01-07T03:25:07.000Z","upsert3","3"
```

success CSV file content (I have removed the actual id of the accounts):
```
"ID","CREATEDDATE","LASTMODIFIEDDATE","NAME","ORACLE_ID__C","STATUS"
"XXXXXXXXXXX","","","upsert1CHANGE_#2","1","Item Updated"
"YYYYYYYYYYY","2022-01-07T03:25:07.000Z","2022-01-07T03:25:07.000Z","upsert3","3","Item Created"
```

error CSV file content:
```
"CREATEDDATE","LASTMODIFIEDDATE","NAME","ORACLE_ID__C","ERROR"
"2022-01-07T03:25:07.000Z","2022-01-07T03:25:07.000Z","upsert2CHANGE_#2","2","INVALID_FIELD_FOR_INSERT_UPDATE:Unable to create/update fields: CreatedDate, LastModifiedDate. Please check the security settings of this field and verify that it is read/write for your profile or permission set.
Error fields: CreatedDate LastModifiedDate "
```

I also verified in my org that org with Oracle_Id__C = 1 did get its Name field value change from "upsert1CHANGE_#1" to "upsert1CHANGE_#2", a new account object with Oracle_Id__C = 3 was created, and no changes made to the account object with Oracle_Id__C = 2 (Name = "upsert2CHANGE_#1") account record.

Do share these findings with Salesforce Support so that they can troubleshoot your issue further. Also, I would suggest the following workaround:
Invoke data loader twice 
- Once with insert operation and audit fields filled.
- Second time with update operation and not only audit fields empty but also a different mapping file that does not contain any audit fields.
