### ISSUE TITLE
[java] Unable to find SWT jar for Windows Server 2019 : amd64

### ISSUE THREAD

**Issue by AppyN** [forcedotcom/dataloader#435]
Receiving this error whenever trying to launch .bat file from windows scheduler. Version Information below:
1) Dataloader: 53.0.2
2) Java Version: java-15-openjdk-15.0.2-1
3) Apache ANT 1.9.16

Please let us know how we can resolve this issue. Build.XML is below, error starts from <java classname>:

<?xml version="1.0" encoding="UTF-8"?>
<project name="Export" default="all">
    <property file="build.properties"/>
    <property environment="env"/>
    <tstamp>
        <format property="todayDate" pattern="MM-dd-yyyy_HH-mm-ss" />
		<format property="todayDate_advantage" pattern="yyyyMMdd_HHmmss" />
        <format property="todayDate_only" pattern="MM-dd-yyyy" />
		<format property="todayDate_yyyyMMdd" pattern="yyyyMMdd" />
    </tstamp>
    
    <tstamp>
        <format property="twoDaysAgo" pattern="yyyy-MM-dd" offset="-2"/>
    </tstamp>

	<macrodef name="Extract_Portfolio">
        <attribute name="PortfolioExportFile"/>
        <attribute name="userName"/>
        <sequential>
            <echo message="Exporting @{object}"/>
            <mkdir dir="exports/${todayDate_only}"/>
            <mkdir dir="logs/${todayDate_only}"/>
            <copy file="config/template-process-conf_Export.xml" tofile="config/process-conf.xml" overwrite="true" failonerror="true"/>
            <replace file="config/process-conf.xml">
              <replacefilter token="_PortfolioExportFile_" value="{fileLocation}"/> 
                <replacefilter token="_userName_" value="@{userName}"/>
            </replace>
            <java classname="com.salesforce.dataloader.process.DataLoaderRunner" classpath="dataloader-53.0.2-uber.jar" failonerror="true">
                <sysproperty key="salesforce.config.dir" value="config"/>
				
                <arg line="process.name=PortfolioExport"/>
            </java>
        </sequential>
    </macrodef>

	
	<target name="PortfolioExport">
			
			<Extract_Portfolio 
				PortfolioExportFile="PortfolioExport${todayDate_yyyyMMdd}"
				userName="${sf.prod.profileName.name}"/>
    </target>

</project>

**Comment by ashitsalesforce** [comment]
Hi @AppyN , you need to specify an argument run.mode and set its value to "batch" when executing in the batch mode. While I am not familiar with Build.XML syntax, it is likely you will need to provide the argument as follows:
```
        <java classname="com.salesforce.dataloader.process.DataLoaderRunner" classpath="dataloader-53.0.2-uber.jar" failonerror="true">
            <sysproperty key="salesforce.config.dir" value="config"/>
			<!-- below must be the same as the key attribute  in the template-process-conf.xml  file and the target below -->
            <arg line="run.mode=batch"/>
            <arg line="process.name=PortfolioExport"/>
        </java>
```
