### ISSUE TITLE
Problem with setting up logs for parallel DL processes.

### ISSUE THREAD

**Issue by RadoslawNad** [forcedotcom/dataloader#438]
I upgraded the Data Loader version to 53.0.3. I want to save the logs to one file and I want to use 'RollingFileAppender' for the log4j2 configuration. However, Data Loader is started by a script, and several DL processes can run simultaneously. And that again causes the error 'ERROR Unable to delete file ABC. The process cannot access the file because it is being used by another process.'. 
Is it possible to use one Logs file and use it when running DL in parallel? 
Is it possible to somehow configure Logs for DL so that there are more log files if DL is run by command-line with the command 'process.bat "file path to process-conf.xml" process name'?
For example, I call 3 processes simultaneously:

process.bat "file path to process-conf.xml" Job1
process.bat "file path to process-conf.xml" Job2
process.bat "file path to process-conf.xml" Job3

Is it possible to set it so that I have 3 separate log files:

Job1.log
Job2.log
Job3.log

or depending on the thread?

**Comment by ashitsalesforce** [comment]
Hi @RadoslawNad, what made you reach the conclusion that the error message has to do with RollingFileAppender? What happens if you replace RollingFileAppender with FileAppender (used in log-conf.xml shipped with Data Loader)? Also, can you give an example name of the file in the error message "ERROR Unable to delete file ABC...".

**Comment by RadoslawNad** [comment]
Hi @ashitsalesforce ,

The first problem with the Log was that I had to set the logs configuration file through environment variables. Otherwise, the log configuration file was not visible to DL after the change.

All the error I get: ERROR Unable to delete file C:\Program Files (x86)\salesforce.com\Data Loader\Logs\sdl.log: java.nio.file.FileSystemException C:\Program Files (x86)\salesforce.com\Data Loader\Logs\sdl.log: The process cannot access the file because it is being used by another process.

Current settings:
`<?xml version="1.0" encoding="UTF-8"?>
<Configuration>
	<Appenders>
		<RollingFile name="fileAppender" fileName="Logs/sdl.log" filePattern="Logs/sdl.log.%i" append="true">
			<PatternLayout pattern="%d %-5p [%t] %C{2} %M (%F:%L) - %m%n"/>
			<Policies>
				<SizeBasedTriggeringPolicy size="100 KB"/>
			</Policies>
			<DefaultRolloverStrategy max="1"/>
		</RollingFile>
		<Console name="STDOUT" target="SYSTEM_OUT">
			<PatternLayout pattern="%d %-5p [%t] %C{2} %M (%F:%L) - %m%n"/>
		</Console>
	</Appenders>
	<Loggers>
		<Logger name="org.apache.log4j.xml" level="warn">
			<AppenderRef ref="fileAppender"/>
			<AppenderRef ref="STDOUT"/>
		</Logger>
		<Root level="info">
			<AppenderRef ref="fileAppender"/>
			<AppenderRef ref="STDOUT"/>
		</Root>
		<Logger name="org.apache" level="warn"/>
	</Loggers>
</Configuration>`

I have not yet tried running Dl in parallel with FileAppender. I will try to do that today and let you know as soon as possible.
And everything works fine when I run only one DL process but this error appears when running in parallel.

**Comment by ashitsalesforce** [comment]
Hi @RadoslawNad , 

Thanks for sharing your config. I was able to reproduce the issue by running the following script:

```
setlocal
start process.bat ../../configs insertAccounts
start process.bat ../../configs insertAccounts
start process.bat ../../configs insertAccounts
```

A workaround is to specify different logging config file for each job where each logging config file specified a different value for fileName and filePattern attributes. I was able to do so with the following script:
```
setlocal

set LOG4J_CONFIGURATION_FILE=../../configs/log-conf1.xml
start process.bat ../../configs insertAccounts

set LOG4J_CONFIGURATION_FILE=../../configs/log-conf2.xml
start process.bat ../../configs insertAccounts

set LOG4J_CONFIGURATION_FILE=../../configs/log-conf3.xml
start process.bat ../../configs insertAccounts
```

where log-conf1.xml has the following values for fileName and filePattern attributes:
```
		<RollingFile name="fileAppender" fileName="Logs1/sdl.log" filePattern="Logs1/sdl.log.%i" append="true">
```
log-conf2.xml has the following values for fileName and filePattern attributes:
```
		<RollingFile name="fileAppender" fileName="Logs2/sdl.log" filePattern="Logs2/sdl.log.%i" append="true">
```

and so on. 

This workaround works for my setup.

**Comment by ashitsalesforce** [comment]
closing the issue with the provided fix above.

**Comment by RadoslawNad** [comment]
Hi @ashitsalesforce  sorry for replying so late and thanks for researching the topic and providing a possible solution. At the moment I'm not able to implement it but it will probably be useful in the future.
Thank you.
