### ISSUE TITLE
MaxFileSize in log-conf.xml DL v54.0

### ISSUE THREAD

**Issue by juanlu-github** [forcedotcom/dataloader#439]
After the migration from log4j to log4j2 it isn't documented anywhere how the MaxFileSize should be defined in log-conf.xml.

OLD WORLD:
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE log4j:configuration SYSTEM "log4j.dtd">
<log4j:configuration>
    <appender name="fileAppender" class="org.apache.log4j.RollingFileAppender">
        <param name="File"   value="${java.io.tmpdir}/sdl.log" />
        <param name="Append" value="true" />
        <param name="MaxFileSize" value="100KB" />
        <param name="MaxBackupIndex" value="1" />
        <layout class="org.apache.log4j.PatternLayout">
            <param name="ConversionPattern" 
                   value="%d %-5p [%t] %C{2} %M (%F:%L) - %m%n"/>
        </layout>	    
    </appender>
    <appender name="STDOUT" class="org.apache.log4j.ConsoleAppender">
        <layout class="org.apache.log4j.PatternLayout">
            <param name="ConversionPattern"
                   value="%d %-5p [%t] %C{2} %M (%F:%L) - %m%n"/>
        </layout>	    
    </appender>
    
    <category name="org.apache.log4j.xml">
        <priority value="warn" />
        <appender-ref ref="fileAppender" />
        <appender-ref ref="STDOUT" />
    </category>
    
    <logger name="org.apache" >
            <level value ="warn" />
    </logger>
    
    <root>
        <priority value ="info" />
        <appender-ref ref="fileAppender" />
        <appender-ref ref="STDOUT" />
    </root>
</log4j:configuration>

NEW WORLD:
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
  <appenders>
    <File name="fileAppender" fileName="${sys:java.io.tmpdir}/sdl.log" append="true">
      <PatternLayout pattern="%d %-5p [%t] %C{2} %M (%F:%L) - %m%n"/>
    </File>
    <CONSOLE name="STDOUT" target="SYSTEM_OUT">
      <PatternLayout pattern="%d %-5p [%t] %C{2} %M (%F:%L) - %m%n"/>
    </CONSOLE>
  </appenders>
  <loggers>
    <logger name="org.apache.log4j.xml" level="warn">
      <AppenderRef ref="fileAppender"/>
      <AppenderRef ref="STDOUT" />
    </logger>
    <logger name="org.apache" level="warn">
      <AppenderRef ref="fileAppender"/>
      <AppenderRef ref="STDOUT" />
    </logger>
    <root level="info">
      <AppenderRef ref="fileAppender"/>
      <AppenderRef ref="STDOUT" />
    </root>
  </loggers>
</configuration>

-----------------------------------

I have tried adding the following to the <File name="fileAppender" ...> element, right after <PatternLayout...>:
  <Policies>
        <SizeBasedTriggeringPolicy size="100KB" />
      </Policies>
But it didn't work: ERROR appender File has no parameter that matches element Policies

Then I just tried directly:
<SizeBasedTriggeringPolicy size="100KB" />
But it didn't work either: ERROR appender File has no parameter that matches element SizeBasedTriggeringPolicy

Any ideas?

Thanks in advance.

**Comment by juanlu-github** [comment]
```
  <Policies>
    <SizeBasedTriggeringPolicy size="100KB" />
  </Policies>
```

**Comment by juanlu-github** [comment]
<SizeBasedTriggeringPolicy size="100KB" />

**Comment by juanlu-github** [comment]
All of the above didn't work.

**Comment by ashitsalesforce** [comment]
Hi @juanlu-github , try replacing the following lines in log-conf.xml:
```
    <File name="fileAppender" fileName="${sys:java.io.tmpdir}/sdl.log" append="true">
      <PatternLayout pattern="%d %-5p [%t] %C{2} %M (%F:%L) - %m%n"/>
    </File>
```

with

```
   <RollingFile name="fileAppender" fileName="${sys:java.io.tmpdir}/sdl.log"
                 filePattern="${sys:java.io.tmpdir}/sdl-%d{yyyy-MM-dd}.log"
                 ignoreExceptions="false">
      <PatternLayout>
          <Pattern>"%d %-5p [%t] %C{2} %M (%F:%L) - %m%n"</Pattern>
      </PatternLayout>
      <Policies>
          <SizeBasedTriggeringPolicy size="100KB" />
      </Policies>
      <DefaultRolloverStrategy max="1" />
    </RollingFile>
```

**Comment by juanlu-github** [comment]
Thanks @ashitsalesforce , it works! You are the best!

**Comment by juanlu-github** [comment]
:-)
