### ISSUE TITLE
Batch process failure with new version (v53.0.2) of data loader

### ISSUE THREAD

**Issue by omsairam9** [forcedotcom/dataloader#442]
As part of 'Product & Service Notification' about new data loader installation we have installed the new version and trying to sync the existing batch process (process.bat file) with new version. Initially we got few errors and worked with Salesforce to fix the same. During this process we have update process config and bat files. Also recreated the encrypted key and the associated password using the references provided by Salesforce vendor, but still we are facing the attached error and unable to proceed further. We are working with Salesforce from last 3 months to fix this issue, but we did not get the actual resolution for the same. Finally reaching out to you as per their suggestion to get your insights to fix the same. Please advise
[sal.txt](https://github.com/forcedotcom/dataloader/files/8365715/sal.txt)

**Comment by ashitsalesforce** [comment]
Hi @omsairam9 , thanks for sharing the console output. Here is the relevant output indicating the root-cause:
```
04:20:29.927 [main] FATAL com.salesforce.dataloader.process.ProcessRunner - Unable to run process SICCodeExtractInsert
java.lang.RuntimeException: Invalid username, password, security token; or user locked out.
	at com.salesforce.dataloader.process.ProcessRunner.run(ProcessRunner.java:180) ~[dataloader-53.0.2-uber.jar:?]
```
Here are the steps to make sure you are encrypting the password correctly:

- Encrypt your password along with your security token - `encrypt -e <your password + security token> <your encryption key file>`
- Verify that the encrypted password is decrypted correctly using the new encryption key file - `encrypt -d <encrypted password> <your encryption key file>`
- Specify the encryption key file (`process.encryptionKeyFile` property) and the new encrypted password (`sfdc.password` property) in process-conf.xml

**Comment by ashitsalesforce** [comment]
Hi @omsairam9 , can you use the same username, password, and security token you have provided in process-conf.xml to login in the interactive mode of data loader to verify that you can successfully login in the interactive mode using the same credentials?

**Comment by omsairam9** [comment]
Hi @ashitsalesforce,

We have used the same credentials inside process-conf.xml file. Just copying the lines that is present in process-conf.xml file for your reference.

<entry key="sfdc.endpoint" value="https://login.salesforce.com"/>
<entry key="sfdc.username" value="XXXXXXX@ryder.com"/>, XXXX is the user name
<entry key="sfdc.password" value="XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"/>, XXXX is the encrypted password created using password_security token
<entry key="process.encryptionKeyFile" value="..\..\..\conf\encrypt.key"/>

Thanks,
Siva.

**Comment by ashitsalesforce** [comment]
Hi @omsairam9 ,

2 questions:
- are you able to successfully login using data loader interactive mode?
- Let's say your username is "dluser", password is "dlpassword", and security token is "sectoken". Are you encrypting "dlpasswordsectoken" or are you encrypting "dlpassword_sectoken" or something else? The correct string to encrypt is "dlpasswordsectoken".

**Comment by omsairam9** [comment]
Hi Ashit,

I just supplied the same credentials to the data loader in interactive mode and I was able to login successfully. Please refer the attached screen shot for the same

Thanks,
Siva.
![Case#42213041_Credentials-Usage-in_Interactive mode](https://user-images.githubusercontent.com/102551653/162263507-ee9890bd-6014-44aa-ac9a-342bf0961acf.jpg)

**Comment by ashitsalesforce** [comment]
Thanks @omsairam9 . Please provide the details of how you are appending security token to password for encrypting. Let's say your username is "dluser", password is "dlpassword", and security token is "sectoken". Are you encrypting "dlpasswordsectoken" or are you encrypting "dlpassword_sectoken" or something else?

**Comment by omsairam9** [comment]
Hi Ashit,

Let me provide the complete details here.  Instead of going back and forth with too many emails, Can we meet once ? So that I can walkthrough the encryption process which we followed and you can correct me if I am missing something during that process. Let me explain you the steps that i followed to create the encrypted password.

Step-1: Created the key using the following command "encrypt.bat -k" and it has created the key in the following directory "C:\Users\sreddy3\.dataloader\dataLoader.key
Step-2 : Created the encrypted password using the following command 
"encrypt.bat –e dlpasswordsectoken C:\Users\sreddy3\.dataloader\dataLoader.key" and it has created a long encrypted password
Step-3: As suggested I have also successfully validated the encrypted password created through step-2 using the following command 
"encrypt -d encryptedpassword C:\Users\sreddy3\.dataloader\dataLoader.key. 
Step-4 : Finally, I have used them in my process-config file like this

<entry key="sfdc.endpoint" value="https://login.salesforce.com"/>
<entry key="sfdc.username" value="etluser@ryder.com"/>


<entry key="sfdc.password" value="XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"/>
<entry key="process.encryptionKeyFile" value="..\..\..\conf\encrypt.key"/>

Thanks,
Siva

**Comment by ashitsalesforce** [comment]
Hi @omsairam9 , thanks for further details. We will work on the logistics of having a call through our Support team.

**Comment by ashitsalesforce** [comment]
closing as the customer is working with Support team to resolve the issue.

**Comment by Linhla85** [comment]
> encrypt.bat -k

When I try to create the key with "encrypt.bat -k" there is issue "Common was unexpected at this time". How can I fix it?

**Comment by ashitsalesforce** [comment]
Hi @Linhla85 , it is likely an error message showing up in the bat script. Rerun encrypt.bat script after changing the first line from 
```
@echo off
```
to
```
@echo on
```

and provide its output.
