### ISSUE TITLE
Unable to get Data Loader running on macOS Monterey

### ISSUE THREAD

**Issue by wherestheguac** [forcedotcom/dataloader#443]
None of the versions appear to work at all on Monterey, 12.3

**Comment by ashitsalesforce** [comment]
Hi @wherestheguac, please provide the following information to troubleshoot your issue:
- which versions of data loader you have tried
- how are you launching data loader
- console output
- logged messages

**Comment by ashitsalesforce** [comment]
closing assuming that the issue is resolved.
