### ISSUE TITLE
Cannot sign CLA or contact contactoss-cla@salesforce.com

### ISSUE THREAD

**Issue by ckoppelman** [forcedotcom/dataloader#446]
Please help!  I've submitted a PR to fix a bug in the Windows Batch script when `%DATALOADER_JAVA_HOME%` is different from `%JAVA_HOME%`.  It tells me I need to sign a CLA.  

I walked through the web interface, but got an error and was told to email contactoss-cla@salesforce.com.  That email address bounced. What should I do?

**Comment by ashitsalesforce** [comment]
Hi @ckoppelman , likely that your CLA issue is resolved. I am closing this issue for now as we will know for sure when you submit a new PR.
