### ISSUE TITLE
Windows Batch script runs wrong version of Java when `%DATALOADER_JAVA_HOME%` is set

### ISSUE THREAD

**Issue by ckoppelman** [forcedotcom/dataloader#447]
When `%DATALOADER_JAVA_HOME%` is different from `%JAVA_HOME%`, the Windows Batch script runs the wrong Java on line 56, but not on line 38.

**Comment by ashitsalesforce** [comment]
Hi @ckoppelman , 

Can you provide the detailed steps to reproduce the issue? We would need details such as:
- Does your system Path or User Path contain a different java version?
- Which version of data loader you are running.
- What is on lines 38 and 56 of dataloader.bat on your desktop?

The reason to specify double-quotes in the following lines is to escape the space characters in the folder path containing JRE. 
```
:AFTER_BANNER
 
IF NOT "%DATALOADER_JAVA_HOME%" == "" (
    set JAVA_HOME="%DATALOADER_JAVA_HOME%"
)
```

For example, a user may have installed JRE in `C:\Users\john doe\java` folder.

**Comment by ckoppelman** [comment]
System PATH contains a different Java version.

I'm running 54.0.0

I understand the reason for quotes, but it was failing when I used code as written.

Line 38: 

```bat
    java -version 1>nul 2>nul || (
```

Line 57: (I misread it)

```bat
    java -D"org.eclipse.swt.browser.IEVersion=12001" -jar %DATALOADER_UBER_JAR_NAME% %*
```

**Comment by ashitsalesforce** [comment]
Thanks @ckoppelman , 

This is perplexing because we can't reproduce the issue. Can you change the first line of dataloader.bat from `@echo off` to `@echo on`, capture the console output, and provide it for further troubleshooting?

**Comment by ckoppelman** [comment]
Ah Hah!  I figured out the issue -- DATALOADER_JAVA_HOME must not end with a `\`.  Now it's working smoothly.  Thank you.

**Comment by ashitsalesforce** [comment]
Hi @ckoppelman , good to hear that the issue was resolved. Thanks for sharing the root-cause and the resolution.
