### ISSUE TITLE
Mapping for field ignored Error

### ISSUE THREAD

**Issue by jgoldfed** [forcedotcom/dataloader#47]
Is there a way to eliminate the else statement on Line 80 of LoadMapper.java?

```
        } else {
            logger.info("Mapping for field " + entry.getKey() + " will be ignored since destination column is empty");
        }
```

Having blank destination columns on the success/error log without the message on the debug is critical for our data teams to process reference values efficiently. This was not present in v27 and we are requesting either a way to turn off or toggle this particular feature.

**Comment by ashitsalesforce** [comment]
@jgoldfed , have you tried changing the log level to warn in log-conf.xml? For example, v51 ships with the following setting:
`  <root level="debug">
      <AppenderRef ref="fileAppender"/>
      <AppenderRef ref="STDOUT" />
    </root>`

You can change it to:
`  <root level="warn">
      <AppenderRef ref="fileAppender"/>
      <AppenderRef ref="STDOUT" />
    </root>`
