### ISSUE TITLE
Unescaped backslashes in csv export file

### ISSUE THREAD

**Issue by egiraudy** [forcedotcom/dataloader#49]
When a field, in salesforce, contains a backslash, the backslash is not escaped, breaking the csv format.

**Comment by ashitsalesforce** [comment]
Hi @egiraudy , what software are you using to read/process the csv file that is breaking without escaping the backslash? The issue was reported a while back and given that there are no more reports and data loader is currently in maintenance mode with only critical bug fixes, closing it.
