### ISSUE TITLE
Open Source Forum link is broken

### ISSUE THREAD

**Issue by rdosser** [forcedotcom/dataloader#50]
I'm excited to use this tool, and I've got questions, but the readme file's link to the open source forum - http://boards.developerforce.com/t5/Open-Source/bd-p/sforceExplorer - is broken. Is there an up-to-date URL for that?

**Comment by diracz** [comment]
I can double check on that. 
In the meantime, Dataloader has pretty good documentation (http://www.salesforce.com/us/developer/docs/dataLoader/) But if you still have technical problem you can post it here.

**Comment by diracz** [comment]
I updated README so it has https://developer.salesforce.com/forums?feedtype=RECENT&dc=APIs_and_Integration&criteria=ALLQUESTIONS&#!/feedtype=RECENT&criteria=ALLQUESTIONS& as new link. The API and integration section is where you can post data loader questions.
