### ISSUE TITLE
dataloader fails to start on windows if the user name has space in it

### ISSUE THREAD

**Issue by nsrahmad** [forcedotcom/dataloader#538]
https://github.com/forcedotcom/dataloader/blob/ddb2a9ad332a71a48bacac766d539e866679d90d/release/win/install.bat#L8
I located the bug to this variable. simply wrapping the value of `DATALOADER_UBER_JAR_NAME` in double quotes fixes this.

**Comment by ashitsalesforce** [comment]
Hi @nsrahmad , `install.bat` is used to install data loader artifacts, not run it. Also, there is no username involved in the line you are pointing out. Let us know the specifics of the issue you are seeing such as the version of data loader, command you are executing, and console output so that we can troubleshoot this further.

**Comment by nsrahmad** [comment]
Yeah, my mistake. I was in a rush so just opened github repo, searched for the variable and clicked in the gutter to create the issue. Now I can see that it is confusing and totally not helpful. 

Firstly, I don't use salesforce stuff myself, my brother does. He installed dataloader in default location (that is when the username gets involved) and tried to run it by clicking the desktop icon. Nothing happened so he called me to take a look. I followed the link from desktop to the installed startup script (dataloader.bat), ran the script in terminal, saw the truncated path in the console, quoted the path and it ran.

dataloader version was whatever was available to download yesterday. I can get more information if you need. But you can easily recreate if you make a local account with a username containing space.

**Comment by ashitsalesforce** [comment]
Hi @nsrahmad , thanks for reporting the issue. We will look into it. I am closing the issue as there have been significant changes to the bat script including using double-quotes around variables whose values may have space or other special characters in them.
