### ISSUE TITLE
v56.0.0 Related Object reference (Id not an option)

### ISSUE THREAD

**Issue by matt-newell** [forcedotcom/dataloader#554]
When upserting records the related object relationship no longer shows `Id` as a valid option. 

This behavior started at 56.0.0 downgrading seems to resolve the issue. 

![Before 56 0 0](https://user-images.githubusercontent.com/7570953/185967560-f37f2a8c-50d2-4cd9-aa27-5e9335a4e916.png)
![56 0 0](https://user-images.githubusercontent.com/7570953/185967564-e337258e-ffbd-4993-a929-cbc1662729b8.png)

**Comment by ashitsalesforce** [comment]
Hi @matt-newell , thanks for catching this issue. We are looking into it and will shortly provide a patch fix.

**Comment by ashitsalesforce** [comment]
Attaching data loader v56.0.1 containing the fix.

[dataloader_win_v56.0.1.zip](https://github.com/forcedotcom/dataloader/files/9396400/dataloader_win_v56.0.1.zip)
MD5 of dataloader_win_v56.0.1.zip: 02f5af46ed183a19b6a58955c4c34f2d

[dataloader_mac_v56.0.1.zip](https://github.com/forcedotcom/dataloader/files/9396341/dataloader_mac_v56.0.1.zip)
MD5 of dataloader_mac_v56.0.1.zip: 76355539436874a1c9fbbb34c7ff9c5e

**Comment by matt-newell** [comment]
Thank You
