### ISSUE TITLE
Cannot launch Dataloader

### ISSUE THREAD

**Issue by aalborz** [forcedotcom/dataloader#578]
**Describe the bug**
I have installed the program, but when I try to launch it from the desktop shortcut, I'm getting an error about JRE not being installed or to set DATALOADER_JAVA_HOME environment variable to the value <full path to the JRE installation folder>. JRE is installed and the environment variable already exists.

**Expected behavior**
I expect the program to launch successfully.

**Screenshots**
![image](https://user-images.githubusercontent.com/9065072/204585565-ee47c7fc-68f4-4c24-96e7-f62ba5c99225.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro (64bit)
 - Version: 21H2

**Comment by ashitsalesforce** [comment]
Hi @aalborz , if you are setting `DATALOADER_JAVA_HOME` to the value ".", which is a relative directory path, set it to an absolute directory path and retry.

**Comment by aalborz** [comment]
I'm sorry I didn't get the initial reply. What is your proposed solution?
    On Tuesday, December 6, 2022 at 01:21:30 PM EST, ashitsalesforce ***@***.***> wrote:  
 
 


closing assuming that the issue is resolved.

**Comment by ashitsalesforce** [comment]
Hi @aalborz , if you set DATALOADER_JAVA_HOME to a relative path such as ".", set it to an absolute path where JRE or JDK is installed.

**Comment by aalborz** [comment]
I've already done that.
    On Tuesday, December 6, 2022 at 05:00:34 PM EST, ashitsalesforce ***@***.***> wrote:  
 
 


Hi @aalborz , if you set DATALOADER_JAVA_HOME to a relative path such as ".", set it to an absolute path where JRE or JDK is installed.
