### ISSUE TITLE
official documentation typo csvWriter instead of csvWrite in dataAccess.type

### ISSUE THREAD

**Issue by magowiz** [forcedotcom/dataloader#579]
In official documentation, at page in https://developer.salesforce.com/docs/atlas.en-us.dataLoader.meta/dataLoader/loader_params.htm
I found that is written that a valid value for `dataAccess.type` is `csvWriter`, but the correct value is `csvWrite`, I found it using dataloader application that tells me:
```
2022-12-02 10:48:02,654 ERROR [contact_extract] dao.DataAccessObjectFactory getDaoInstance (DataAccessObjectFactory.java:64) - The specified data access object type: csvWriter is not supported
```

**Expected behavior**
Documentation should point to correct types

**Comment by ashitsalesforce** [comment]
Hi @magowiz , thanks for reporting this issue. We will fix the documentation.

**Comment by ashitsalesforce** [comment]
Documentation is fixed.
