### ISSUE TITLE
Build Failure : Some files do not have the expected license header

### ISSUE THREAD

**Issue by tggagne** [forcedotcom/dataloader#58]
Am trying to build dataloader locally and understand what it does inside.

When I run "mvn clean package -DskipTests" the build ends with the error:

[INFO] Missing header in: /Users/tgagne/work/git/dataloader/src/test/java/com/salesforce/dataloader/process/ProcessExtractTestBase.java
[INFO] Missing header in: /Users/tgagne/work/git/dataloader/src/test/java/com/salesforce/dataloader/process/CsvUpsertProcessTest.java
[INFO] Missing header in: /Users/tgagne/work/git/dataloader/src/test/java/com/salesforce/dataloader/TestBase.java
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 7.760 s
[INFO] Finished at: 2015-04-07T10:38:09-04:00
[INFO] Final Memory: 32M/510M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.mycila.maven-license-plugin:maven-license-plugin:1.8.0:check (default) on project dataloader: Some files do not have the expected license header -> [Help 1]

I've confirmed /Users/tgagne/work/git/dataloader/license.txt exists.  I've even tried editing the <header /> tag to use the full path as was suggested elsewhere on the 'net.

I just cloned the repo this AM (7Apr2015).

**Comment by diracz** [comment]
You can add a -Dlicense.skip=true at your command. 
In the meantime I suspect there's some license header that's changed.

**Comment by tggagne** [comment]
That worked.  When I tried to run it it complained that it needed Java 1.6.  Is there a way to get around that to use Java 1.8?

**Comment by diracz** [comment]
Not that I'm aware of.
