### ISSUE TITLE
Dataloder 

### ISSUE THREAD

**Issue by chimpanzee818** [forcedotcom/dataloader#585]
Hi everyone,
can any one please help me,

basically i am running dataloder job on unix server but after api upgradation i have to upgrade the dataloder api also so with new upgradation we have to pass the endpoint , batch size, org Id and password from config property file rather than process conf file.

so for one org id i know how to do that but with to org id how we will do that how be will update the org id and password from config file. 

Thanks in advance 
Saumya singh

**Comment by ashitsalesforce** [comment]
Hi @chimpanzee818, 

Are you trying to set some of the following properties?
```
sfdc.endpoint
sfdc.loadBatchSize
sfdc.extractionRequestSize
dataAccess.writeBatchSize
dataAccess.readBatchSize
sfdc.username
sfdc.password
```

Are you referring to sfdc.username property when you mention org id?

Which version of data loader are you upgrading to? The latest version (v57.0.0) lets you specify the properties in command line, `process.conf` file, or `config.properties` file. A property specified in command line overrides its setting in `process.conf` and `config.properties`. A property specified in `process.conf` overrides its setting in `config.properties`.

**Comment by chimpanzee818** [comment]
hi thank you for ur response,

i am upgrading at version Dataloder V55.
yaa u right i am referring sfdc.username property when i mention org id.

Yes, here again u also right i am trying to set the setting in config.properties one.

" sfdc.endpoint
sfdc.loadBatchSize
sfdc.extractionRequestSize
dataAccess.writeBatchSize
dataAccess.readBatchSize
sfdc.username
sfdc.password"


this one i can use when i hv to set for one user id in config.properties  but my scenario is different like -


i am extracting account record from b2b user and upserting it into account of b2c user.
so i hv to set the setting for both b2b and b2c in config.properties, 
for single user we simply set it but how we will set for two user id ?
b2b user id = testb2b.devbox
b2c user id = testb2c.devbox

**Comment by ashitsalesforce** [comment]
Hi @chimpanzee818 , thanks for confirming the properties you are setting. You are performing 2 batch operations: extract (for b2b user) and upsert (for b2c user). Can you provide the command you are entering in the command shell for each?

**Comment by chimpanzee818** [comment]
hi @ashitsalesforce 

i am not sure are you talking about this 
process.name=DataExtract for b2b and 
 process.name=UpsertAccounts

**Comment by ashitsalesforce** [comment]
Hi @chimpanzee818 , are you executing the following command in the command line:
```
java -jar target/dataloader-55.0.1-uber.jar run.mode=batch process.name=DataExtract salesforce.config.dir=<path to config dir containing process-conf.xml and config.properties files>
```

**Comment by chimpanzee818** [comment]
Hi @ashitsalesforce 
yes oky u want this,

for B2B
java -cp /home/oracrm/lampstack/apache2/htdocs/DataLoader12535/dataloader-55.0.1-uber.jar -Dsalesforce.config.dir="/home/oracrm/lampstack/apache2/htdocs/DataLoader12535/conf" com.salesforce.dataloader.process.DataLoaderRunner run.mode=batch  process.name=DataExtract

AND 
for b2c
java -cp /home/oracrm/lampstack/apache2/htdocs/DataLoader12535/dataloader-55.0.1-uber.jar -Dsalesforce.config.dir="/home/oracrm/lampstack/apache2/htdocs/DataLoader12535/conf" com.salesforce.dataloader.process.DataLoaderRunner run.mode=batch  process.name=UpsertAccounts

**Comment by ashitsalesforce** [comment]
Thanks. Try the following:

- Upgrade to v57.0.0

- Run
```
java -cp /home/oracrm/lampstack/apache2/htdocs/DataLoader12535/dataloader-57.0.0-uber.jar -Dsalesforce.config.dir="/home/oracrm/lampstack/apache2/htdocs/DataLoader12535/conf" com.salesforce.dataloader.process.DataLoaderRunner run.mode=batch process.name=DataExtract sfdc.username=<b2b user> sfdc.password=<encoded b2b user password> sfdc.endpoint=<your endpoint> sfdc.extractionRequestSize=<your extraction request size>
```

followed by 
```
java -cp /home/oracrm/lampstack/apache2/htdocs/DataLoader12535/dataloader-55.0.1-uber.jar -Dsalesforce.config.dir="/home/oracrm/lampstack/apache2/htdocs/DataLoader12535/conf" com.salesforce.dataloader.process.DataLoaderRunner run.mode=batch process.name=UpsertAccounts sfdc.username=<b2c user> sfdc.password=<encoded b2c user password> sfdc.endpoint=<your endpoint> sfdc.loadBatchSize=<your load batch size>
```

**Comment by chimpanzee818** [comment]
Hi @ashitsalesforce 
Thanku i will,

We will not give anything in config.properties file

**Comment by chimpanzee818** [comment]
hi @ashitsalesforce 
when i am running shell script its throwing an error
 java.lang.RuntimeException: com.salesforce.dataloader.exception.ControllerInitializationException: Error loading config file: <path>/config.properties.  Please make sure that it exists and is readable

even i have given all the permission, how can i resolve it 

please response fast

**Comment by ashitsalesforce** [comment]
Hi @chimpanzee818 , 

Were you able to successfully specify different config properties through command line for b2b extract and b2c upsert operations?

What command are you typing in the command shell when invoking the shell script and seeing the error about config.properties file?

`Error initializing encryption for key file /conf/key.txt>: Failed to open file:` error seems to be when you execute a different command. what command are you running in the command shell when you see this error?

Regarding your last comment, note that this is a volunteer-maintained forum. Go through Salesforce support if you need quick response.

Thanks

**Comment by chimpanzee818** [comment]
hi @ashitsalesforce 

thank you for response,

command line i hv used

for extract--
java -cp /path/dataloader-55.0.1-uber.jar -Dsalesforce.config.dir="/path/conf" com.salesforce.dataloader.process.DataLoaderRunner run.mode=batch  process.name=DataExtract sfdc.username="<b2b@salesforce.com>" sfdc.password="<password>" sfdc.endpoint="<https://test.salesforce.com>" 
 process.encryptionKeyFile="<path/conf/key.txt>"

for upsert--
java -cp /path/dataloader-55.0.1-uber.jar -Dsalesforce.config.dir="/path/conf" com.salesforce.dataloader.process.DataLoaderRunner run.mode=batch  process.name=UpsertAccounts sfdc.username="<b2c@salesforce.com>" sfdc.password="<password>" sfdc.endpoint="<https://test.salesforce.com>" process.encryptionKeyFile="<path/dataLoader.key>" sfdc.loadBatchSize="<10>"

**Comment by chimpanzee818** [comment]
hi @ashitsalesforce 

runinng shell script i mean executing dataloder  like we fire command = ./shallscriptName

after executing  this command. i hv seen this error 
 
during Error initializing encryption for key file <path/key.txt>: Failed to open file: <path/conf/key.txt>
2023-01-10 12:46:21,684 ERROR [DataExtract] controller.Controller <init> (Controller.java:134) - Exception happened in initConfig:
com.salesforce.dataloader.exception.ControllerInitializationException: Error loading config file: /home/oracrm/lampstack/apache2/htdocs/DataLoader12535/conf/config.properties.  Please make sure that it exists and is readable
 
like recently we upgraded the dataloder there are so many job runinng if again i will upgrade it then they were affect
thats why how can i insert multiple org  in v55

**Comment by ashitsalesforce** [comment]
hi @chimpanzee818 

Have you created an encryption key file as described [here](https://developer.salesforce.com/docs/atlas.en-us.dataLoader.meta/dataLoader/command_line_create_encryption_key.htm)? Also, have you encrypted the password described [here](https://developer.salesforce.com/docs/atlas.en-us.dataLoader.meta/dataLoader/command_line_create_enc_password.htm)? Note that you will have to look into the relevant Windows script (`encrypt.bat`) to figure out appropriate java commands.

**Comment by ashitsalesforce** [comment]
hi @chimpanzee818 

The error message `Error initializing encryption for key file <path/key.txt>: Failed to open file: <path/conf/key.txt>` means data loader did not find the key file. Did you specify `process.encryptionKeyFile="<path/conf/key.txt>"` in extract operation or did you specify the absolute path to the file containing the key? For example, if the key file is at location `/user/home/john/.dataloader/dataloader.key`, I would specify `process.encryptionKeyFile="/user/home/john/.dataloader/dataloader.key"`

**Comment by chimpanzee818** [comment]
hi @ashitsalesforce 

right now its throwing an error fail -

 controller.Controller initConfig (Controller.java:397) - The controller config has been initialized
 ERROR [TAPColleagueRecord] security.EncryptionAesUtil decryptMsg (EncryptionAesUtil.java:217) - Fail to decrypt message: For input string: "<4"

 ERROR [TAPColleagueRecord] config.Config decryptProperty (Config.java:841) - Error loading parameter: sfdc.password of type: java.lang.String

how can i resolve this i error i am facing  after specifying the key as process.encryptionKeyFile="/user/home/john/.dataloader/dataloader.key"

but key is perfectively working for other jobs

**Comment by ashitsalesforce** [comment]
It is possible that `sfdc.password` value is set incorrectly or the value is incorrect. For example, if the encrypted password is `123456`, are you specifying `sfdc.password="<123456>` or `sfdc.password="123456"`? The correct way to specify the password is `sfdc.password="123456"`.

**Comment by chimpanzee818** [comment]
hy @ashitsalesforce 

right now error is 
 FATAL [DataExtract] process.ProcessRunner validateConfigProperties (ProcessRunner.java:339) - Required parameter sfdc.password is unspecified or empty

Thank you thank you for your response 
is there any way i can decrypt my password.

**Comment by ashitsalesforce** [comment]
@chimpanzee818 , good to hear that it ran. In case you are still curious about how to decrypt the password, send me the command you used to encrypt it and I will tell you how to use the same command with -d flag to decrypt it.

**Comment by chimpanzee818** [comment]
@ashitsalesforce 
Thank you ones again,
Actually i forget how i encrypted my password but after so many struggle finally i  remember
how i did that's why
First decrypted my password nd found my mistake.

**Comment by chimpanzee818** [comment]
@ashitsalesforce 

hy again i need ur help 

i am inserting record from differert csv in a obj throught dataloder 

process what i used i convert all csv data into one csv  after that final csv use for inserting but earlier i didnt face such error but right now i am facing an error could u plezz help me 

error is "com.salesforce.dataloader.exception.DataAccessRowException: Error reading row #0: the number of data columns (1) is less than the number of columns in the header (25)"


even i hv check my data.csv its exactly having 25 coulmn as it is expecting.

**Comment by chimpanzee818** [comment]
Hy @ashitsalesforce 
I am facing an error can you please help me Mapping for field header will be ignore since destination is empty 

And this we face during prod deployment

**Comment by chimpanzee818** [comment]
Oky
