### ISSUE TITLE
Reopen of #43: Field API name should be case insensitive in sdl mapping file

### ISSUE THREAD

**Issue by ubraig** [forcedotcom/dataloader#597]
Ran into the very same issue as described in issue #43.
#43 has been closed as completed on  Feb 26, 2021 ??

Now, when using with dataloader-57.0.1-uber.jar, running in batch mode to upsert Accounts with the following sdl file:

```
MyExternalId__c=MyExternalId__c
#
# only this one will work: target field name exactly same case as in system
NAME=Name
#
# this one won't work
#NAME=NAME
```

When using the mapping `NAME=Name` it will work.
When using the mapping `NAME=NAME` it won't work: See exception below.

```
Exception in thread "main" java.lang.RuntimeException: Invalid property name 'NAME'
        at com.salesforce.dataloader.process.ProcessRunner.logErrorAndExitProcess(ProcessRunner.java:246)
        at com.salesforce.dataloader.process.DataLoaderRunner.main(DataLoaderRunner.java:80)
```

**Comment by ashitsalesforce** [comment]
Hi @ubraig , thanks for reporting the issue. I am attaching zip files containing the fix in case you want to try the fix before the next patch or major release.

MD5 (dataloader_mac_v57.0.2.zip) = bcf68115b9243f7b6f26ce4e134fcc19
MD5 (dataloader_win_v57.0.2.zip) = 4e66ec2091a6cc02a4c3fa344f4234e9

[dataloader_mac_v57.0.2.zip](https://github.com/forcedotcom/dataloader/files/10728568/dataloader_mac_v57.0.2.zip)
[dataloader_win_v57.0.2.zip](https://github.com/forcedotcom/dataloader/files/10728593/dataloader_win_v57.0.2.zip)

**Comment by ubraig** [comment]
Hi @ashitsalesforce,
thanks a lot for fixing so quickly.
Now works fine.

**Comment by ashitsalesforce** [comment]
Hi @ubraig , thanks for reporting the issue and confirming the fix.
