### ISSUE TITLE
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.

### ISSUE THREAD

**Issue by wailam-chpscc** [forcedotcom/dataloader#603]
Hi,

How can I resolve the warning message below? This message appears in other closed issues but I didn't see it directly addressed in those threads. In what way would performance be impacted?

1. Installed Data Loader per "[Install Data Loader on Windows](https://developer.salesforce.com/docs/atlas.en-us.dataLoader.meta/dataLoader/loader_install_windows.htm)"
2. Open Data Loader 57.0.1 and see the output below on start up:
```
Data Loader requires Java JRE 11 or later. Checking if it is installed...
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
2023-02-17 16:24:41,721 INFO  [main] controller.Controller _doInitializeLog (Controller.java:402) - The log has been initialized
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.                                                                                                                                               2023-02-17 16:24:42,365 INFO  [main] controller.Controller _doInitializeLog (Controller.java:402) - The log has been initialized
```

I believe I am using a compatible Java version (`Data Loader requires Java JRE 11 or later.`) but please let me know if I should re-install or update to the newest version.
```
C:\Users> java --version
openjdk 19.0.1 2022-10-18
OpenJDK Runtime Environment Zulu19.30+11-CA (build 19.0.1+10)
OpenJDK 64-Bit Server VM Zulu19.30+11-CA (build 19.0.1+10, mixed mode, sharing) 
```

 Thanks in advance for your advice.

**Comment by ashitsalesforce** [comment]
Hi @wailam-chpscc , this is not an operator error or usage of an incompatible Java version. We plan to fix this issue in the upcoming release.

**Comment by ashitsalesforce** [comment]
Fix is checked in.

**Comment by wailam-chpscc** [comment]
@ashitsalesforce, thank you for the clarification!
