### ISSUE TITLE
Popup window expands to the full height of the screen (vertical axis)

### ISSUE THREAD

**Issue by Arv18** [forcedotcom/dataloader#647]
**Describe the bug**
When you click on any of the options, the displayed popup window (after Log In) expands to the full height of the screen (vertical axis).

![image](https://user-images.githubusercontent.com/25601985/229874175-627e1a3f-f57f-48da-b3d7-4c5d88a27bd6.png)

**To Reproduce**

1. Open "Data Loader 57.0.1"
2. Click on "Insert" (or any option).
3. Fill in the necessary data to log in, and click on "Log In".
4. Click on "Next"
5. The new popup window appears expanded vertically to the height of the screen (without the taskbar).

**Expected behavior**
The window should either keep a default size like the login window or keep the settings from the last data loader session. This may not be a high-priority bug, but on large screens, it is very annoying. 

**Screenshots**
Popup window expanded:
![image](https://user-images.githubusercontent.com/25601985/229876954-8f428410-cbb7-4ba8-bc7f-0277196d86b3.png)

**Desktop (please complete the following information):**
 - OS: Windows 11 Home
 - Version: 22H2

**Additional context**
This may not be a high-priority bug.

**Comment by Arv18** [comment]
Sometimes the width is also expanded a bit.

**Comment by ashitsalesforce** [comment]
Hi @Arv18 , thanks for reporting this issue. We have checked in a code change to mitigate it in the upcoming release that will be available with the next major Salesforce release. I will close the issue. However, open a new one if you still see the issue in the upcoming release.

**Comment by Arv18** [comment]
> Hi @Arv18 , thanks for reporting this issue. We have checked in a code change to mitigate it in the upcoming release that will be available with the next major Salesforce release. I will close the issue. However, open a new one if you still see the issue in the upcoming release.

Perfect, thanks @ashitsalesforce  I'll have it in mind.
