### ISSUE TITLE
"Sql error: Missing IN or OUT parameter at index:: 1" when @ symbol appears in SQL query

### ISSUE THREAD

**Issue by tggagne** [forcedotcom/dataloader#68]
Dataloader complains with the error above when a SQL query contains an @ symbol in its SELECT as in:

```
select ...
    trim(oprid) || '@domain.com' || '.full' email,
    trim(oprid) || '@domain.com' || '.full' username
```

**Comment by tggagne** [comment]
One work-around in Oracle SQL is to use:
```
trim(oprid) || chr(64) || 'domain.com' || '.full' email,
```
to hide the @ from dataloader.

I imagine other databases have a similar string function for creating ascii characters from integer values.

**Comment by ashitsalesforce** [comment]
thanks for the workaround @tggagne
