### ISSUE TITLE
Cosmetic issue: Estimated time to complete is inaccurate

### ISSUE THREAD

**Issue by bmercernccer** [forcedotcom/dataloader#711]
**Describe the bug**
When using dataloader to insert or update large numbers of records, the progress dialog shows a green progress bar and a count of processed records with successes and failures, all of which show accurate information. However the hourly rate and estimated completion time are comically wrong. The use of the bulk api changes the numbers, but doesn't make them realistic.  

**To Reproduce**
1. Perform an Insert, Upsert, or Update with a large number of records. 
2. Observe the records per hour rate and the estimated time to complete.
3. Note that the records per hour rate displayed is drastically greater than the actual rate of processing. Often the rate it provides is physically impossible. 
4. Note that the estimated time to complete is drastically less than the actual observed time, often indicating the process should be complete within a second or two even though it's obvious that hours are required.

**Expected behavior**
I would not expect perfection, but I would expect the rate to be at least of the same order of magnitude as the actual observed rate. I'd expect the estimated time to complete to be within +/- 50% of the actual value, and I'd expect the estimate to become more accurate over time as more data is processed.

**Screenshots**
![image](https://github.com/forcedotcom/dataloader/assets/21127097/e07dc082-d621-4e3d-b0a4-febadb6320f3)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: Multiple, including 57 and 58

**Comment by ashitsalesforce** [comment]
Hi @bmercernccer , thanks for reporting this issue. We are adding information about elapsed time o make it easier to troubIeshoot such issues in the future. I am attaching a few screenshots of a potential fix we plan to make in a future release.
<img width="645" alt="Screenshot 2023-07-02 at 9 48 05 PM" src="https://github.com/forcedotcom/dataloader/assets/71143047/7610187e-fda7-4333-8e4d-de59056ce8f7">
<img width="646" alt="Screenshot 2023-07-02 at 9 48 17 PM" src="https://github.com/forcedotcom/dataloader/assets/71143047/b7bed7b2-318b-49e4-95c5-105557299763">
<img width="653" alt="Screenshot 2023-07-02 at 9 48 25 PM" src="https://github.com/forcedotcom/dataloader/assets/71143047/c8a9e7da-736e-4c9d-9955-8306555c76ff">
<img width="644" alt="Screenshot 2023-07-02 at 9 48 38 PM" src="https://github.com/forcedotcom/dataloader/assets/71143047/48b511b8-e5ba-4fb8-8190-426a22f211fa">
<img width="646" alt="Screenshot 2023-07-02 at 9 50 35 PM" src="https://github.com/forcedotcom/dataloader/assets/71143047/7279adc9-819e-482a-a22e-8b924d65edd3">

**Comment by ashitsalesforce** [comment]
In case you want to try before the next official release, here is the zip file containing the fix
[dataloader_v58.0.3.zip](https://github.com/forcedotcom/dataloader/files/11941754/dataloader_v58.0.3.zip)

MD5 (dataloader_v58.0.3.zip) = 058da365fa054c207b2ff2886ed064dd
