### ISSUE TITLE
Dataloder 23 Version facing issue 

### ISSUE THREAD

**Issue by chimpanzee818** [forcedotcom/dataloader#713]
Hi @ashitsalesforce 

thanks in advance,
actually i shifted data Loder version 23  
and earlier we didn't face any issue but right now we r facing issue i tried to search compare with prod every thing same but still we r getting error.

error :

[oracrm@crmqa1app1 Late_Disbursement]$ ./loadDataToSalesforce.sh
log4j:ERROR Parsing error on line 2 and column 16
log4j:ERROR Document root element "configuration", must match DOCTYPE root "null".
log4j:ERROR Parsing error on line 2 and column 16
log4j:ERROR Document is invalid: no grammar found.
log4j:WARN The <configuration> element has been deprecated.
log4j:WARN Use the <log4j:configuration> element instead.
log4j:ERROR Parsing error on line 2 and column 16
log4j:ERROR Document root element "configuration", must match DOCTYPE root "null".
log4j:ERROR Parsing error on line 2 and column 16
log4j:ERROR Document is invalid: no grammar found.
log4j:WARN The <configuration> element has been deprecated.
log4j:WARN Use the <log4j:configuration> element instead.
[oracrm@crmqa1app1 Late_Disbursement]$ ls

please check it,
Thanks,

**Comment by ashitsalesforce** [comment]
Hi @chimpanzee818 , log4j had a major version change from 1.x to 2.x between data loader 58 and 23. Consequently, the syntax of log4j configuration file (log-conf.xml) is different. You have 2 choices with Data Loader 58:
- Continue to use log-conf.xml after converting it from log4j 1.x to log4j 2.x syntax
- Delete log-conf.xml and place [log4j2.properties](https://github.com/forcedotcom/dataloader/blob/master/src/main/resources/log4j2.properties) file from configs sub-folder of the data loader installation folder into the configuration folder of your choice.

**Comment by chimpanzee818** [comment]
@chimpanzee818 

ok got it thnqq
its get resolved.
new issue came with other data Loder i am opining new issue for that. 

thnqq
