### ISSUE TITLE
EncryptedDataSource has incorrect package statement

### ISSUE THREAD

**Issue by tggagne** [forcedotcom/dataloader#75]
Currently it reads:

```
package com.salesforce.dataloader.dao.database;
```

But it's not in that directory.  It's in the dao directory.

So we can either change the directory it's in or change the package statement.

Any suggestions?  I'm probably the only person using it right now, so modifying my database-conf and updating the doc in the class shouldn't be a big deal.

**Comment by ashitsalesforce** [comment]
line 26 of com.salesforce.dataloader.dao.EncryptedDataSource.java states:
`package com.salesforce.dataloader.dao;`

Perhaps it was addressed once you provided filed the issue but issue wasn't closed.
