### ISSUE TITLE
Where is dataloader-34.0-uber.jar in the download

### ISSUE THREAD

**Issue by maiden7705** [forcedotcom/dataloader#79]
I am confused about its usage.. so i have older version of CLIQ / dataloader uploading to sales force in our informatica / websphere application.
It was 2.6 from previous developer. I am new in this tool and asked to update the version to the latest 3.4 to test its bulk upload speed.
So far i am unable to locate, in this entire download, anything remotely called "dataloader-34.0-uber.jar"

**Comment by tgunz** [comment]
You have to build it. You'll need to clone the repo locally and actually follow the instructions.

**Comment by Mallikarjun24** [comment]
HI  tgunz ,
Could you please advise how to down load the dataloader APi 37.0 jar file,
i need to migrate the data from Data Loader v36.0 to Dataloader 37.0.
 
Regards
Mallik

**Comment by pgumiela** [comment]
@ashitsalesforce, can we close all these old Issues and keep only the ones that are reproducible and need attention?

**Comment by ashitsalesforce** [comment]
Hi Paul, thanks for reminding. We are working through a backlog. Closing this issue as it is not relevant anymore.
