### ISSUE TITLE
cannot load process-conf.xml

### ISSUE THREAD

**Issue by kazmitobe** [forcedotcom/dataloader#81]
The following error occurred.
I think the cause is 3f48c2f.

    ERROR [main] process.ProcessConfig getProcessInstance (ProcessConfig.java:96) - Error loading process: HyoukaInfoSetteiExport configuration from config file: C:\**********\config\process-conf.xml
    org.springframework.beans.factory.BeanDefinitionStoreException: IOException parsing XML document from URL [file://C:/**********/config/process-conf.xml]; nested exception is java.net.UnknownHostException: C

**Comment by rkaramc** [comment]
+1
Windows 7
Java 1.7.0_15

**Comment by rjmazzeo** [comment]
Bug fix checked in. It might take a week for the updated MSI to be available. It looks like it was due to https://github.com/forcedotcom/dataloader/commit/3f48c2f6a28ff15d8deb456488a9971999af8202

Revised it to avoid prefixing the path when a windows path is detected with drive letter.

**Comment by rjmazzeo** [comment]
Closing as the fix should be generally available. Go ahead and reopen or resubmit if you see the issue again.
