### ISSUE TITLE
How to insert environment variables into process-conf.xml

### ISSUE THREAD

**Issue by tggagne** [forcedotcom/dataloader#83]
I was kind of hoping I could use the ${env.variablename} syntax simialr to what's used with ant's build.xml file.  

I have a script that runs my dataloader from the commandline.  It looks like:

```
DrozBook:dataloader tgagne$ cat ~/bin/process 
#!/bin/bash
dataloaderdir=~/dataloader
version=27.0.1
version=30.0.0
version=34.0
version=33.0.0

if [ $# -gt 1 ]; then
    export ARG2=$2
fi

time java \
    -cp $dataloaderdir/dataloader-$version-uber.jar:$dataloaderdir/ojdbc6.jar:$dataloaderdir/postgresql-9.4-1201.jdbc4.jar:$dataloaderdir/sqljdbc4.jar \
    -Dsalesforce.config.dir=`pwd`  \
    com.salesforce.dataloader.process.ProcessRunner process.name=$1 | grep --line-buffered -vi "will be ignored since destination column is empty"
```

Inside process-conf.xml I wanted to use the argument to change the name of the CSV file I was reading from for an import.

```
<entry key="dataAccess.name" value="${env.ARG2}" />
```

But alas, dataloader didn't swallow it.

```
Caused by: com.salesforce.dataloader.exception.DataAccessObjectInitializationException: File: /Users/tgagne/git/customer/dataloader/${env.ARG2} not found.  Open failed.
```

The way this is done in build.xml is with the tag

```
<property environment="env"/>
```

But sticking it near the top of process-conf.xml just blows-up the stack.

​Is there something I'm missing or is it impossible to do such a thing with process-conf.xml?

**Comment by rjmazzeo** [comment]
At this point process-conf.xml doesn't have this kind of parameter substitution. Until a feature like this gets prioritized you can workaround the issue with by using sed to generate a final process-conf.xml in your BASH script. 

Something like 
cat process-template.xml | sed 's/${env\.ARG2}/FINALPARAMHERE/' > process-conf.xml

**Comment by dsipasseuth** [comment]
Why not just use a configuration like the one your are already using with salesforce.config.dir by passing -Denv.ARG2=filename in your bash call ?

Anyway, using Spring you can what you are trying to achieve might be possible with either PropertyPlaceHolder or by using Spring Expression Language (process-conf.xml is, after all, only just a bean list definition anyway). 
You can access system properties (of JVM) like that : #{ systemProperties['user.region'] }

**Comment by rjmazzeo** [comment]
I'll add it to the feature want list. I'll be the develop branch for the next few months. If the edit is made, I can let you know. In the meantime if you feel like it you can fork the repository, make the change and submit a pull request.

**Comment by bigassforce** [comment]
### Workaround with variable substitution:

1. Prepare temp file using some task that _does_ support variable substitution (eg `echoxml`)

```
<tempfile
    property="sdl.tmp"
    destdir="process"
    prefix="sdl"
    suffix=".tmp"
    createfile="true"
    deleteonexit="true"
/>
```

2. Configure lean process-conf.xml using import statement to pull in the temp file

```
<!DOCTYPE beans PUBLIC "" "lib/spring-beans.dtd">
<beans>
  <import resource="sdl*" />
</beans>
```

3. Populate temp file (with credentials etc) at runtime, which will be cleaned up automatically...

```
<echo file="${sdl.tmp}" message="&lt;!DOCTYPE beans PUBLIC &quot;&quot; &quot;lib/spring-beans.dtd&quot;&gt;" />
<echoxml file="${sdl.tmp}" append="true">
    <beans>
        <bean class="com.salesforce.dataloader.process.ProcessRunner" id="extract" singleton="false">
            <property name="name" value="extract" />
            <property name="configOverrideMap">
                <map>
                    <entry key="dataAccess.type" value="databaseWrite" />
                    <entry key="dataAccess.name" value="extractConfig" />
                    <entry key="process.operation" value="extract" />
                    <entry key="sfdcInternal" value="true" />
                    <entry key="sfdcInternal.isSessionIdLogin" value="true" />
                    <entry key="sfdc.endpoint" value="${sf.serverUrl}" />
                    <entry key="sfdcInternal.sessionId" value="${sf.sessionId" />
                </map>
            </property>
        </bean>
    </beans>
</echoxml>
```

Pros:
- no special tokens or search/replace required
- credentials don't hang around in filesystem or vcs

Cons:
- build script gets bloated with xml bean generation mess
- care required around multiple jobs due to wildcard import

**Comment by ashitsalesforce** [comment]
The workaround suggested by rjmazzeo should work if it is put in a wrapper script for process.bat. The wrapper can generate process-conf.xml from a template and then invoke process.bat.
