### ISSUE TITLE
Provide steps and/or pre-requisite for running dataloader unit test on sandbox environment.

### ISSUE THREAD

**Issue by dsipasseuth** [forcedotcom/dataloader#89]
Hi, 

I'd really like to be able to run the unit test of data loader on a dedicated sandbox.
Some custom fields are not present in a default sandbox so i have to manually create them. 

Is it possible to have some guidance (or a script) for setting up the environment and running tests ?

Hacking around the project would be easier/safer if testing could be done before making pull requests. 

Thx

**Comment by rjmazzeo** [comment]
We are working on that in the coming weeks. A lot of the unit tests require an active salesforce org with certain conditions. Most of this is lost to time so we are in the processes of restablishing confidence metrics for making changes. Next time I'm in there I'll make a pass at isolating true unit tests from functional and integration tests. The documentation for setting up integration and functional testing will be a bit further out.

**Comment by rjmazzeo** [comment]
Good news on this one. I have all tests passing.  A few had stagnated but most of them were ok.

I have to sanitize an internal document on how to setup an org but once setup it, you should be good.

**Comment by rjmazzeo** [comment]
https://github.com/forcedotcom/dataloader/wiki/Testing-Dataloader

It's a working guide. This is just my brief guide. Let me know if you run into troubles with it.
