### ISSUE TITLE
Add a way to configure the exit code when running CLI.

### ISSUE THREAD

**Issue by dsipasseuth** [forcedotcom/dataloader#90]
Hi,

When running the data loader in command line, it would be nice to be able to configure the data loader to return a "configurable" exit code based on number of line in success / error or error code from SalesForce API. (either bulk or soap but they should be kept separate as they are not the same).

it should be kept simple but would meet most basic (don't want to go through ratio stuff, etc...) needs like : 
no success, no error
full success, no error
no success, full error
partial success, partial error
per error type mapping (job based)

**Comment by rjmazzeo** [comment]
The error code from the Salesforce API seems pretty doable in a reasonable timeframe but the other features will take a little thought and prioritization.

**Comment by dsipasseuth** [comment]
I've started an implementation of my own.

Doesn't seems to complicated. but i don't think i've cover all use cases.

**Comment by rjmazzeo** [comment]
awesome! Please send the pull request when you get further along.

**Comment by dsipasseuth** [comment]
A partial implementation is already available in my github as a branch.

I just want to be able to run all test before making any pull request.

Issue #89 may be ?

**Comment by rjmazzeo** [comment]
I'm working on it :). I've isolated the clean unit tests that do not require an active environment and are reasonably performant. Next step, start running the unit tests against clean orgs and documenting configuration requirements..etc.

**Comment by rjmazzeo** [comment]
https://github.com/forcedotcom/dataloader/wiki/Testing-Dataloader

**Comment by zefreak** [comment]
What is the status of this?

**Comment by ashitsalesforce** [comment]
closing the issue as data loader is in a maintenance mode with only critical bug fixes and version updates.
