### ISSUE TITLE
getting error on insert modified "csv" file.

### ISSUE THREAD

**Issue by HUMENTH** [forcedotcom/dataloader#910]
**Describe the bug**

![image](https://github.com/forcedotcom/dataloader/assets/4609678/664223d1-ccc5-40ad-9868-73c01709a6b1)

**To Reproduce**
1. Install version V59.0.0
2. login with credential
3. export data in csv file.
4. open csv file and save (no need to make changes)
5. click on insert and "Choose CSV file"
6. click on "Next"
7. see error

**Expected behavior**
![image](https://github.com/forcedotcom/dataloader/assets/4609678/864cc2bf-c919-4516-b168-cb4ffe95b4fe)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version V59.0.0

**Additional context**
working fine with previous version.
my salesforce instance is already on API 59

![image](https://github.com/forcedotcom/dataloader/assets/4609678/f1cfa50b-e24a-489e-a032-694fb55ddc6a)

**Comment by ashitsalesforce** [comment]
Hi @HUMENTH , can you share a sample CSV that fails with v59.0.0? Also, provide the error message in the log file or on the console when the failure occurs.

**Comment by HUMENTH** [comment]
these are my settings

![image](https://github.com/forcedotcom/dataloader/assets/4609678/4bcf88b1-5093-49a2-bbbf-1fb4f99a32af)

> this settings window is not expanding properly.

**Comment by HUMENTH** [comment]
@ashitsalesforce 
> Can you wrap every field in double-quotes and try the upload to eliminate the possibility of using incorrect delimiter?

I have tried enclosing each field in double quotes, which seems to have resolved the error. However, I don't consider this a viable solution, as I don't have to do this with the previous version of the dataloader, v58.0.4, which worked fine without any issues.

**Comment by ashitsalesforce** [comment]
Hi @HUMENTH , the fact that enclosing each field in double-quotes works indicates that the issue has to do with data loader code using a character besides comma as delimiter. Can you try the original CSV upload after removing all characters specified in "Other Delimiters for load operations" in Advanced Settings dialog?

**Comment by HUMENTH** [comment]
@ashitsalesforce 
Thanks, it's working as normal after removing characters from "Other Delimiters for load operations".

**Comment by ashitsalesforce** [comment]
Good question. To answer that definitively, I need the value of the following properties in `config.properties` file when the issue occurs:
```
loader.csvOther
loader.csvOtherValue
```
Given that the issue is gone, the current value of these two properties is not useful in identifying the root-cause. If you can somehow backtrack and reproduce the issue, capture the value of the two properties and let us know.

**Comment by HUMENTH** [comment]
@ashitsalesforce 
Please find below required values.

```
loader.csvOther=true
loader.csvOtherValue=-
```

> loader.csvOtherValue=-

hyphen "-" is preset value in dataloader with fresh installation.

**Comment by ashitsalesforce** [comment]
Yes, that's right. Are you seeing the issue with a fresh installation? I ask because I don't.

**Comment by ashitsalesforce** [comment]
Also, I can reproduce the error in v58.0.4 and v59.0.0 if I add '/' character to the list of other delimiters for load operation. 
<img width="406" alt="Screenshot 2023-12-05 at 11 03 47 PM" src="https://github.com/forcedotcom/dataloader/assets/71143047/842cb343-7e8e-4368-b96d-cb6c254f081d">

**Comment by ashitsalesforce** [comment]
Yes, that's right.

**Comment by HUMENTH** [comment]
@ashitsalesforce 
I believe the root cause of the issue remains unidentified. The data loader seems to function properly when importing the same exported CSV file without any modifications. However, the issue arises when changes are made to the imported CSV file or even when the CSV file is simply opened and saved without making any changes.

This needs further investigation.

> OS: Windows 11 Pro
> Application: MS Excel (Office 365:Insider)

**Comment by HUMENTH** [comment]
@bmercernccer please check my previous comment.

**Comment by bmercernccer** [comment]
@HUMENTH You mentioned that "the issue arises when changes are made to the exported CSV file or even when the CSV file is simply opened and saved without making any changes." 
What software did you use to open and save the CSV file? 

Some programs may make changes to a CSV file when opening and saving it. Excel is one example.

**Comment by ashitsalesforce** [comment]
@HUMENTH , we are unable to reproduce the issue by opening and saving CSV file you have provided using Excel on Windows 11. So, as of now we cannot make further progress unless we have a CSV file or steps to reliably reproduce the issue.

**Comment by HUMENTH** [comment]
@ashitsalesforce can you please confirm your some details?
Your 
OS:?
CSV editor:? With complete version number, so I will try on the same build/version.
