### ISSUE TITLE
Import of CSV Files with UTF8 Encoding with BOM Fails

### ISSUE THREAD

**Issue by dsipasseuth** [forcedotcom/dataloader#94]
The bug is most likely in force-wsc component in the CSVReader class.
When reading the header, it does not ignore BOM and see the double quote as not escaped.
[BuggedFile.txt](https://github.com/forcedotcom/dataloader/files/58073/BuggedFile.txt)

**Comment by ashitsalesforce** [comment]
This issue will be addressed in v52 by using BOMInputStream in CSVFileReader.java.
