### ISSUE TITLE
Parser was expecting element 'urn:partner.soap.sforce.com:filterable' but found 'urn:partner.soap.sforce.com:encrypted'

### ISSUE THREAD

**Issue by tggagne** [forcedotcom/dataloader#99]
I was testing the dataloader today using an object with a platform-encrypted field.  Dataloader complained in both the CLI and GUI versions:

```
2016-01-04 14:25:04,640 INFO  [exportAccount] process.ProcessRunner run (ProcessRunner.java:137) - Setting field types
2016-01-04 14:25:04,987 ERROR [exportAccount] client.PartnerClient runOperation (PartnerClient.java:332) - Error while calling web service operation: describeSObject, error was: Unexpected element. Parser was expecting element 'urn:partner.soap.sforce.com:filterable' but found 'urn:partner.soap.sforce.com:encrypted'
com.sforce.ws.ConnectionException: Unexpected element. Parser was expecting element 'urn:partner.soap.sforce.com:filterable' but found 'urn:partner.soap.sforce.com:encrypted'
```

Has anyone ran across this yet?

**Comment by tggagne** [comment]
Dataloader.io also crashed trying to describe the object with, "Oops!  Error fetching object fields."

**Comment by tggagne** [comment]
I'm wondering if all that's needed is a new partner.wsdl, but am unsure.

I downloaded a new one and noticed it includes "encrypted" and tried building a new partner.jar.
```
java -classpath force-wsc-35.2.7.jar:ST-4.0.8.jar com.sforce.ws.tools.wsdlc partner.wsdl partner.jar 
```
But when I tried using it with dataloader (inserting it into the class path), it complained:
```
2016-01-12 23:16:17,097 FATAL [main] process.ProcessRunner topLevelError (ProcessRunner.java:238) - Unable to run process exportAccount
java.lang.NoSuchMethodError: com.sforce.soap.partner.PartnerConnection.setCallOptions(Ljava/lang/String;Ljava/lang/String;)V
	at com.salesforce.dataloader.client.PartnerClient.login(PartnerClient.java:482)
	at com.salesforce.dataloader.client.PartnerClient.connect(PartnerClient.java:213)
	at com.salesforce.dataloader.controller.Controller.login(Controller.java:173)
	at com.salesforce.dataloader.controller.Controller.login(Controller.java:168)
	at com.salesforce.dataloader.process.ProcessRunner.run(ProcessRunner.java:128)
	at com.salesforce.dataloader.process.ProcessRunner.run(ProcessRunner.java:100)
	at com.salesforce.dataloader.process.ProcessRunner.main(ProcessRunner.java:253)
```

Any ideas?

**Comment by rjmazzeo** [comment]
Yup. Ran into the same issues when we revved wsc to version 36. Setcalloptions got a breaking change in the upgrade to v36. The error you are listing is what happens a v36 wsc jar tries to connect to a target environment running v35. You'll have to either wait a few weeks for v36 to make it to all environments or edit the maven dependencies and change the wsc version to 35. You will also have to fix calls to that method one after applying v35.

**Comment by tggagne** [comment]
@rjmazzeo , did you ever see the error with the encrypted thing above, or do you think that's also a version problem?

**Comment by rjmazzeo** [comment]
No, I have not seen that. It sounds similar but it could also be an api bug. Have you tried it on workbench.developerforce.com? My rule of thumb is if the entity is queryable there then it should *generally* work in data loader.

**Comment by tggagne** [comment]
It works on workbench.developerforce.com using both APIs 34 and 35.  Force CLI also seems to work.  But as I noted, dataloader.io and dataloader don't work.  

So you're suggesting the new build of dataloader for 36 will work when that version rolls out, but 35 will not?

**Comment by rjmazzeo** [comment]
No, You mentioned v35 but since you are on github we published v36 last month and it sounded like a deserialization issue you might encounter on versioning. I've never worked with the data type you mentioned. I'll try a hello world with it today.

**Comment by rjmazzeo** [comment]
I turned on platform encryption, encrypted account name and a few other account fields. I connected and extracted the records without issue (they were all masked but I wasn't testing platform encryption itself). 

Granted this using dataloader v36 on a v36 enabled org. Try the dataloader that is bundled with your target org just to make sure it's not a version issue.

If it still repros then you will have to call in to support.  We would need the tooling they have to debug it.

**Comment by ashitsalesforce** [comment]
Closing this issue as it is old and likely addressed by now.

**Comment by jhabarunk** [comment]
After updating force-partner-api & force-wsc dependencies version to 49.0.0, getting below error:
com.sforce.ws.ConnectionException: Unexpected element. Parser was expecting element 'urn:partner.soap.sforce.com:currencySymbol' but found 'urn:partner.soap.sforce.com:chatterExternal'

**Comment by ashitsalesforce** [comment]
Hi @jhabarunk , have you tried the latest release - v51.0.1, available at https://github.com/forcedotcom/dataloader/releases/tag/v51.0.1 ?

**Comment by jhabarunk** [comment]
Hi @ashitsalesforce, thanks for the quick response. It was not an issue from SF side.  Basically the WAR of my project was containing two versions each of force-partner-api & force-wsc dependencies (v35 & v49). Due to this issue at runtime, it was deserializing the response using v35 class files and was failing as v35  GetUserInfoResult class does not contain urn:partner.soap.sforce.com:chatterExternal element

**Comment by ashitsalesforce** [comment]
Hi @jhabarunk , thanks for updating the discussion thread. Glad to hear that you were able to resolve the issue.
